# Generated by Django 5.1.7 on 2025-11-01 05:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('users', '0003_rename_name_user_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='보유 수량', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('average_price', models.DecimalField(decimal_places=4, help_text='평균 매수가', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, help_text='투자 메모', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_portfolio',
                'indexes': [models.Index(fields=['user', 'stock'], name='users_portf_user_id_47a5d6_idx'), models.Index(fields=['user', '-updated_at'], name='users_portf_user_id_6a9ea0_idx')],
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
