# Generated by Django 5.1.7 on 2025-11-21 07:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='stop_loss_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='손절가 (하한가)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='목표 매도가', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
