# Generated by Django 5.1.7 on 2025-12-09 07:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_cashflowstatement_proceeds_from_issuance_of_long_term_debt_and_capital_securities_net'),
        ('users', '0005_add_target_stop_loss_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='관심종목 리스트 이름 (예: 진입준비, 기술주)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='리스트 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_watchlist',
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_entry_price', models.DecimalField(blank=True, decimal_places=4, help_text='목표 진입가', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, help_text='메모')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('position_order', models.IntegerField(default=0, help_text='리스트 내 표시 순서')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.watchlist')),
            ],
            options={
                'db_table': 'users_watchlist_item',
                'ordering': ['position_order', '-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', '-updated_at'], name='users_watch_user_id_b385df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['watchlist', 'position_order'], name='users_watch_watchli_a50443_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['watchlist', '-added_at'], name='users_watch_watchli_6541e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('watchlist', 'stock')},
        ),
    ]
