# Generated by Django 5.1.7 on 2025-12-08 11:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='원본 기사 URL', max_length=2000, unique=True)),
                ('url_hash', models.CharField(db_index=True, editable=False, help_text='URL SHA256 해시 (중복 체크용)', max_length=64)),
                ('title', models.CharField(help_text='기사 제목', max_length=500)),
                ('summary', models.TextField(blank=True, help_text='기사 요약')),
                ('image_url', models.URLField(blank=True, help_text='대표 이미지 URL', max_length=2000)),
                ('source', models.CharField(db_index=True, help_text='뉴스 출처', max_length=100)),
                ('published_at', models.DateTimeField(db_index=True, help_text='발행 일시')),
                ('language', models.CharField(default='en', help_text='언어 코드', max_length=5)),
                ('category', models.CharField(choices=[('general', 'General'), ('company', 'Company'), ('forex', 'Forex'), ('crypto', 'Crypto'), ('merger', 'Merger')], default='general', help_text='뉴스 카테고리', max_length=20)),
                ('finnhub_id', models.BigIntegerField(blank=True, help_text='Finnhub 기사 ID', null=True)),
                ('marketaux_uuid', models.CharField(blank=True, help_text='Marketaux 기사 UUID', max_length=50)),
                ('sentiment_score', models.DecimalField(blank=True, db_index=True, decimal_places=3, help_text='감성 점수 (-1.000 ~ +1.000)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-1.000')), django.core.validators.MaxValueValidator(Decimal('1.000'))])),
                ('sentiment_source', models.CharField(choices=[('marketaux', 'Marketaux'), ('computed', 'Computed'), ('none', 'None')], default='none', help_text='감성 분석 출처', max_length=20)),
                ('is_press_release', models.BooleanField(default=False, help_text='보도 자료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_articles',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at', 'category'], name='news_articl_publish_629129_idx'), models.Index(fields=['source', '-published_at'], name='news_articl_source_6b9a79_idx'), models.Index(fields=['sentiment_score', '-published_at'], name='news_articl_sentime_cad86b_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='종목 심볼', max_length=20)),
                ('entity_name', models.CharField(help_text='엔티티 이름', max_length=200)),
                ('entity_type', models.CharField(choices=[('equity', 'Equity'), ('index', 'Index'), ('etf', 'ETF'), ('cryptocurrency', 'Cryptocurrency'), ('currency', 'Currency'), ('mutualfund', 'Mutual Fund')], help_text='엔티티 타입', max_length=20)),
                ('exchange', models.CharField(blank=True, help_text='거래소', max_length=20)),
                ('country', models.CharField(blank=True, help_text='국가 코드', max_length=5)),
                ('industry', models.CharField(blank=True, help_text='산업 분류', max_length=100)),
                ('match_score', models.DecimalField(decimal_places=5, default=Decimal('1.00000'), help_text='매칭 신뢰도', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00000')), django.core.validators.MaxValueValidator(Decimal('1.00000'))])),
                ('sentiment_score', models.DecimalField(blank=True, db_index=True, decimal_places=3, help_text='엔티티별 감성 점수', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-1.000')), django.core.validators.MaxValueValidator(Decimal('1.000'))])),
                ('source', models.CharField(choices=[('finnhub', 'Finnhub'), ('marketaux', 'Marketaux')], help_text='데이터 소스', max_length=20)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='news.newsarticle')),
            ],
            options={
                'db_table': 'news_entities',
            },
        ),
        migrations.CreateModel(
            name='EntityHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_text', models.TextField(help_text='하이라이트 텍스트')),
                ('sentiment', models.DecimalField(decimal_places=3, help_text='하이라이트 감성 점수', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('-1.000')), django.core.validators.MaxValueValidator(Decimal('1.000'))])),
                ('location', models.CharField(choices=[('title', 'Title'), ('main_text', 'Main Text')], help_text='하이라이트 위치', max_length=20)),
                ('news_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='news.newsentity')),
            ],
            options={
                'db_table': 'entity_highlights',
                'ordering': ['-sentiment'],
            },
        ),
        migrations.CreateModel(
            name='SentimentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='종목 심볼', max_length=20)),
                ('date', models.DateField(db_index=True, help_text='집계 날짜')),
                ('avg_sentiment', models.DecimalField(decimal_places=3, help_text='평균 감성 점수', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('-1.000')), django.core.validators.MaxValueValidator(Decimal('1.000'))])),
                ('news_count', models.PositiveIntegerField(help_text='뉴스 건수')),
                ('positive_count', models.PositiveIntegerField(default=0, help_text='긍정 뉴스 건수')),
                ('negative_count', models.PositiveIntegerField(default=0, help_text='부정 뉴스 건수')),
                ('neutral_count', models.PositiveIntegerField(default=0, help_text='중립 뉴스 건수')),
            ],
            options={
                'db_table': 'sentiment_history',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', '-date'], name='sentiment_h_symbol_4e86f8_idx'), models.Index(fields=['-date', 'avg_sentiment'], name='sentiment_h_date_17cd39_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='newsentity',
            index=models.Index(fields=['symbol', 'entity_type'], name='news_entiti_symbol_3e0e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='newsentity',
            index=models.Index(fields=['sentiment_score'], name='news_entiti_sentime_cd9ca5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newsentity',
            unique_together={('news', 'symbol')},
        ),
    ]
