# Generated by Django 5.1.7 on 2026-02-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNewsKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='키워드 추출 날짜', unique=True)),
                ('keywords', models.JSONField(default=list, help_text='\n            키워드 리스트\n            [{\n                "text": "AI 반도체",\n                "sentiment": "positive|negative|neutral",\n                "related_symbols": ["NVDA", "AMD"],\n                "importance": 0.95\n            }]\n        ')),
                ('total_news_count', models.PositiveIntegerField(default=0, help_text='분석에 사용된 뉴스 총 건수')),
                ('sources', models.JSONField(default=dict, help_text='소스별 뉴스 건수 {"finnhub": 45, "marketaux": 5}')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='키워드 추출 상태', max_length=20)),
                ('llm_model', models.CharField(default='gemini-2.5-flash', help_text='사용된 LLM 모델', max_length=50)),
                ('generation_time_ms', models.PositiveIntegerField(blank=True, help_text='LLM 생성 시간 (밀리초)', null=True)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, help_text='프롬프트 토큰 수', null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, help_text='응답 토큰 수', null=True)),
                ('error_message', models.TextField(blank=True, help_text='실패 시 에러 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_news_keywords',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date', 'status'], name='daily_news__date_142952_idx')],
            },
        ),
    ]
