# Generated by Django 5.1.7 on 2026-02-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_daily_news_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCollectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('sector', 'Sector'), ('sub_sector', 'Sub-Sector'), ('custom', 'Custom')], max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('max_symbols', models.PositiveIntegerField(default=20)),
                ('last_collected_at', models.DateTimeField(blank=True, null=True)),
                ('last_article_count', models.PositiveIntegerField(default=0)),
                ('last_symbol_count', models.PositiveIntegerField(default=0)),
                ('total_collections', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_collection_categories',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='news_collec_is_acti_6ea2f6_idx')],
            },
        ),
    ]
