# Generated by Django 5.1.7 on 2026-02-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_collection_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trained_at', models.DateTimeField(auto_now_add=True, help_text='학습 완료 시각')),
                ('model_version', models.CharField(help_text='모델 버전 (예: lr_v1_week8)', max_length=50)),
                ('algorithm', models.CharField(default='logistic_regression', help_text='알고리즘 (logistic_regression, lightgbm)', max_length=50)),
                ('training_samples', models.PositiveIntegerField(help_text='학습 데이터 건수')),
                ('feature_count', models.PositiveIntegerField(default=5, help_text='feature 수')),
                ('f1_score', models.FloatField(help_text='F1 Score')),
                ('precision', models.FloatField(blank=True, help_text='Precision', null=True)),
                ('recall', models.FloatField(blank=True, help_text='Recall', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy', null=True)),
                ('weights', models.JSONField(blank=True, help_text='Engine C β₁~β₅ 가중치', null=True)),
                ('smoothed_weights', models.JSONField(blank=True, help_text='Smoothing 적용 후 가중치 (0.7×new + 0.3×prev)', null=True)),
                ('feature_importance', models.JSONField(blank=True, help_text='Feature importance 리포트', null=True)),
                ('training_config', models.JSONField(blank=True, help_text='학습 설정 (window, split 등)', null=True)),
                ('safety_gate_passed', models.BooleanField(default=False, help_text='Safety Gate 통과 여부')),
                ('safety_gate_details', models.JSONField(blank=True, help_text='Safety Gate 상세 결과', null=True)),
                ('deployment_status', models.CharField(choices=[('shadow', 'Shadow Mode'), ('deployed', 'Deployed'), ('rolled_back', 'Rolled Back'), ('failed', 'Failed')], default='shadow', help_text='배포 상태', max_length=20)),
                ('deployed_at', models.DateTimeField(blank=True, help_text='실적용 시각', null=True)),
                ('shadow_comparison', models.JSONField(blank=True, help_text='Shadow Mode: ML vs 수동 선별 비교 리포트', null=True)),
            ],
            options={
                'db_table': 'ml_model_history',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='importance_score',
            field=models.FloatField(blank=True, db_index=True, help_text='규칙 기반 중요도 점수 (Engine C)', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='llm_analysis',
            field=models.JSONField(blank=True, help_text='LLM 심층 분석 결과 JSON', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='llm_analyzed',
            field=models.BooleanField(db_index=True, default=False, help_text='LLM 심층 분석 완료 여부'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='ml_label_24h',
            field=models.FloatField(blank=True, help_text='발행 후 다음 거래일 변동폭 (%)', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='ml_label_confidence',
            field=models.FloatField(blank=True, help_text='Label 신뢰도 (0~1)', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='ml_label_important',
            field=models.BooleanField(blank=True, help_text='섹터별 threshold 적용 중요 뉴스 여부', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='ml_label_updated_at',
            field=models.DateTimeField(blank=True, help_text='ML Label 업데이트 시간', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='rule_sectors',
            field=models.JSONField(blank=True, help_text='규칙 엔진 추출 섹터 리스트', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='rule_tickers',
            field=models.JSONField(blank=True, help_text='규칙 엔진 추출 티커 리스트', null=True),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['importance_score', '-published_at'], name='news_articl_importa_f276e5_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['llm_analyzed', '-published_at'], name='news_articl_llm_ana_a547e4_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodelhistory',
            index=models.Index(fields=['-trained_at', 'deployment_status'], name='ml_model_hi_trained_ea6d99_idx'),
        ),
    ]
