# Generated by Django 5.1.7 on 2026-03-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_intelligence_pipeline_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='alphavantage_id',
            field=models.CharField(blank=True, help_text='Alpha Vantage 기사 ID', max_length=200),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='fmp_id',
            field=models.CharField(blank=True, help_text='FMP 기사 ID', max_length=200),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='아카이브 여부'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_official',
            field=models.BooleanField(default=False, help_text='공식 발표 (보도자료 등)'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('company', 'Company'), ('press_release', 'Press Release'), ('forex', 'Forex'), ('crypto', 'Crypto'), ('merger', 'Merger')], default='general', help_text='뉴스 카테고리', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='sentiment_source',
            field=models.CharField(choices=[('marketaux', 'Marketaux'), ('alpha_vantage', 'Alpha Vantage'), ('fmp', 'FMP'), ('computed', 'Computed'), ('none', 'None')], default='none', help_text='감성 분석 출처', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsentity',
            name='source',
            field=models.CharField(choices=[('finnhub', 'Finnhub'), ('marketaux', 'Marketaux'), ('fmp', 'FMP'), ('alpha_vantage', 'Alpha Vantage')], help_text='데이터 소스', max_length=20),
        ),
        migrations.CreateModel(
            name='NewsCollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('symbols_tried', models.IntegerField(default=0)),
                ('articles_new', models.IntegerField(default=0)),
                ('articles_dup', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('duration_sec', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'news_collection_logs',
                'indexes': [models.Index(fields=['provider', '-executed_at'], name='news_collec_provide_e72e90_idx')],
            },
        ),
    ]
