# Generated by Django 5.1.7 on 2026-03-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_multi_provider_news_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('consecutive_task_failure', '태스크 연속 실패'), ('ml_f1_decline', 'ML F1 급락'), ('keyword_extraction_failure', '키워드 추출 실패'), ('llm_error_spike', 'LLM 에러율 급등'), ('neo4j_unavailable', 'Neo4j 연결 실패'), ('collection_drop', '수집량 급감'), ('unclassified_backlog', '미분류 뉴스 누적')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, help_text='예: {"task_name": "collect_sp500_news_fmp_batch", "error_count": 3}', null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_alert_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved', '-created_at'], name='news_alert__is_reso_0dd2dc_idx'), models.Index(fields=['trigger_type', '-created_at'], name='news_alert__trigger_037ea3_idx')],
            },
        ),
    ]
