# Generated by Django 5.2.14 on 2026-07-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSignalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_key', models.CharField(max_length=64, unique=True)),
                ('as_of', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('z_score', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('grade', models.CharField(choices=[('gray', 'gray'), ('yellow', 'yellow'), ('orange', 'orange'), ('red', 'red')], max_length=8)),
                ('detail', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credit_signal_state',
            },
        ),
        migrations.CreateModel(
            name='MacroSeriesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(db_index=True, max_length=32)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('revised_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'macro_series_history',
                'indexes': [models.Index(fields=['series_id', '-date'], name='macro_serie_series__1216ee_idx')],
                'constraints': [models.UniqueConstraint(fields=('series_id', 'date'), name='uniq_series_date')],
            },
        ),
    ]
