# Generated by Django 5.2.14 on 2026-07-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtfNavHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('date', models.DateField()),
                ('nav', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('revised_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'etf_nav_history',
                'indexes': [models.Index(fields=['symbol', '-date'], name='etf_nav_his_symbol_b4e0f4_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'date'), name='uniq_etf_symbol_date')],
            },
        ),
    ]
