# Generated by Django 5.2.14 on 2026-07-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_signals', '0002_etf_nav_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfnavhistory',
            name='nav_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
