# Generated by Django 5.2.14 on 2026-07-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychainevidence',
            name='grounded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplychainevidence',
            name='grounding_method',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supplychainevidence',
            name='grounding_status',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('normalized_match', 'Normalized match'), ('not_found', 'Not found'), ('missing_source', 'Missing source')], max_length=20, null=True),
        ),
    ]
