# Generated by Django 5.2.14 on 2026-07-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_pipeline', '0002_supplychainevidence_grounded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychainevidence',
            name='grounding_status',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('normalized_match', 'Normalized match'), ('partial_match', 'Partial match'), ('not_found', 'Not found'), ('missing_source', 'Missing source')], max_length=20, null=True),
        ),
    ]
