# Generated by Django 5.2.14 on 2026-08-11 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_pipeline', '0003_alter_supplychainevidence_grounding_status'),
        ('stocks', '0013_analystsignalsnapshot_spot_at_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='unmatchedcompanyqueue',
            name='source_form',
            field=models.CharField(db_index=True, default='10-K', help_text='미해소 이름의 출처 form (10-K / 8-K). first-seen 기준.', max_length=10),
        ),
        migrations.CreateModel(
            name='SEC8KFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cik', models.CharField(max_length=10)),
                ('accession_no', models.CharField(max_length=30, unique=True)),
                ('filing_date', models.DateField(db_index=True, help_text='8-K 제출일 = 이벤트 시점(핵심).')),
                ('items', models.JSONField(blank=True, default=list, help_text='보고된 item 코드 목록 예: ["1.01","9.01"]')),
                ('primary_doc_url', models.URLField(blank=True, default='', max_length=500)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('extracted', 'Extracted'), ('empty', 'Empty'), ('failed', 'Failed')], default='collected', max_length=12)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(db_column='symbol_id', on_delete=django.db.models.deletion.CASCADE, related_name='sec_8k_filings', to='stocks.stock')),
            ],
            options={
                'db_table': 'sec_8k_filing',
                'ordering': ['-filing_date'],
            },
        ),
        migrations.CreateModel(
            name='SEC8KCounterpartyEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_symbol', models.CharField(help_text='8-K 제출 기업(관계 원점).', max_length=20)),
                ('raw_target_name', models.CharField(help_text='원문에서 추출된 상대 기업명.', max_length=200)),
                ('resolved_ticker', models.CharField(blank=True, default='', help_text='ticker_matcher 해소 결과(빈값=미해소).', max_length=20)),
                ('match_method', models.CharField(blank=True, default='', help_text='alias/exact/fuzzy(현행 ticker_matcher).', max_length=20)),
                ('relationship_type', models.CharField(choices=[('PARTNER_WITH', 'Partner With'), ('SUPPLIES_TO', 'Supplies To'), ('DEPENDS_ON', 'Depends On'), ('ACQUIRED', 'Acquired')], max_length=20)),
                ('item_code', models.CharField(help_text='출처 item 예: "1.01"/"2.01".', max_length=10)),
                ('filing_date', models.DateField(db_index=True, help_text='filing 시점(비정규화, 착지 관계의 시점 정보).')),
                ('evidence_text', models.TextField(blank=True, default='', help_text='상대 기업 지목 문장 발췌.')),
                ('landed', models.BooleanField(db_index=True, default=False, help_text='RelationConfidence evidence 착지 여부.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='sec_pipeline.sec8kfiling')),
            ],
            options={
                'db_table': 'sec_8k_counterparty_evidence',
            },
        ),
        migrations.AddIndex(
            model_name='sec8kfiling',
            index=models.Index(fields=['symbol', '-filing_date'], name='sec_8k_fili_symbol__959dca_idx'),
        ),
        migrations.AddIndex(
            model_name='sec8kfiling',
            index=models.Index(fields=['status'], name='sec_8k_fili_status_902d35_idx'),
        ),
        migrations.AddIndex(
            model_name='sec8kcounterpartyevidence',
            index=models.Index(fields=['source_symbol', 'relationship_type'], name='sec_8k_coun_source__8e8466_idx'),
        ),
        migrations.AddIndex(
            model_name='sec8kcounterpartyevidence',
            index=models.Index(fields=['resolved_ticker'], name='sec_8k_coun_resolve_91a94f_idx'),
        ),
        migrations.AddIndex(
            model_name='sec8kcounterpartyevidence',
            index=models.Index(fields=['landed'], name='sec_8k_coun_landed_3a5bee_idx'),
        ),
    ]
