# Generated by Django 5.1.7 on 2026-04-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketpulse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefinglog',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='LLM 호출 비용 USD', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='briefinglog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marketpulsenews',
            name='category_confidence',
            field=models.FloatField(default=0.0, help_text='분류 신뢰도 0.0~1.0'),
        ),
        migrations.AddField(
            model_name='marketpulsenews',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='marketpulsenews',
            name='paired_with_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketpulsenews',
            name='relevance_score',
            field=models.FloatField(default=0.0, help_text='관련도 0.0~1.0'),
        ),
        migrations.AddField(
            model_name='marketpulsenews',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='-1.0~1.0 (null=미분석)', null=True),
        ),
        migrations.AddField(
            model_name='marketpulsenews',
            name='summary_ko',
            field=models.TextField(blank=True, default=''),
        ),
    ]
