# Generated by Django 5.2.14 on 2026-07-02 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_industryclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_date', models.DateField()),
                ('signal_tag', models.CharField(max_length=10)),
                ('confidence', models.CharField(max_length=20)),
                ('composite_score', models.FloatField(blank=True, null=True)),
                ('conf_ver', models.IntegerField(default=1)),
                ('rank', models.IntegerField()),
                ('published_at', models.DateTimeField()),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'db_table': 'stocks_issuance_log',
                'indexes': [models.Index(fields=['signal_date', 'signal_tag'], name='stocks_issu_signal__ea2ca4_idx')],
                'unique_together': {('stock', 'signal_date', 'signal_tag')},
            },
        ),
    ]
