# Generated by Django 5.2.14 on 2026-07-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_issuancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('surface', models.CharField(choices=[('dashboard_eod', 'Dashboard EOD 추천 카드'), ('chain_sight', 'Chain Sight 표면'), ('news_chip', '뉴스 스트립 칩')], max_length=32)),
                ('object_ref', models.CharField(max_length=128)),
                ('event_type', models.CharField(choices=[('impression', '노출'), ('click', '클릭')], max_length=16)),
                ('first_seen_at', models.DateTimeField()),
                ('seen_count', models.IntegerField(default=0)),
                ('session_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stocks_impression_log',
                'indexes': [models.Index(fields=['user_id', 'surface', 'object_ref'], name='stocks_impr_user_id_6b84e4_idx'), models.Index(fields=['user_id', 'event_type'], name='stocks_impr_user_id_744601_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_type', 'impression')), fields=('user_id', 'surface', 'object_ref'), name='uniq_impression_user_surface_object')],
            },
        ),
    ]
