# Generated by Django 5.2.14 on 2026-08-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_impressionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressionlog',
            name='surface',
            field=models.CharField(choices=[('dashboard_eod', 'Dashboard EOD 추천 카드'), ('chain_sight', 'Chain Sight 표면'), ('news_chip', '뉴스 스트립 칩'), ('coverage_detail', '커버리지 상세 페이지')], max_length=32),
        ),
    ]
