# Generated by Django 5.2.14 on 2026-08-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_alter_impressionlog_surface'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystSignalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(default='fmp', max_length=16)),
                ('target_consensus', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('target_high', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('target_low', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('target_median', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('grade_strong_buy', models.IntegerField(blank=True, null=True)),
                ('grade_buy', models.IntegerField(blank=True, null=True)),
                ('grade_hold', models.IntegerField(blank=True, null=True)),
                ('grade_sell', models.IntegerField(blank=True, null=True)),
                ('grade_strong_sell', models.IntegerField(blank=True, null=True)),
                ('grade_consensus', models.CharField(blank=True, default='', max_length=16)),
                ('grades_historical', models.JSONField(blank=True, default=list)),
                ('rating', models.CharField(blank=True, default='', max_length=4)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stocks_analyst_signal_snapshot',
                'ordering': ['symbol', '-captured_at'],
                'indexes': [models.Index(fields=['symbol', '-captured_at'], name='stocks_anal_symbol_e12509_idx')],
            },
        ),
    ]
