# Generated by Django 5.2.14 on 2026-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_analystsignalsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystsignalsnapshot',
            name='spot_at_capture',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
