# Generated by Django 5.2.14 on 2026-08-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_analystsignalsnapshot_spot_at_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cik',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
