# Generated by Django 5.2.14 on 2026-08-13 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_analystsignalsnapshot_spot_at_capture'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='분할 효력일 (FMP date, YYYY-MM-DD)')),
                ('numerator', models.DecimalField(decimal_places=6, max_digits=15)),
                ('denominator', models.DecimalField(decimal_places=6, max_digits=15)),
                ('split_type', models.CharField(blank=True, default='', help_text='FMP splitType 원문', max_length=32)),
                ('source', models.CharField(default='fmp', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='stocks.stock')),
            ],
            options={
                'verbose_name': 'Stock Split',
                'verbose_name_plural': 'Stock Splits',
                'db_table': 'stocks_stock_split',
                'indexes': [models.Index(fields=['stock', 'date'], name='stocks_stoc_stock_i_d30081_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
