# Generated by Django 5.2.14 on 2026-08-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_merge_0014_stock_cik_0014_stocksplit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('EARNINGS', 'Earnings'), ('DIVIDEND', 'Dividend'), ('SPLIT', 'Split')], max_length=16)),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('event_date', models.DateField(db_index=True, help_text='ET 기준. DIVIDEND는 ex-date.')),
                ('session', models.CharField(choices=[('BMO', 'Before Market Open'), ('AMC', 'After Market Close'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='EARNINGS 발표 세션 (BMO/AMC).', max_length=8)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('occurred', 'Occurred'), ('stale', 'Stale')], default='scheduled', help_text='stale = 재조회 창에서 소실(이동·철회 추정).', max_length=12)),
                ('eps_estimated', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('eps_actual', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('revenue_estimated', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('revenue_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dividend_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, default='', max_length=20)),
                ('split_numerator', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('split_denominator', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, help_text='최초 관측 시각.')),
                ('last_seen_at', models.DateTimeField(auto_now=True, help_text='최근 관측 시각(저장마다 갱신).')),
                ('date_observed_count', models.PositiveSmallIntegerField(default=1, help_text='동일 (type,symbol,date) 재관측 누적 → 날짜 안정 신호.')),
                ('source', models.CharField(default='fmp', max_length=16)),
                ('fmp_last_updated', models.DateTimeField(blank=True, help_text='FMP lastUpdated 원문.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'db_table': 'shared_calendar_event',
                'ordering': ['event_date', 'symbol'],
                'indexes': [models.Index(fields=['symbol', 'event_date'], name='shared_cale_symbol_164fc4_idx'), models.Index(fields=['event_date', 'event_type'], name='shared_cale_event_d_e66c33_idx')],
                'unique_together': {('event_type', 'symbol', 'event_date')},
            },
        ),
    ]
