# Generated by Django 5.2.14 on 2026-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='exclude_reason',
            field=models.CharField(blank=True, choices=[('LEVERAGED_ETF', '레버리지 ETF (2배 롱 파생 — 투자 유니버스 밖, RC 0)')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='universe_excluded',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
