# Generated by Django 5.2.14 on 2026-09-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_flag_leveraged_etfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystGradeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('date', models.DateField(db_index=True, help_text='등급 변경 발표일 (원천 YYYY-MM-DD, 시각 없음)')),
                ('grading_company', models.CharField(help_text='평가 기관 (실측 최장 26자)', max_length=128)),
                ('previous_grade', models.CharField(blank=True, default='', max_length=32)),
                ('new_grade', models.CharField(blank=True, default='', max_length=32)),
                ('action', models.CharField(blank=True, default='', help_text='maintain / upgrade / downgrade', max_length=16)),
                ('source_row_count', models.IntegerField(default=1)),
                ('source', models.CharField(default='fmp', max_length=16)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'stocks_analyst_grade_change',
                'ordering': ['symbol', '-date'],
                'indexes': [models.Index(fields=['symbol', '-date'], name='stocks_anal_symbol_0737b9_idx')],
                'unique_together': {('symbol', 'date', 'grading_company', 'previous_grade', 'new_grade', 'action')},
            },
        ),
    ]
