/**
 * Chain Sight 마인드맵 카테고리 한글 매핑 (R1 Phase C-3)
 *
 * - sector: 13개 정적 표(검수 완료) + "미분류". 매핑 없는 값은 영문 원문 fallback(빈 값 금지).
 * - industry: ~130개 규모 — 자동 번역 금지. 골격(빈 dict)만 두고 사용자 검수 후 채운다.
 *   (화면엔 industry 영문 원문 그대로 표시. 정렬/그룹핑 키는 항상 영문 원본 유지 — 표시만 한글.)
 */

export const SECTOR_LABELS: Record<string, string> = {
  'Basic Materials': '기초소재',
  'Communication Services': '통신서비스',
  'Consumer Cyclical': '경기소비재',
  'Consumer Defensive': '필수소비재',
  'E-Commerce': '이커머스',
  ETF: 'ETF',
  Energy: '에너지',
  'Financial Services': '금융',
  Healthcare: '헬스케어',
  Industrials: '산업재',
  'Real Estate': '부동산',
  Technology: '기술',
  Utilities: '유틸리티',
  미분류: '미분류',
};

/**
 * industry 한글 매핑 — 사용자 승인 최종본 137건(부록 A, 2026-08-27 확정).
 * 표시만 한글, 정렬/그룹핑 키·API 파라미터는 항상 영문 원본 유지.
 * 대문자 변형 5건(AUTO MANUFACTURERS·CAPITAL MARKETS·CONSUMER ELECTRONICS·
 * SEMICONDUCTORS·UTILITIES - INDEPENDENT POWER PRODUCERS)도 포함 = 데이터
 * 정규화(CS-INDUSTRY-NORMALIZE 5행 UPDATE) 착지 전까지의 fallback 안전망.
 * 미매핑(신규 유입) 값은 getLabelForIndustry()가 영문 원문 fallback.
 */
export const INDUSTRY_LABELS: Record<string, string> = {
  'AUTO MANUFACTURERS': '자동차 제조',
  'Advertising Agencies': '광고 대행',
  'Aerospace & Defense': '항공우주·방위',
  'Agricultural - Machinery': '농기계',
  'Agricultural Farm Products': '농축산물',
  'Agricultural Inputs': '농업 자재',
  'Airlines, Airports & Air Services': '항공·공항 서비스',
  'Apparel - Footwear & Accessories': '신발·잡화',
  'Apparel - Manufacturers': '의류 제조',
  'Apparel - Retail': '의류 소매',
  'Asset Management': '자산운용',
  'Asset Management - Global': '자산운용 - 글로벌',
  'Asset Management - Leveraged': '자산운용 - 레버리지',
  'Auto - Dealerships': '자동차 딜러',
  'Auto - Manufacturers': '자동차 제조',
  'Auto - Parts': '자동차 부품',
  'Auto - Recreational Vehicles': '레저차량(RV)',
  'Banks - Diversified': '은행 - 대형종합',
  'Banks - Regional': '은행 - 지역',
  'Beverages - Alcoholic': '주류',
  'Beverages - Non-Alcoholic': '음료',
  'Beverages - Wineries & Distilleries': '와인·증류주',
  Biotechnology: '바이오',
  'Business Equipment & Supplies': '사무기기·용품',
  'CAPITAL MARKETS': '자본시장',
  'CONSUMER ELECTRONICS': '가전',
  Chemicals: '화학',
  'Chemicals - Specialty': '특수화학',
  'Communication Equipment': '통신장비',
  'Computer Hardware': '컴퓨터 하드웨어',
  Conglomerates: '복합기업',
  Construction: '건설',
  'Construction Materials': '건축자재',
  'Consulting Services': '컨설팅',
  'Consumer Electronics': '가전',
  Copper: '구리',
  'Discount Stores': '할인점',
  'Diversified Utilities': '종합 유틸리티',
  'Drug Manufacturers - General': '제약 - 대형',
  'Drug Manufacturers - Specialty & Generic': '제약 - 스페셜티·제네릭',
  'E-Commerce': '이커머스',
  'Electrical Equipment & Parts': '전기장비·부품',
  'Electronic Components': '전자부품',
  'Electronic Gaming & Multimedia': '게임·멀티미디어',
  'Engineering & Construction': '엔지니어링·건설',
  Entertainment: '엔터테인먼트',
  'Financial - Capital Markets': '자본시장',
  'Financial - Credit Services': '신용 서비스',
  'Financial - Data & Stock Exchanges': '금융데이터·거래소',
  'Food Confectioners': '제과',
  'Food Distribution': '식품 유통',
  'Furnishings, Fixtures & Appliances': '가구·생활가전',
  'Gambling, Resorts & Casinos': '카지노·리조트',
  'General Utilities': '일반 유틸리티',
  Gold: '금',
  'Grocery Stores': '식료품 소매',
  'Hardware, Equipment & Parts': '하드웨어·장비',
  'Home Improvement': '홈임프루브먼트',
  'Household & Personal Products': '생활용품·퍼스널케어',
  'Independent Power Producers': '민자발전(IPP)',
  'Index Fund': '인덱스펀드',
  'Industrial - Distribution': '산업재 유통',
  'Industrial - Infrastructure Operations': '인프라 운영',
  'Industrial - Machinery': '산업기계',
  'Industrial - Pollution & Treatment Controls': '환경·오염처리',
  'Industrial Materials': '산업소재',
  'Information Technology Services': 'IT 서비스',
  'Insurance - Brokers': '보험 - 브로커',
  'Insurance - Diversified': '보험 - 종합',
  'Insurance - Life': '보험 - 생명',
  'Insurance - Property & Casualty': '보험 - 손해',
  'Insurance - Reinsurance': '보험 - 재보험',
  'Insurance - Specialty': '보험 - 특종',
  'Integrated Freight & Logistics': '종합 물류',
  'Internet Content & Information': '인터넷 콘텐츠',
  'Investment - Banking & Investment Services': '투자은행(IB)',
  Leisure: '레저',
  'Luxury Goods': '명품',
  'Manufacturing - Metal Fabrication': '금속가공',
  'Manufacturing - Tools & Accessories': '공구',
  'Medical - Care Facilities': '의료시설·요양',
  'Medical - Devices': '의료기기',
  'Medical - Diagnostics & Research': '진단·연구',
  'Medical - Distribution': '의약품 유통',
  'Medical - Equipment & Services': '의료장비·서비스',
  'Medical - Healthcare Information Services': '헬스케어 IT',
  'Medical - Healthcare Plans': '건강보험',
  'Medical - Instruments & Supplies': '의료 소모품·기구',
  'Medical - Pharmaceuticals': '의약품',
  'Medical - Specialties': '의료 스페셜티',
  'Oil & Gas Equipment & Services': '유전 장비·서비스',
  'Oil & Gas Exploration & Production': '석유가스 E&P',
  'Oil & Gas Integrated': '종합 석유·가스',
  'Oil & Gas Midstream': '미드스트림',
  'Oil & Gas Refining & Marketing': '정유',
  'Packaged Foods': '가공식품',
  'Packaging & Containers': '포장·용기',
  'Paper, Lumber & Forest Products': '제지·목재',
  'Personal Products & Services': '퍼스널 서비스',
  'REIT - Diversified': '리츠 - 종합',
  'REIT - Healthcare Facilities': '리츠 - 헬스케어',
  'REIT - Hotel & Motel': '리츠 - 호텔',
  'REIT - Industrial': '리츠 - 물류·산업',
  'REIT - Office': '리츠 - 오피스',
  'REIT - Residential': '리츠 - 주거',
  'REIT - Retail': '리츠 - 리테일',
  'REIT - Specialty': '리츠 - 스페셜티',
  Railroads: '철도',
  'Real Estate - Services': '부동산 서비스',
  'Regulated Electric': '전력',
  'Regulated Gas': '가스',
  'Regulated Water': '수도',
  'Renewable Utilities': '신재생에너지',
  'Rental & Leasing Services': '렌탈·리스',
  'Residential Construction': '주택건설',
  Restaurants: '외식',
  SEMICONDUCTORS: '반도체',
  'Security & Protection Services': '보안 서비스',
  Semiconductors: '반도체',
  'Social Media': '소셜미디어',
  'Software - Application': '소프트웨어 - 애플리케이션',
  'Software - Infrastructure': '소프트웨어 - 인프라',
  'Software - Services': '소프트웨어 - 서비스',
  Solar: '태양광',
  'Specialty Business Services': '전문 비즈니스 서비스',
  'Specialty Retail': '전문 소매',
  'Staffing & Employment Services': '인력·채용',
  Steel: '철강',
  Technology: '기술(일반)',
  'Technology Distributors': 'IT 유통',
  'Telecommunications Services': '통신 서비스',
  Tobacco: '담배',
  'Travel Lodging': '호텔·숙박',
  'Travel Services': '여행 서비스',
  Trucking: '트럭운송',
  'UTILITIES - INDEPENDENT POWER PRODUCERS': '민자발전(IPP)',
  'Waste Management': '폐기물 처리',
};

/** sector 문자열 → 한글 라벨. 미매핑 시 영문 원문 fallback(빈 값 표시 금지). */
export function getLabelForSector(sector: string): string {
  return SECTOR_LABELS[sector] ?? sector;
}

/** industry 문자열 → 한글 라벨(현재 골격 단계 — 항상 영문 원문 fallback). */
export function getLabelForIndustry(industry: string): string {
  return INDUSTRY_LABELS[industry] ?? industry;
}
