# Generated by Django 5.1.7 on 2026-04-03 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stocks", "0008_industryclassification"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineIntelligenceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("hours_back", models.IntegerField(default=24)),
                ("collection_score", models.FloatField(default=0.0)),
                ("extraction_score", models.FloatField(default=0.0)),
                ("matching_score", models.FloatField(default=0.0)),
                ("sync_score", models.FloatField(default=0.0)),
                ("quality_score", models.FloatField(default=0.0)),
                (
                    "health_score",
                    models.FloatField(default=0.0, help_text="5차원 가중 평균"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="healthy",
                        max_length=10,
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("cross_insights", models.TextField(blank=True, default="")),
                ("recommended_actions", models.JSONField(blank=True, default=list)),
                ("trend_vs_previous", models.JSONField(blank=True, default=dict)),
                ("prompt_version", models.CharField(default="v1", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sec_pipeline_intelligence_report",
                "ordering": ["-report_date"],
                "get_latest_by": "report_date",
            },
        ),
        migrations.CreateModel(
            name="BusinessModelSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of_date", models.DateField(help_text="filing_date 기준")),
                (
                    "direct_customer_contact",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("indirect", "Indirect"),
                            ("hybrid", "Hybrid"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "contract_model",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("one_time", "One-time"),
                            ("hybrid", "Hybrid"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "recurring_revenue_signal",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "channel_dependency",
                    models.CharField(
                        choices=[
                            ("high_dependency", "High Dependency"),
                            ("moderate", "Moderate"),
                            ("low_dependency", "Low Dependency"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "customer_concentration",
                    models.CharField(
                        choices=[
                            ("concentrated", "Concentrated"),
                            ("diversified", "Diversified"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("overall_confidence", models.FloatField(default=0.0)),
                (
                    "confidence_grade",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("prompt_version", models.CharField(default="v1", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        db_column="symbol_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_model_snapshots",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "sec_business_model_snapshot",
                "ordering": ["-as_of_date"],
                "get_latest_by": "as_of_date",
            },
        ),
        migrations.CreateModel(
            name="BusinessModelEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("direct_customer_contact", "Direct Customer Contact"),
                            ("contract_model", "Contract Model"),
                            ("recurring_revenue_signal", "Recurring Revenue Signal"),
                            ("channel_dependency", "Channel Dependency"),
                            ("customer_concentration", "Customer Concentration"),
                        ],
                        max_length=30,
                    ),
                ),
                ("evidence_text", models.TextField()),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="sec_pipeline.businessmodelsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "sec_business_model_evidence",
            },
        ),
        migrations.CreateModel(
            name="CompanyAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=200)),
                ("ticker", models.CharField(max_length=20)),
                (
                    "context_sector",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "context_country",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="참고용 메타데이터 (unique key에 포함하지 않음)",
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin_resolved", "Admin Resolved"),
                            ("auto_90pct", "Auto 90%+"),
                            ("manual_seed", "Manual Seed"),
                        ],
                        default="manual_seed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Company aliases",
                "db_table": "sec_company_alias",
                "unique_together": {("alias", "context_sector")},
            },
        ),
        migrations.CreateModel(
            name="FilingProcessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("fmp_metadata", "FMP Metadata"),
                            ("sec_fetch", "SEC Fetch"),
                            ("section_extract", "Section Extract"),
                            ("track_a_extract", "Track A Extract"),
                            ("track_b_extract", "Track B Extract"),
                            ("ticker_match", "Ticker Match"),
                            ("neo4j_sync", "Neo4j Sync"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=10,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sec_filing_process_log",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "stage", "-started_at"],
                        name="sec_filing__symbol_02ba92_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RawDocumentStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accession_no", models.CharField(max_length=30, unique=True)),
                ("filing_date", models.DateField()),
                ("fiscal_year", models.IntegerField()),
                ("final_link", models.URLField(max_length=500)),
                ("item_1_text", models.TextField(blank=True, default="")),
                ("item_1a_text", models.TextField(blank=True, default="")),
                ("item_7_text", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=10,
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        default="regex",
                        help_text="regex / edgartools_fallback",
                        max_length=20,
                    ),
                ),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        db_column="symbol_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sec_filings",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "sec_raw_document_store",
                "ordering": ["-filing_date"],
            },
        ),
        migrations.AddField(
            model_name="businessmodelsnapshot",
            name="source_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_model_snapshots",
                to="sec_pipeline.rawdocumentstore",
            ),
        ),
        migrations.CreateModel(
            name="SupplyChainEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_company_name", models.CharField(max_length=200)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("SUPPLIES_TO", "Supplies To"),
                            ("CUSTOMER_OF", "Customer Of"),
                            ("PARTNER_WITH", "Partner With"),
                            ("DEPENDS_ON", "Depends On"),
                            ("COMPETES_WITH", "Competes With"),
                        ],
                        max_length=20,
                    ),
                ),
                ("evidence_text", models.TextField()),
                ("system_confidence", models.FloatField(default=0.0)),
                (
                    "confidence_grade",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("neo4j_dirty", models.BooleanField(default=True)),
                ("neo4j_synced_at", models.DateTimeField(blank=True, null=True)),
                ("prompt_version", models.CharField(default="v1", max_length=10)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_company",
                    models.ForeignKey(
                        db_column="source_symbol_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sec_supply_chain_as_source",
                        to="stocks.stock",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_chain_evidences",
                        to="sec_pipeline.rawdocumentstore",
                    ),
                ),
                (
                    "target_company",
                    models.ForeignKey(
                        blank=True,
                        db_column="target_symbol_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sec_supply_chain_as_target",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "sec_supply_chain_evidence",
            },
        ),
        migrations.CreateModel(
            name="UnmatchedCompanyQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_company_name", models.CharField(max_length=200)),
                ("source_symbol", models.CharField(max_length=20)),
                ("occurrence_count", models.IntegerField(default=1)),
                (
                    "source_sectors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="이 이름이 나온 sector 목록 (2개+면 동명이의 경고)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("matched", "Matched"),
                            ("not_public", "Not Public"),
                            ("person", "Person"),
                            ("duplicate", "Duplicate"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "fuzzy_candidates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"ticker":"TSM","name":"...","score":0.82}, ...]',
                    ),
                ),
                (
                    "resolved_ticker",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sec_unmatched_company_queue",
                "ordering": ["-occurrence_count"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="sec_unmatch_status_9fefc3_idx"
                    ),
                    models.Index(
                        fields=["raw_company_name"],
                        name="sec_unmatch_raw_com_1078d7_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="rawdocumentstore",
            index=models.Index(
                fields=["symbol", "-filing_date"], name="sec_raw_doc_symbol__20917b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessmodelsnapshot",
            index=models.Index(
                fields=["symbol", "-as_of_date"], name="sec_busines_symbol__d64aa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplychainevidence",
            index=models.Index(
                fields=["source_company", "relationship_type"],
                name="sec_supply__source__292866_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplychainevidence",
            index=models.Index(
                fields=["target_company"], name="sec_supply__target__30f08e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplychainevidence",
            index=models.Index(
                fields=["neo4j_dirty"], name="sec_supply__neo4j_d_db5c43_idx"
            ),
        ),
    ]
