# Generated by Django 5.1.7 on 2026-03-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('metric_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('display_name_en', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('profitability', 'Profitability'), ('growth', 'Growth'), ('financial_structure', 'Financial Structure'), ('cash_flow_quality', 'Cash Flow Quality'), ('operational_efficiency', 'Operational Efficiency'), ('dilution_shareholder', 'Dilution & Shareholder'), ('valuation', 'Valuation')], max_length=30)),
                ('unit', models.CharField(choices=[('ratio', 'Ratio'), ('days', 'Days'), ('pct', 'Percentage'), ('years', 'Years'), ('flag', 'Boolean Flag')], max_length=20)),
                ('higher_is_better', models.BooleanField()),
                ('is_core_mvp', models.BooleanField(default=True)),
                ('is_benchmarkable', models.BooleanField(default=True)),
                ('formula_description', models.TextField(blank=True)),
                ('source_apis', models.JSONField(default=list)),
                ('source_fields', models.JSONField(default=list)),
                ('fallback_formula', models.TextField(blank=True)),
                ('green_threshold', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('red_threshold', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('threshold_direction', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], default='above', max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('formula_version', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'metrics_metric_definition',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BatchJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(db_index=True, max_length=100)),
                ('job_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('retry', 'Retry')], default='scheduled', max_length=50)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial_failure', 'Partial Failure'), ('failed', 'Failed')], max_length=20)),
                ('total_symbols', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('skip_count', models.IntegerField(default=0)),
                ('failure_details', models.JSONField(default=list)),
                ('pipeline_step', models.CharField(blank=True, max_length=50)),
                ('depends_on_job_id', models.BigIntegerField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='celery_beat', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metrics_batch_job_run',
                'indexes': [models.Index(fields=['job_name', '-started_at'], name='metrics_bat_job_nam_db248d_idx'), models.Index(fields=['status'], name='metrics_bat_status_962f6f_idx')],
            },
        ),
    ]
