# Generated by Django 5.1.7 on 2026-03-26 09:03

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_peerlistcache_companymetricsnapshot'),
        ('stocks', '0006_stockoverviewko'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryMetricBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(db_index=True, max_length=100)),
                ('fiscal_year', models.IntegerField()),
                ('p25_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('median_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('p75_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('mean_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('sample_count', models.IntegerField(default=0)),
                ('benchmark_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', help_text='high: sample>=10, medium: 5-9, low: <5 → sector fallback', max_length=10)),
                ('is_sector_fallback', models.BooleanField(default=False)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('metric_code', models.ForeignKey(db_column='metric_code', on_delete=django.db.models.deletion.CASCADE, to='metrics.metricdefinition')),
            ],
            options={
                'db_table': 'metrics_industry_metric_benchmark',
                'indexes': [models.Index(fields=['industry', 'fiscal_year'], name='metrics_ind_industr_46fbd2_idx')],
                'unique_together': {('industry', 'fiscal_year', 'metric_code')},
            },
        ),
        migrations.CreateModel(
            name='PeerMetricBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('p25_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('median_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('p75_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('peer_count', models.IntegerField(default=0)),
                ('peer_symbols_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None)),
                ('benchmark_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', help_text='high: peer>=8, medium: 3-7, low: <3', max_length=10)),
                ('use_minmax', models.BooleanField(default=False)),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('metric_code', models.ForeignKey(db_column='metric_code', on_delete=django.db.models.deletion.CASCADE, to='metrics.metricdefinition')),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'db_table': 'metrics_peer_metric_benchmark',
                'indexes': [models.Index(fields=['symbol', 'fiscal_year'], name='metrics_pee_symbol_ef805e_idx')],
                'unique_together': {('symbol', 'fiscal_year', 'metric_code')},
            },
        ),
    ]
