# Generated by Django 5.1.7 on 2026-03-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_industrymetricbenchmark_peermetricbenchmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymetricsnapshot',
            name='exclusion_reason',
            field=models.CharField(blank=True, default='', help_text="not_applicable/unstable일 때 사유. e.g. '흑자 기업', '값 변동 과대'", max_length=100),
        ),
        migrations.AddField(
            model_name='companymetricsnapshot',
            name='value_status',
            field=models.CharField(choices=[('normal', '정상'), ('missing', '데이터 누락'), ('not_applicable', '해당 없음'), ('unstable', '값 불안정'), ('low_confidence', '신뢰도 낮음')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='peerlistcache',
            name='benchmark_basis',
            field=models.CharField(choices=[('industry_size', '업종+규모'), ('industry', '업종 전체'), ('sector', '섹터 전체')], default='industry_size', max_length=20),
        ),
        migrations.AddField(
            model_name='peerlistcache',
            name='peer_tier',
            field=models.CharField(blank=True, default='', help_text='Phase 2: Chain Sight 연계 시 strict/broad/industry. Phase 1에서는 빈 문자열.', max_length=20),
        ),
        migrations.AddField(
            model_name='peerlistcache',
            name='size_bucket',
            field=models.CharField(blank=True, choices=[('mega', 'Mega'), ('large', 'Large'), ('mid', 'Mid'), ('small', 'Small')], default='', max_length=10),
        ),
    ]
