# Generated by Django 5.1.7 on 2026-03-27 00:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chainsight", "0002_companyinsidersignal_companynarrativetag_and_more"),
        ("stocks", "0007_sp500constituent_industry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyChainProfile",
            fields=[
                (
                    "symbol",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="chain_profile",
                        serialize=False,
                        to="stocks.stock",
                    ),
                ),
                ("rate_sensitivity", models.CharField(blank=True, max_length=10)),
                ("forex_sensitivity", models.CharField(blank=True, max_length=10)),
                ("commodity_sensitivity", models.CharField(blank=True, max_length=10)),
                ("regulation_type", models.CharField(blank=True, max_length=50)),
                (
                    "beta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                ("growth_stage", models.CharField(blank=True, max_length=30)),
                (
                    "revenue_cagr_3y",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("capital_type", models.CharField(blank=True, max_length=30)),
                ("net_cash_position", models.BigIntegerField(blank=True, null=True)),
                ("smart_money_signal", models.CharField(blank=True, max_length=20)),
                ("top_segment", models.CharField(blank=True, max_length=100)),
                (
                    "top_segment_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "china_revenue_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "customer_concentration_risk",
                    models.CharField(blank=True, max_length=10),
                ),
                ("business_model_type", models.CharField(blank=True, max_length=20)),
                ("primary_narrative", models.CharField(blank=True, max_length=100)),
                (
                    "theme_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("narrative_sentiment", models.CharField(blank=True, max_length=10)),
                (
                    "score_profitability",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "score_growth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "score_financial_structure",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("overall_grade", models.CharField(blank=True, max_length=5)),
                (
                    "profile_completeness",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="0.0~1.0 채워진 필드 비율",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "chainsight_chain_profile",
            },
        ),
        migrations.CreateModel(
            name="CompanyRevenueStructure",
            fields=[
                (
                    "symbol",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="revenue_structure",
                        serialize=False,
                        to="stocks.stock",
                    ),
                ),
                (
                    "segments",
                    models.JSONField(
                        default=list,
                        help_text='[{"name":"iPhone","revenue_pct":52,"trend":"stable"}, ...]',
                    ),
                ),
                (
                    "geographic_revenue",
                    models.JSONField(
                        default=list, help_text='[{"region":"Americas","pct":42}, ...]'
                    ),
                ),
                (
                    "major_customers",
                    models.JSONField(
                        default=list,
                        help_text='[{"customer":"Apple","revenue_pct":22}, ...]',
                    ),
                ),
                (
                    "customer_concentration_risk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "business_model_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("b2b", "B2B"),
                            ("b2c", "B2C"),
                            ("mixed", "Mixed"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "commodity_exposures",
                    models.JSONField(
                        default=list,
                        help_text='[{"commodity":"lithium","exposure":"high","context":"battery"}, ...]',
                    ),
                ),
                ("source_filing", models.CharField(blank=True, max_length=100)),
                (
                    "extraction_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fmp_api", "FMP API"),
                            ("10k_llm", "10-K LLM Parsing"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="0.0 ~ 1.0",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("last_parsed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "chainsight_revenue_structure",
            },
        ),
        migrations.CreateModel(
            name="ChainNewsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("marketaux", "MarketAux"),
                            ("finnhub", "Finnhub"),
                            ("eodhd", "EODHD"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.CharField(max_length=255)),
                ("title", models.TextField()),
                ("summary", models.TextField(blank=True)),
                ("url", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(db_index=True)),
                (
                    "sentiment_score",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=10,
                    ),
                ),
                ("event_type", models.CharField(blank=True, max_length=50)),
                (
                    "event_importance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "co_mentioned_symbols",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        default=list,
                        help_text="이 기사에서 함께 언급된 다른 종목들",
                        size=None,
                    ),
                ),
                ("is_duplicate", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="chainsight.chainnewsevent",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        db_column="symbol",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chain_news_events",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "db_table": "chainsight_news_event",
                "indexes": [
                    models.Index(
                        fields=["symbol", "-published_at"],
                        name="chainsight__symbol_1898fb_idx",
                    ),
                    models.Index(
                        fields=["symbol", "event_type"],
                        name="chainsight__symbol_bd2b04_idx",
                    ),
                    models.Index(
                        fields=["-published_at"], name="chainsight__publish_1e61e5_idx"
                    ),
                ],
                "unique_together": {("source", "source_id")},
            },
        ),
    ]
