# Generated by Django 5.1.7 on 2026-04-18 12:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chainsight", "0005_add_neo4j_dirty_previous_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "path_nodes",
                    models.JSONField(
                        help_text='ticker 배열. 예: ["NVDA", "TSM", "ASML"]'
                    ),
                ),
                (
                    "summary_path",
                    models.JSONField(
                        blank=True, help_text="landmark ticker 배열", null=True
                    ),
                ),
                (
                    "path_signature",
                    models.CharField(
                        blank=True,
                        help_text='경로 성격 태그: "공급망 중심 · 반도체 장비"',
                        max_length=80,
                        null=True,
                    ),
                ),
                (
                    "edge_snapshot",
                    models.JSONField(
                        blank=True, help_text="저장 시점 관계 스냅샷", null=True
                    ),
                ),
                ("why_now_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "source_center",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("source_slot", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("watching", "Watching"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="watching",
                        max_length=20,
                    ),
                ),
                (
                    "recheck_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Recheck 횟수. 2회 이상 + 24h → watching→active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_paths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chainsight_saved_path",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PathAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("watch", "Watch"),
                            ("expand", "Expand"),
                            ("alternatives", "Alternatives"),
                            ("recheck", "Recheck"),
                            ("archive", "Archive"),
                            ("resolve", "Resolve"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "saved_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="chainsight.savedpath",
                    ),
                ),
            ],
            options={
                "db_table": "chainsight_path_action",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="savedpath",
            index=models.Index(
                fields=["user", "-updated_at"], name="chainsight__user_id_dbcb07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedpath",
            index=models.Index(
                fields=["status", "-updated_at"], name="chainsight__status_87107d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pathaction",
            index=models.Index(
                fields=["saved_path", "-created_at"],
                name="chainsight__saved_p_463601_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pathaction",
            index=models.Index(
                fields=["action_type", "-created_at"],
                name="chainsight__action__ab0b37_idx",
            ),
        ),
    ]
