# Generated by Django 5.2.14 on 2026-06-15 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0008_unify_neo4j_flags'),
        ('stocks', '0008_industryclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAttentionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('score', models.FloatField()),
                ('volume_z', models.FloatField()),
                ('volatility_pct', models.FloatField()),
                ('return_pct', models.FloatField()),
                ('raw_return', models.FloatField()),
                ('is_low_liquidity', models.BooleanField(default=False, help_text='ADV < ADV_FLOOR 시 True. 점수는 정상 계산·저장(제외 아님).')),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='attention_scores', to='stocks.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['date', '-score'], name='chainsight__date_cb4847_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
