# Generated by Django 5.2.14 on 2026-06-16 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0009_attention_score'),
        ('stocks', '0008_industryclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLeadershipScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(db_index=True, max_length=128)),
                ('window', models.IntegerField(help_text='회귀/추세 윈도우 길이 (20 또는 120).')),
                ('as_of_date', models.DateField(db_index=True)),
                ('trend_quality', models.FloatField(blank=True, help_text='T2: (slope×252)×R². 테마무관, 윈도우별.', null=True)),
                ('theme_alpha', models.FloatField(blank=True, help_text='T3: α×252. 테마 멤버<3 시 NULL.', null=True)),
                ('theme_beta', models.FloatField(blank=True, help_text='T3: β (r_i~α+β·r_theme_LOO). 테마 멤버<3 시 NULL.', null=True)),
                ('up_capture', models.FloatField(blank=True, help_text='② theme>0 일 Σr_i/Σr_theme×100. 분모 0 시 NULL.', null=True)),
                ('down_capture', models.FloatField(blank=True, help_text='② theme<0 일 Σr_i/Σr_theme×100. 분모 0 시 NULL.', null=True)),
                ('capture_spread', models.FloatField(blank=True, help_text='② up_capture − down_capture. 둘 중 하나라도 NULL이면 NULL.', null=True)),
                ('obs_count', models.IntegerField(default=0, help_text='윈도우 내 유효 관측(수익률)일 수.')),
                ('is_fallback', models.BooleanField(default=False, help_text='120일 미달로 20 윈도우만 산출된 종목 표시(IPO/상폐/프리미엄).')),
                ('stock', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='leadership_scores', to='stocks.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['as_of_date', 'theme', 'window'], name='chainsight__as_of_d_fccbfc_idx'), models.Index(fields=['as_of_date', 'window', '-trend_quality'], name='chainsight__as_of_d_3c1514_idx')],
                'unique_together': {('stock', 'theme', 'window', 'as_of_date')},
            },
        ),
    ]
