# Generated by Django 5.2.14 on 2026-06-25 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0010_stockleadershipscore'),
        ('stocks', '0008_industryclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('source', models.CharField(choices=[('news_jaccard', 'News Co-mention (Jaccard)'), ('llm', 'LLM'), ('manual', 'Manual')], default='news_jaccard', max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='코어 멤버 평균 강도')),
                ('window_days', models.IntegerField(default=21, help_text='co-mention half-life 윈도우(일)')),
                ('cohesion', models.FloatField(blank=True, help_text='멤버 수익률 pairwise 상관 평균', null=True)),
                ('breadth', models.FloatField(blank=True, help_text='일별 방향 일치도', null=True)),
                ('member_count', models.IntegerField(default=0)),
                ('core_count', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(db_index=True, default=False, help_text='킬스위치/노이즈 게이팅(소표본·저신뢰)')),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chainsight_event_group',
                'indexes': [models.Index(fields=['source', 'is_hidden'], name='chainsight__source_ee38a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('core', 'Core'), ('satellite', 'Satellite')], default='core', max_length=10)),
                ('edge_confidence', models.FloatField(default=0.0, help_text='다중신호 confidence(jaccard 1-hop + 13F 가산 + 코어 연결수)')),
                ('anchor_symbol', models.CharField(blank=True, help_text='위성이 닿은 코어 멤버(코어는 공백)', max_length=10)),
                ('cohold_institutions', models.IntegerField(default=0, help_text='13F 공유 기관 수(✓N, 가산 신호)')),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chainsight.eventgroup')),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='event_group_memberships', to='stocks.stock')),
            ],
            options={
                'db_table': 'chainsight_group_membership',
                'indexes': [models.Index(fields=['symbol', 'role'], name='chainsight__symbol_4454ea_idx')],
                'unique_together': {('group', 'symbol')},
            },
        ),
    ]
