# Generated by Django 5.2.14 on 2026-06-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0011_eventgroup_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='name_candidates',
            field=models.JSONField(blank=True, default=dict, help_text='코어 TF-IDF 이름 후보 {"n2":..,"n3":..,"terms":[..]} (N 미확정 — Phase 1)'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='cohesion',
            field=models.FloatField(blank=True, help_text='코어 멤버 수익률 pairwise 상관 평균(게이팅 기준)', null=True),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='킬스위치/노이즈 게이팅(코어 cohesion<0.2 또는 산출불가 = 저신뢰 잡탕 후보)'),
        ),
    ]
