# Generated by Django 5.2.14 on 2026-06-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0013_stockleadershipscore_benchmark_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationPairSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_a', models.CharField(db_index=True, max_length=16)),
                ('canonical_b', models.CharField(db_index=True, max_length=16)),
                ('period', models.DateField()),
                ('truth_max', models.FloatField()),
                ('market_max', models.FloatField()),
                ('relevance_opp', models.FloatField()),
                ('relevance_risk', models.FloatField()),
                ('truth_edge_count', models.IntegerField(default=0)),
                ('market_edge_count', models.IntegerField(default=0)),
                ('last_observed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chainsight_relation_pair_snapshot',
                'indexes': [models.Index(fields=['canonical_a', 'canonical_b', '-period'], name='chainsight__canonic_ec1295_idx'), models.Index(fields=['-relevance_opp', '-period'], name='chainsight__relevan_c0f383_idx'), models.Index(fields=['-relevance_risk', '-period'], name='chainsight__relevan_0490b3_idx')],
                'unique_together': {('canonical_a', 'canonical_b', 'period')},
            },
        ),
    ]
