# Generated by Django 5.2.14 on 2026-07-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0014_relationpairsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationconfidence',
            name='evidence_streak',
            field=models.IntegerField(default=0, help_text='연속 재확인 틱 수. 하향/무증거 시 0 리셋. B의 streak≥N 판정.'),
        ),
        migrations.AddField(
            model_name='relationconfidence',
            name='fastpath_triggered_at',
            field=models.DateTimeField(blank=True, help_text='C fast-path 발동 감사(오상향 추적).', null=True),
        ),
        migrations.AddField(
            model_name='relationconfidence',
            name='last_computed_at',
            field=models.DateTimeField(blank=True, help_text='궤적 점 계산 시각(기존 드리프트 해소, upsert 감사용).', null=True),
        ),
        migrations.AddField(
            model_name='relationconfidence',
            name='last_downgraded_at',
            field=models.DateTimeField(blank=True, help_text='하향 전이 witness.', null=True),
        ),
        migrations.AddField(
            model_name='relationconfidence',
            name='last_upgraded_at',
            field=models.DateTimeField(blank=True, help_text='상향 전이 witness.', null=True),
        ),
    ]
