# Generated by Django 5.2.14 on 2026-07-06 06:28
#
# TH-1 독립 마이그레이션 (설계서 theme_heat_design.md v1.2 §6.0~§6.6).
# 스키마(CreateModel × 7) + 시드(RunPython) 단일 파일 (프롬프트 §4).

import django.db.models.deletion
from django.db import migrations, models

# GICS 11 섹터 정본 = services/serverless/services/sector_heatmap_service.py SECTORS 키.
# HeatEntity kind=sector 시드의 ref_id (잠금장치 2: kind=theme 행 생성 금지).
GICS_SECTORS = [
    "Technology",
    "Healthcare",
    "Financial Services",
    "Consumer Cyclical",
    "Industrials",
    "Energy",
    "Communication Services",
    "Real Estate",
    "Utilities",
    "Basic Materials",
    "Consumer Defensive",
]

# ThemeEtfMap 초기 시드 (설계서 §6.4 v1.2.1) — ⚠️ 검수 미완 (§12-2).
#
# 설계서 §6.4 예시는 반도체/방산 등 테마 단위를 전제하나, Cycle 1 은 sector 엔티티만
# 존재한다(§6.0 잠금장치 2). 결정(v1.2.1): Cycle 1 C5 주 데이터 = 섹터 SPDR 11종(C5 구현
# PR 에서 시드, TASKQUEUE TH-C5-SPDR-SEED), 아래 테마 ETF 9행은 **active=False(레인 개방
# 대기)로 보존** — 테마 레인 개방 후 orig_theme 으로 원 테마 단위 복원.
#
# orig_theme = 복원 키(모델 필드 미추가 = §6.0/§6.4 스펙 잠금 준수, 이 committed 상수가
# 복원의 durable 근거). (sector_key, orig_theme, etf_symbol, role, leverage_factor)
THEME_ETF_SEED = [
    ("Technology", "반도체", "SOXX", "primary", 1),
    ("Technology", "반도체", "SMH", "primary", 1),
    ("Technology", "반도체", "SOXL", "leveraged", 3),
    ("Technology", "기술", "QQQ", "primary", 1),
    ("Technology", "기술", "TQQQ", "leveraged", 3),
    ("Industrials", "방산", "ITA", "primary", 1),
    ("Energy", "에너지", "XLE", "primary", 1),
    ("Energy", "에너지", "ERX", "leveraged", 2),
    ("Healthcare", "헬스케어", "XLV", "primary", 1),
]


def seed_heat_entities_and_etf_map(apps, schema_editor):
    """kind=sector 11행 + ThemeEtfMap §6.4 초기 시드 (멱등). kind=theme 행 미생성."""
    HeatEntity = apps.get_model("chainsight", "HeatEntity")
    ThemeEtfMap = apps.get_model("chainsight", "ThemeEtfMap")

    entity_by_ref = {}
    for ref_id in GICS_SECTORS:
        entity, _ = HeatEntity.objects.get_or_create(
            kind="sector",
            ref_id=ref_id,
            defaults={"constituent_policy": "static"},
        )
        entity_by_ref[ref_id] = entity

    # 테마 ETF 9행은 active=False (레인 개방 대기 — 설계서 §6.4 v1.2.1). orig_theme 은
    # 위 상수(committed)가 복원 근거이므로 DB 컬럼 미추가.
    for sector_key, _orig_theme, etf_symbol, role, leverage_factor in THEME_ETF_SEED:
        ThemeEtfMap.objects.get_or_create(
            theme=entity_by_ref[sector_key],
            etf_symbol=etf_symbol,
            role=role,
            defaults={"leverage_factor": leverage_factor, "active": False},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0015_relationconfidence_evidence_streak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('snapshot_date', models.DateField(db_index=True, help_text='주간(금요일). diff 의 시간축.')),
                ('fiscal_year', models.SmallIntegerField(help_text='당기·차기 연도별 행.')),
                ('eps_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('eps_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('eps_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('num_analysts_eps', models.IntegerField(blank=True, help_text='C8 신뢰 가중.', null=True)),
                ('revenue_avg', models.DecimalField(blank=True, decimal_places=2, help_text='보조.', max_digits=22, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol', '-snapshot_date', 'fiscal_year'],
                'unique_together': {('symbol', 'snapshot_date', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='HeatEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sector', 'sector'), ('theme', 'theme')], help_text='sector | theme — Cycle 1 은 sector 11행만 시드.', max_length=16)),
                ('ref_id', models.CharField(help_text='sector: GICS 섹터 키 / theme: (미래) 테마 노드 식별자.', max_length=64)),
                ('constituent_policy', models.CharField(help_text='sector: static / theme: (미래) monthly_frozen.', max_length=16)),
            ],
            options={
                'indexes': [models.Index(fields=['kind'], name='heat_entity_kind_idx')],
                'unique_together': {('kind', 'ref_id')},
            },
        ),
        migrations.CreateModel(
            name='InsiderTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('reporting_cik', models.CharField(blank=True, max_length=16)),
                ('company_cik', models.CharField(blank=True, max_length=16)),
                ('filing_date', models.DateField(db_index=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('transaction_type', models.CharField(blank=True, help_text='S-Sale, P-Purchase, A-Award, M-Exempt, F-InKind, G-Gift, 공란 — 전건 보존.', max_length=32)),
                ('securities_transacted', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('type_of_owner', models.CharField(blank=True, max_length=64)),
                ('direct_or_indirect', models.CharField(blank=True, max_length=8)),
                ('acq_or_disp', models.CharField(blank=True, max_length=8)),
                ('sec_url', models.TextField(blank=True, help_text='SEC 원문 — 교차검증 훅(§8)·감사 추적용.')),
                ('raw', models.JSONField(default=dict, help_text='FMP 응답 원본.')),
                ('dedup_key', models.CharField(help_text='hash(symbol, reporting_cik, transaction_date, transaction_type, securities_transacted, price).', max_length=64, unique=True)),
            ],
            options={
                'ordering': ['-filing_date'],
                'indexes': [models.Index(fields=['symbol', '-filing_date'], name='insider_sym_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThemeFilingCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=16)),
                ('filing_date', models.DateField(db_index=True)),
                ('form_type', models.CharField(help_text='424B5 또는 IPO 이벤트 마커.', max_length=16)),
                ('exchange', models.CharField(blank=True, help_text='IPO 레코드용 — NYSE/NASDAQ 필터 (§5.2-3).', max_length=16)),
                ('source', models.CharField(default='fmp', help_text='fmp 고정 (EDGAR 폴백 불요 확정, 필드는 이음새로 유지).', max_length=8)),
                ('dedup_key', models.CharField(help_text='hash(symbol, cik, accession) — accession 은 link 에서 추출.', max_length=64, unique=True)),
            ],
            options={
                'ordering': ['-filing_date'],
                'indexes': [models.Index(fields=['form_type', '-filing_date'], name='filing_type_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThemeDemandScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='주간(금요일 기준일).')),
                ('score', models.SmallIntegerField(blank=True, help_text='not_computed 시 NULL.', null=True)),
                ('status', models.CharField(choices=[('supported', 'supported'), ('neutral', 'neutral'), ('detached', 'detached'), ('not_computed', 'not_computed')], max_length=16)),
                ('components', models.JSONField(default=dict, help_text='테마별 오버라이드 구성 그대로 기록.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(db_column='theme_id', on_delete=django.db.models.deletion.PROTECT, related_name='demand_scores', to='chainsight.heatentity')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('theme', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ThemeEtfMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etf_symbol', models.CharField(max_length=16)),
                ('role', models.CharField(choices=[('primary', 'primary'), ('leveraged', 'leveraged')], max_length=16)),
                ('leverage_factor', models.SmallIntegerField(default=1, help_text='1, 2, 3.')),
                ('active', models.BooleanField(default=True, help_text='상장폐지 대응.')),
                ('theme', models.ForeignKey(db_column='theme_id', on_delete=django.db.models.deletion.PROTECT, related_name='etf_maps', to='chainsight.heatentity')),
            ],
            options={
                'ordering': ['theme', 'role'],
                'unique_together': {('theme', 'etf_symbol', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ThemeHeatScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('score', models.SmallIntegerField(help_text='0~100.')),
                ('status', models.CharField(choices=[('overheated', 'overheated'), ('warning', 'warning'), ('cool', 'cool')], max_length=16)),
                ('components', models.JSONField(default=dict, help_text='성분별 {z, s, raw, missing_reason} 8건 — C2 는 C2a/C2b 분리, C8 은 z_mode 포함.')),
                ('evidence', models.JSONField(default=dict, help_text='근거 한 줄 생성용 상위 기여 성분 2건 (§10.3).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(db_column='theme_id', help_text='§6.0 HeatEntity.', on_delete=django.db.models.deletion.PROTECT, related_name='heat_scores', to='chainsight.heatentity')),
            ],
            options={
                'ordering': ['-date', '-score'],
                'indexes': [models.Index(fields=['-date'], name='heat_score_date_desc_idx')],
                'unique_together': {('theme', 'date')},
            },
        ),
        # 역방향은 noop — 시드 행은 위 DeleteModel 이 테이블째 드롭하므로 명시적 DELETE 는
        # 불필요하고, DELETE(지연 FK 트리거)+같은 트랜잭션 DROP 은 Postgres 충돌을 유발한다.
        migrations.RunPython(
            seed_heat_entities_and_etf_map,
            migrations.RunPython.noop,
        ),
    ]
