# Generated by Django 5.2.14 on 2026-07-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0016_theme_heat_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniverseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_date', models.DateField(db_index=True, help_text='배치 실행 일자 (유니버스 동결 시점).', unique=True)),
                ('symbols', models.JSONField(default=list, help_text="그날 조회한 유니버스 심볼 배열 (SP500 active − '.' 심볼). 모집단 참조원.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-batch_date'],
            },
        ),
    ]
