# Generated by Django 5.2.14 on 2026-07-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0016_backfill_last_computed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationconfidence',
            name='relation_type',
            field=models.CharField(choices=[('PEER_OF', 'Peer'), ('SUPPLIES_TO', 'Supplies To'), ('CO_MENTIONED', 'Co-mentioned'), ('PRICE_CORRELATED', 'Price Correlated'), ('HAS_THEME', 'Has Theme'), ('COMPETES_WITH', 'Competes With'), ('HELD_BY_SAME_FUND', 'Held by Same Fund'), ('PARTNER_WITH', 'Partner With'), ('DEPENDS_ON', 'Depends On')], max_length=30),
        ),
    ]
