# Generated by Django 5.2.14 on 2026-07-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0017_alter_relationconfidence_relation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolCentrality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('as_of', models.DateField(db_index=True)),
                ('pagerank', models.FloatField()),
                ('betweenness', models.FloatField()),
                ('pagerank_rank', models.IntegerField()),
                ('betweenness_rank', models.IntegerField()),
                ('graph_nodes', models.IntegerField()),
                ('graph_edges', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chainsight_symbol_centrality',
                'indexes': [models.Index(fields=['as_of', 'pagerank_rank'], name='chainsight__as_of_077772_idx'), models.Index(fields=['as_of', 'betweenness_rank'], name='chainsight__as_of_cb3132_idx'), models.Index(fields=['symbol', '-as_of'], name='chainsight__symbol_82bc17_idx')],
                'unique_together': {('symbol', 'as_of')},
            },
        ),
    ]
