# Generated by Django 5.2.14 on 2026-07-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0018_seed_spdr_primary_etfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtfSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('snapshot_date', models.DateField(db_index=True, help_text='수집 기준일. diff 의 시간축.')),
                ('shares_outstanding', models.DecimalField(blank=True, decimal_places=2, help_text='FMP /stable/shares-float outstandingShares.', max_digits=24, null=True)),
                ('nav', models.DecimalField(blank=True, decimal_places=6, help_text='FMP /stable/etf/info nav.', max_digits=20, null=True)),
                ('aum', models.DecimalField(blank=True, decimal_places=2, help_text='FMP /stable/etf/info assetsUnderManagement (보조).', max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol', '-snapshot_date'],
                'unique_together': {('symbol', 'snapshot_date')},
            },
        ),
    ]
