# Generated by Django 5.2.14 on 2026-07-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0019_etfsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeetfmap',
            name='measured_liquidity_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='시드 시점 실측 20일 중위 거래대금(감사용, 자동 갱신 없음·보정 미적용). 결정12b.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='themeetfmap',
            name='leverage_factor',
            field=models.SmallIntegerField(default=1, help_text='배율 1, 2, 3 (= multiplier).'),
        ),
        migrations.CreateModel(
            name='EtfDailyBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('date', models.DateField(db_index=True)),
                ('close', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol', '-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
