# Generated by Django 5.2.14 on 2026-07-09 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0021_seed_spdr_leveraged_etfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('fiscal_date', models.DateField(db_index=True, help_text='분기 결산일 (EV.date == income.date).')),
                ('enterprise_value', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol', '-fiscal_date'],
                'unique_together': {('symbol', 'fiscal_date')},
            },
        ),
        migrations.CreateModel(
            name='ThemeNewsVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('mention_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(db_column='theme_id', on_delete=django.db.models.deletion.PROTECT, related_name='news_volumes', to='chainsight.heatentity')),
            ],
            options={
                'ordering': ['theme', '-date'],
                'unique_together': {('theme', 'date')},
            },
        ),
    ]
