# Generated by Django 5.2.14 on 2026-07-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0022_quarterlyvaluation_themenewsvolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeKeywordH2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_normalized', models.CharField(help_text='_normalize 형(소문자·공백정리). 조회 키.', max_length=255, unique=True)),
                ('term_original', models.CharField(help_text='LLM 입력 원문(감사).', max_length=255)),
                ('sector', models.CharField(help_text='HeatEntity.ref_id (GICS 정본).', max_length=32)),
                ('confidence', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], help_text='정규화 등급(소문자).', max_length=8)),
                ('source', models.CharField(db_index=True, default='h2_v1', help_text='박제 배치 표식(provenance). h2_v1 = TH-13 초판.', max_length=16)),
                ('reason', models.TextField(blank=True, help_text='LLM 배정 근거 1줄(감사).')),
                ('applied_at', models.DateTimeField(help_text='박제 시각(provenance).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['term_normalized'],
                'indexes': [models.Index(fields=['source'], name='h2_source_idx')],
            },
        ),
    ]
