# Generated by Django 5.2.14 on 2026-07-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0026_themekeywordh2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeTermOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_normalized', models.CharField(db_index=True, help_text='_normalize 형(소문자·공백정리). 조회 키.', max_length=255)),
                ('term_original', models.CharField(help_text='재검 입력 원문(감사).', max_length=255)),
                ('disposition', models.CharField(help_text="HeatEntity.ref_id CSV(재배정) 또는 'none'(제거).", max_length=64)),
                ('generation', models.CharField(db_index=True, default='ovr_v1', help_text='세대 태깅(롤백 단위). ovr_v1 = 결정35 초판.', max_length=16)),
                ('provenance', models.JSONField(default=dict, help_text='{cell, should_be, disposition_kind, reason}. 2×2 셀 라벨 등재.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['term_normalized'],
                'indexes': [models.Index(fields=['generation'], name='termoverride_gen_idx')],
                'constraints': [models.UniqueConstraint(fields=('term_normalized', 'generation'), name='uq_termoverride_term_gen')],
            },
        ),
    ]
