# Generated by Django 5.2.14 on 2026-07-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0027_theme_term_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationconfidence',
            name='domain_machine_check',
            field=models.JSONField(blank=True, help_text='기계검증 결과(항목별 pass/fail + type_match + LLM confidence).', null=True),
        ),
        migrations.AddField(
            model_name='relationconfidence',
            name='domain_review_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('auto', 'Auto'), ('rejected', 'Rejected')], help_text='도메인 초안 검수 상태. 게이트 판정 결과.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='relationconfidence',
            name='relation_domain',
            field=models.CharField(blank=True, help_text='승인된 도메인 태그(제품/시장). 검수 승인만 기록(Phase 2).', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='relationconfidence',
            name='relation_domain_draft',
            field=models.CharField(blank=True, help_text='LLM 초안 도메인 태그. 파이프라인이 기록, 승인 전.', max_length=80, null=True),
        ),
    ]
