# Generated by Django 5.2.14 on 2026-08-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0028_relationconfidence_domain_machine_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationconfidence',
            name='serving_layer',
            field=models.CharField(choices=[('evidence', 'Evidence'), ('context', 'Context'), ('excluded', 'Excluded'), ('pending', 'Pending')], db_index=True, default='pending', help_text='계층 분류(CS-P1A Slice2). 매핑표: SEC4종·CO_MENTIONED=evidence / PEER_OF·PRICE_CORRELATED=context / PEER(2건)=pending.', max_length=10),
        ),
    ]
