# Generated by Django 5.2.14 on 2026-08-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0029_relationconfidence_serving_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationconfidence',
            name='sync_computed_at',
            field=models.DateTimeField(blank=True, help_text='sync_strength 계산 시각(감사용).', null=True),
        ),
        migrations.AddField(
            model_name='relationconfidence',
            name='sync_strength',
            field=models.FloatField(blank=True, db_index=True, help_text='초과수익(일간수익−SPY수익) Pearson 상관. evidence 계층 강도(CS-P1B). null=미계산/관측부족.', null=True),
        ),
        migrations.AddField(
            model_name='relationconfidence',
            name='sync_window_days',
            field=models.IntegerField(blank=True, help_text='sync_strength 계산 윈도우(거래일). 관행 90.', null=True),
        ),
    ]
