# Generated by Django 5.2.14 on 2026-08-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0030_relationconfidence_sync_computed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationconfidence',
            name='relation_type',
            field=models.CharField(choices=[('PEER_OF', 'Peer'), ('SUPPLIES_TO', 'Supplies To'), ('CO_MENTIONED', 'Co-mentioned'), ('PRICE_CORRELATED', 'Price Correlated'), ('HAS_THEME', 'Has Theme'), ('COMPETES_WITH', 'Competes With'), ('HELD_BY_SAME_FUND', 'Held by Same Fund'), ('PARTNER_WITH', 'Partner With'), ('DEPENDS_ON', 'Depends On'), ('ACQUIRED', 'Acquired')], max_length=30),
        ),
    ]
