# Generated by Django 5.2.14 on 2026-08-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0031_alter_relationconfidence_relation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolDemandSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('anchor_date', models.DateField(db_index=True, help_text='이번 주 금요일 스냅샷(WoW 앵커).')),
                ('fiscal_year', models.SmallIntegerField(help_text='조인 기준 FY(차기 = anchor.year+1).')),
                ('eps_prev', models.DecimalField(blank=True, decimal_places=4, help_text='지난주 동일-FY eps_avg.', max_digits=12, null=True)),
                ('eps_curr', models.DecimalField(blank=True, decimal_places=4, help_text='이번주 eps_avg.', max_digits=12, null=True)),
                ('direction', models.SmallIntegerField(blank=True, help_text='sign(Δeps): +1 상향/−1 하향/0 불변. excluded 시 NULL.', null=True)),
                ('num_analysts_prev', models.IntegerField(blank=True, null=True)),
                ('num_analysts_curr', models.IntegerField(blank=True, null=True)),
                ('excluded', models.BooleanField(default=False, help_text='가드 제외 여부(유효분모에서 빠짐).')),
                ('exclude_reason', models.CharField(blank=True, default='', help_text='fy_mismatch/analyst_delta/missing_prev.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-anchor_date', 'symbol'],
                'indexes': [models.Index(fields=['anchor_date'], name='dss_signal_anchor_idx')],
                'unique_together': {('symbol', 'anchor_date')},
            },
        ),
    ]
