# Generated by Django 5.2.14 on 2026-08-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0033_rc_scale_normalize_v3'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comentionedge',
            constraint=models.CheckConstraint(condition=models.Q(('symbol_a', models.F('symbol_b')), _negated=True), name='cme_symbol_a_ne_symbol_b'),
        ),
        migrations.AddConstraint(
            model_name='relationconfidence',
            constraint=models.CheckConstraint(condition=models.Q(('symbol_a', models.F('symbol_b')), _negated=True), name='rc_symbol_a_ne_symbol_b'),
        ),
        migrations.AddConstraint(
            model_name='relationpairsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('canonical_a', models.F('canonical_b')), _negated=True), name='rps_canonical_a_ne_canonical_b'),
        ),
    ]
