# Generated by Django 5.2.14 on 2026-08-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0034_selfloop_db_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolStoryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('partner', models.CharField(max_length=10)),
                ('count_7d', models.IntegerField(default=0)),
                ('count_90d', models.IntegerField(default=0)),
                ('weekly_avg_90d', models.FloatField(default=0.0)),
                ('activity_ratio', models.FloatField(blank=True, null=True)),
                ('last_co_mention_date', models.DateField(blank=True, null=True)),
                ('thread_total', models.IntegerField(default=0)),
                ('materialized_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chainsight_symbol_story_activity',
                'indexes': [models.Index(fields=['symbol'], name='chainsight__symbol_8c5e1c_idx'), models.Index(fields=['-activity_ratio'], name='chainsight__activit_617d43_idx'), models.Index(fields=['symbol', '-count_7d'], name='chainsight__symbol_9145e6_idx')],
                'unique_together': {('symbol', 'partner')},
            },
        ),
    ]
