"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# .env 파일 로드
load_dotenv()

## API Keys
ALPHA_VANTAGE_API_KEY = os.getenv('ALPHA_VANTAGE_API_KEY')
EODHD_API_KEY = os.getenv('EODHD_API_KEY', '')  # EODHD Historical Data
FMP_API_KEY = os.getenv('FMP_API_KEY')
FINNHUB_API_KEY = os.getenv('FINNHUB_API_KEY', '')
MARKETAUX_API_KEY = os.getenv('MARKETAUX_API_KEY', '')
FRED_API_KEY = os.getenv('FRED_API_KEY', '')  # FRED 거시경제 데이터
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')  # Claude API for RAG
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')  # Gemini API for RAG (primary)

# ============================================================
# Stock Data Provider Configuration
# ============================================================
# Provider 선택: "alpha_vantage" 또는 "fmp"
# 각 엔드포인트별로 다른 provider를 사용할 수 있습니다.
# 환경변수로 오버라이드 가능합니다.

STOCK_PROVIDERS = {
    # Feature Flags - 환경변수로 오버라이드 가능
    'quote': os.getenv('STOCK_PROVIDER_QUOTE', 'alpha_vantage'),
    'profile': os.getenv('STOCK_PROVIDER_PROFILE', 'alpha_vantage'),
    'daily_prices': os.getenv('STOCK_PROVIDER_DAILY_PRICES', 'alpha_vantage'),
    'weekly_prices': os.getenv('STOCK_PROVIDER_WEEKLY_PRICES', 'alpha_vantage'),
    'balance_sheet': os.getenv('STOCK_PROVIDER_BALANCE_SHEET', 'alpha_vantage'),
    'income_statement': os.getenv('STOCK_PROVIDER_INCOME_STATEMENT', 'alpha_vantage'),
    'cash_flow': os.getenv('STOCK_PROVIDER_CASH_FLOW', 'alpha_vantage'),
    'search': os.getenv('STOCK_PROVIDER_SEARCH', 'alpha_vantage'),
    'sector': os.getenv('STOCK_PROVIDER_SECTOR', 'alpha_vantage'),
}

# Provider 캐시 TTL (초)
PROVIDER_CACHE_TTL = {
    'quote': 300,           # 5분 - 실시간 시세
    'profile': 86400,       # 24시간 - 회사 프로필
    'daily_prices': 3600,   # 1시간 - 일별 가격
    'weekly_prices': 3600,  # 1시간 - 주별 가격
    'balance_sheet': 604800,      # 7일 - 대차대조표
    'income_statement': 604800,   # 7일 - 손익계산서
    'cash_flow': 604800,          # 7일 - 현금흐름표
    'search': 1800,         # 30분 - 검색 결과
    'sector': 3600,         # 1시간 - 섹터 성과
}

# Rate Limiting 설정
PROVIDER_RATE_LIMITS = {
    'alpha_vantage': {
        'per_minute': 5,
        'per_day': 500,
        'request_delay': 12.0,  # 초
    },
    'fmp': {
        'per_minute': 300,     # Starter Plan
        'per_day': 10000,      # Starter Plan
        'request_delay': 0.2,  # 초
    }
}

# Fallback Provider 활성화
PROVIDER_FALLBACK_ENABLED = os.getenv('PROVIDER_FALLBACK_ENABLED', 'True').lower() == 'true'

# ============================================================
# News API Configuration
# ============================================================

# News Rate Limits
NEWS_RATE_LIMITS = {
    'finnhub': {
        'per_minute': 60,          # Finnhub API: 60 calls/min (무료 티어)
        'wait_seconds': 1,         # 요청 간 최소 대기 시간
    },
    'marketaux': {
        'per_day': 100,            # Marketaux API: 100 calls/day (무료 티어)
        'articles_per_request': 3, # 응답당 최대 기사 수 제한
        'wait_seconds': 1,         # 요청 간 최소 대기 시간
    },
}

# News Cache TTL (초)
NEWS_CACHE_TTL = {
    'stock_news': 3600,      # 1시간 - 종목별 뉴스 리스트
    'trending': 300,         # 5분 - 트렌딩 뉴스
    'sentiment': 900,        # 15분 - 감성 분석 결과
    'entity': 1800,          # 30분 - 엔티티 추출 결과
}

# News API 우선순위 (1차: Finnhub, 2차: Marketaux)
NEWS_PRIMARY_PROVIDER = os.getenv('NEWS_PRIMARY_PROVIDER', 'finnhub')
NEWS_FALLBACK_PROVIDER = os.getenv('NEWS_FALLBACK_PROVIDER', 'marketaux')

# ============================================================
# Neo4j Configuration
# ============================================================

# Neo4j 연결 설정 (로컬 개발 환경 기본값)
NEO4J_URI = os.getenv('NEO4J_URI', 'bolt://localhost:7687')
NEO4J_USERNAME = os.getenv('NEO4J_USERNAME', 'neo4j')
NEO4J_PASSWORD = os.getenv('NEO4J_PASSWORD', 'password')
NEO4J_DATABASE = os.getenv('NEO4J_DATABASE', 'neo4j')

# Neo4j 연결 풀 설정
NEO4J_CONNECTION_POOL = {
    'max_connection_lifetime': 3600,  # 1시간
    'max_connection_pool_size': 50,
    'connection_acquisition_timeout': 60,
}

# Neo4j Aura (클라우드) 사용 여부
NEO4J_USE_AURA = os.getenv('NEO4J_USE_AURA', 'False').lower() == 'true'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hvwb-ms8%a@fh7_pf@obr@edq6(h41bj+$yetj#h!wg7#(b(&8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

CUSTOM_APPS = [
    "stocks.apps.StocksConfig",
    "users.apps.UsersConfig",
]

INSTALLED_APPS = [
    'daphne',  # Channels ASGI 서버 (맨 위에 위치)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stocks',
    'users',
    'analysis',
    'news',
    'macro',  # 거시경제 대시보드 (Market Pulse)
    'graph_analysis',  # 그래프 온톨로지 분석 (Phase 1)
    'rag_analysis',  # RAG 기반 AI 분석
    'serverless',  # Market Movers (AWS Lambda 전환 대상)
    'rest_framework',
    'rest_framework_simplejwt',  # JWT 인증 추가
    'rest_framework_simplejwt.token_blacklist',  # JWT 토큰 블랙리스트
    'corsheaders',  # CORS 지원 추가
    'django_celery_beat',  # Celery Beat 스케줄러
    'django_celery_results',  # Celery 작업 결과 저장
    'channels',  # WebSocket 지원
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS 미들웨어 추가
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'stock_vis',
        'USER': os.getenv('DB_USER', 'byeongjinjeong'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#AUTH

AUTH_USER_MODEL = 'users.User'

# CORS 설정
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Next.js 개발 서버
    "http://127.0.0.1:3000",
]

# 개발 환경과 프로덕션 환경 분리
if DEBUG:
    # 개발 환경에서만 모든 origin 허용
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # 프로덕션에서는 명시적으로 허용된 origins만
    CORS_ALLOW_ALL_ORIGINS = False
    # 프로덕션 도메인 추가 시 CORS_ALLOWED_ORIGINS에 추가

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

# Simple JWT 설정
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Access Token 유효 시간: 60분
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Refresh Token 유효 시간: 7일
    'ROTATE_REFRESH_TOKENS': True,                   # Refresh Token 재발급
    'BLACKLIST_AFTER_ROTATION': True,               # 이전 Refresh Token 블랙리스트
    'UPDATE_LAST_LOGIN': True,                      # 마지막 로그인 시간 업데이트

    'ALGORITHM': 'HS256',                           # 암호화 알고리즘
    'SIGNING_KEY': SECRET_KEY,                      # 서명 키
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),              # 인증 헤더 타입
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',      # 인증 헤더 이름
    'USER_ID_FIELD': 'id',                         # 사용자 ID 필드
    'USER_ID_CLAIM': 'user_id',                    # JWT Claim의 사용자 ID

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

#Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'stocks.log',
        },
    },
    'loggers': {
        'stocks': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Celery 설정
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/New_York'  # NYSE 시간대
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery 작업 결과 저장
CELERY_RESULT_BACKEND = 'django-db'

# Redis 캐시 백엔드 (기존 로컬 메모리 캐시를 Redis로 변경)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
    }
}

# Channels WebSocket 설정
ASGI_APPLICATION = 'config.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Celery Beat 스케줄은 config/celery.py의 app.conf.beat_schedule에서 관리
# (settings.py에 CELERY_BEAT_SCHEDULE 정의 시 celery.py 설정을 오버라이드하므로 주의)
