# Generated by Django 5.1.7 on 2025-03-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
