# Generated by Django 5.1.7 on 2026-01-08 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0003_alter_cashflowstatement_proceeds_from_issuance_of_long_term_debt_and_capital_securities_net'),
        ('users', '0006_watchlist_watchlistitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of the correlation value')),
                ('correlation', models.DecimalField(decimal_places=4, help_text='Correlation coefficient (-1.0 to 1.0)', max_digits=5)),
                ('previous_correlation', models.DecimalField(blank=True, decimal_places=4, help_text="Previous day's correlation coefficient", max_digits=5, null=True)),
                ('correlation_change', models.DecimalField(decimal_places=4, default=0, help_text='Change from previous correlation', max_digits=5)),
                ('is_anomaly', models.BooleanField(db_index=True, default=False, help_text='True if change exceeds threshold (±0.2)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_a', models.ForeignKey(help_text='First stock in the pair', on_delete=django.db.models.deletion.CASCADE, related_name='correlation_edges_a', to='stocks.stock')),
                ('stock_b', models.ForeignKey(help_text='Second stock in the pair', on_delete=django.db.models.deletion.CASCADE, related_name='correlation_edges_b', to='stocks.stock')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_edges', to='users.watchlist')),
            ],
            options={
                'db_table': 'graph_correlation_edge',
                'ordering': ['-date', 'stock_a', 'stock_b'],
            },
        ),
        migrations.CreateModel(
            name='CorrelationAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date when anomaly was detected')),
                ('anomaly_type', models.CharField(choices=[('divergence', 'Divergence'), ('convergence', 'Convergence'), ('reversal', 'Reversal')], help_text='Type of anomaly detected', max_length=20)),
                ('previous_correlation', models.DecimalField(decimal_places=4, help_text='Previous correlation value', max_digits=5)),
                ('current_correlation', models.DecimalField(decimal_places=4, help_text='Current correlation value', max_digits=5)),
                ('change_magnitude', models.DecimalField(decimal_places=4, help_text='Absolute change in correlation', max_digits=5)),
                ('alerted', models.BooleanField(db_index=True, default=False, help_text='True if user has been alerted about this anomaly')),
                ('alert_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when alert was sent', null=True)),
                ('dismissed', models.BooleanField(default=False, help_text='True if user dismissed this anomaly')),
                ('notes', models.TextField(blank=True, help_text='User notes about this anomaly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_anomalies', to='users.watchlist')),
                ('edge', models.ForeignKey(help_text='The edge that triggered this anomaly', on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='graph_analysis.correlationedge')),
            ],
            options={
                'db_table': 'graph_correlation_anomaly',
                'ordering': ['-date', '-change_magnitude'],
            },
        ),
        migrations.CreateModel(
            name='CorrelationMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of the correlation calculation')),
                ('matrix_data', models.JSONField(help_text='Correlation matrix as nested dict: {symbol1: {symbol2: correlation}}')),
                ('stock_count', models.IntegerField(default=0, help_text='Number of stocks in the matrix')),
                ('calculation_period', models.IntegerField(default=90, help_text='Number of days used for correlation calculation (default: 90 days = 3 months)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_matrices', to='users.watchlist')),
            ],
            options={
                'db_table': 'graph_correlation_matrix',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GraphMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Calculation date')),
                ('stock_count', models.IntegerField(help_text='Number of stocks processed')),
                ('edge_count', models.IntegerField(help_text='Number of edges (correlations) calculated')),
                ('anomaly_count', models.IntegerField(default=0, help_text='Number of anomalies detected')),
                ('calculation_time_ms', models.IntegerField(blank=True, help_text='Calculation time in milliseconds', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if calculation failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_metadata', to='users.watchlist')),
            ],
            options={
                'db_table': 'graph_metadata',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Cache date (latest date in the price data)')),
                ('prices', models.JSONField(help_text="List of price records: [{date: '2026-01-09', close: 151.75}, ...]")),
                ('period_days', models.IntegerField(default=90, help_text='Number of days in cache')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_caches', to='stocks.stock')),
            ],
            options={
                'db_table': 'graph_price_cache',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='correlationedge',
            index=models.Index(fields=['watchlist', '-date'], name='graph_corre_watchli_a32b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='correlationedge',
            index=models.Index(fields=['watchlist', 'is_anomaly', '-date'], name='graph_corre_watchli_3e31f9_idx'),
        ),
        migrations.AddIndex(
            model_name='correlationedge',
            index=models.Index(fields=['stock_a', 'stock_b', '-date'], name='graph_corre_stock_a_2f27a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='correlationedge',
            unique_together={('watchlist', 'stock_a', 'stock_b', 'date')},
        ),
        migrations.AddIndex(
            model_name='correlationanomaly',
            index=models.Index(fields=['watchlist', '-date'], name='graph_corre_watchli_45f154_idx'),
        ),
        migrations.AddIndex(
            model_name='correlationanomaly',
            index=models.Index(fields=['watchlist', 'alerted', '-date'], name='graph_corre_watchli_d7e29d_idx'),
        ),
        migrations.AddIndex(
            model_name='correlationanomaly',
            index=models.Index(fields=['-date', '-change_magnitude'], name='graph_corre_date_6fbd51_idx'),
        ),
        migrations.AddIndex(
            model_name='correlationmatrix',
            index=models.Index(fields=['watchlist', '-date'], name='graph_corre_watchli_8bc67e_idx'),
        ),
        migrations.AddIndex(
            model_name='correlationmatrix',
            index=models.Index(fields=['date'], name='graph_corre_date_552827_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='correlationmatrix',
            unique_together={('watchlist', 'date')},
        ),
        migrations.AddIndex(
            model_name='graphmetadata',
            index=models.Index(fields=['watchlist', '-date'], name='graph_metad_watchli_70f81f_idx'),
        ),
        migrations.AddIndex(
            model_name='graphmetadata',
            index=models.Index(fields=['status', '-date'], name='graph_metad_status_dc8a53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='graphmetadata',
            unique_together={('watchlist', 'date')},
        ),
        migrations.AddIndex(
            model_name='pricecache',
            index=models.Index(fields=['stock', '-date'], name='graph_price_stock_i_26ba5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricecache',
            unique_together={('stock', 'date')},
        ),
    ]
