from django.core.management.base import BaseCommand
from metrics.models import MetricDefinition


METRIC_SEEDS = [
    # ── profitability (5개) ──
    {
        "metric_code": "gross_margin",
        "display_name": "매출총이익률",
        "display_name_en": "Gross Margin",
        "category": "profitability",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "IncomeStatement.gross_profit / IncomeStatement.total_revenue",
        "source_apis": ["income-statement"],
        "source_fields": ["gross_profit", "total_revenue"],
        "sort_order": 1,
    },
    {
        "metric_code": "operating_margin",
        "display_name": "영업이익률",
        "display_name_en": "Operating Margin",
        "category": "profitability",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "IncomeStatement.operating_income / IncomeStatement.total_revenue",
        "source_apis": ["income-statement"],
        "source_fields": ["operating_income", "total_revenue"],
        "sort_order": 2,
    },
    {
        "metric_code": "net_margin",
        "display_name": "순이익률",
        "display_name_en": "Net Margin",
        "category": "profitability",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "IncomeStatement.net_income / IncomeStatement.total_revenue",
        "source_apis": ["income-statement"],
        "source_fields": ["net_income", "total_revenue"],
        "sort_order": 3,
    },
    {
        "metric_code": "roe",
        "display_name": "자기자본이익률",
        "display_name_en": "Return on Equity",
        "category": "profitability",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "IncomeStatement.net_income / BalanceSheet.total_shareholder_equity",
        "source_apis": ["income-statement", "balance-sheet"],
        "source_fields": ["net_income", "total_shareholder_equity"],
        "sort_order": 4,
    },
    {
        "metric_code": "roic",
        "display_name": "투하자본이익률",
        "display_name_en": "Return on Invested Capital",
        "category": "profitability",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "(operating_income * (1 - tax_rate)) / (equity + long_term_debt)",
        "source_apis": ["income-statement", "balance-sheet"],
        "source_fields": [
            "operating_income",
            "income_tax_expense",
            "total_shareholder_equity",
            "long_term_debt",
        ],
        "sort_order": 5,
    },
    # ── growth (4개) ──
    {
        "metric_code": "revenue_growth_yoy",
        "display_name": "매출 성장률 (YoY)",
        "display_name_en": "Revenue Growth YoY",
        "category": "growth",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "(rev_t - rev_t1) / abs(rev_t1)",
        "source_apis": ["income-statement"],
        "source_fields": ["total_revenue"],
        "sort_order": 1,
        "notes": "requires_prior_year",
    },
    {
        "metric_code": "operating_income_growth",
        "display_name": "영업이익 성장률",
        "display_name_en": "Operating Income Growth",
        "category": "growth",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "(op_t - op_t1) / abs(op_t1)",
        "source_apis": ["income-statement"],
        "source_fields": ["operating_income"],
        "sort_order": 2,
        "notes": "requires_prior_year",
    },
    {
        "metric_code": "fcf_growth_yoy",
        "display_name": "FCF 성장률",
        "display_name_en": "FCF Growth YoY",
        "category": "growth",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "(fcf_t - fcf_t1) / abs(fcf_t1)",
        "source_apis": ["cash-flow-statement"],
        "source_fields": ["operating_cashflow", "capital_expenditures"],
        "sort_order": 3,
        "notes": "requires_prior_year",
    },
    {
        "metric_code": "rev_growth_vs_industry",
        "display_name": "매출성장 vs 업종",
        "display_name_en": "Revenue Growth vs Industry",
        "category": "growth",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": False,
        "formula_description": "company_revenue_growth - industry_median_revenue_growth",
        "source_apis": ["income-statement"],
        "source_fields": ["total_revenue"],
        "sort_order": 4,
        "notes": "requires_benchmark",
    },
    # ── financial_structure (6개) ──
    {
        "metric_code": "debt_to_equity",
        "display_name": "부채비율",
        "display_name_en": "Debt to Equity",
        "category": "financial_structure",
        "unit": "ratio",
        "higher_is_better": False,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "BalanceSheet.short_longterm_debt_total / BalanceSheet.total_shareholder_equity",
        "fallback_formula": "(long_term_debt + short_term_debt) / total_shareholder_equity",
        "source_apis": ["balance-sheet"],
        "source_fields": ["short_longterm_debt_total", "total_shareholder_equity"],
        "sort_order": 1,
    },
    {
        "metric_code": "current_ratio",
        "display_name": "유동비율",
        "display_name_en": "Current Ratio",
        "category": "financial_structure",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "BalanceSheet.total_current_assets / BalanceSheet.total_current_liabilities",
        "source_apis": ["balance-sheet"],
        "source_fields": ["total_current_assets", "total_current_liabilities"],
        "sort_order": 2,
    },
    {
        "metric_code": "interest_coverage",
        "display_name": "이자보상배율",
        "display_name_en": "Interest Coverage",
        "category": "financial_structure",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "IncomeStatement.operating_income / IncomeStatement.interest_expense",
        "source_apis": ["income-statement"],
        "source_fields": ["operating_income", "interest_expense"],
        "sort_order": 3,
    },
    {
        "metric_code": "net_debt_to_ebitda",
        "display_name": "순부채/EBITDA",
        "display_name_en": "Net Debt to EBITDA",
        "category": "financial_structure",
        "unit": "ratio",
        "higher_is_better": False,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "(total_debt - cash) / ebitda",
        "source_apis": ["balance-sheet", "income-statement"],
        "source_fields": [
            "short_longterm_debt_total",
            "cash_and_cash_equivalents_at_carrying_value",
            "ebitda",
        ],
        "sort_order": 4,
    },
    {
        "metric_code": "cash_runway_years",
        "display_name": "현금 소진 연수",
        "display_name_en": "Cash Runway",
        "category": "financial_structure",
        "unit": "years",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": False,
        "formula_description": "cash / abs(operating_cashflow) if operating_cashflow < 0 else null",
        "source_apis": ["balance-sheet", "cash-flow-statement"],
        "source_fields": [
            "cash_and_cash_equivalents_at_carrying_value",
            "operating_cashflow",
        ],
        "sort_order": 5,
    },
    {
        "metric_code": "short_term_debt_pct",
        "display_name": "단기부채 비중",
        "display_name_en": "Short Term Debt %",
        "category": "financial_structure",
        "unit": "pct",
        "higher_is_better": False,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "short_term_debt / total_debt",
        "source_apis": ["balance-sheet"],
        "source_fields": ["short_term_debt", "short_longterm_debt_total"],
        "sort_order": 6,
    },
    # ── cash_flow_quality (6개) ──
    {
        "metric_code": "fcf_margin",
        "display_name": "잉여현금흐름 마진",
        "display_name_en": "FCF Margin",
        "category": "cash_flow_quality",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "(operating_cashflow - capital_expenditures) / total_revenue",
        "source_apis": ["cash-flow-statement", "income-statement"],
        "source_fields": [
            "operating_cashflow",
            "capital_expenditures",
            "total_revenue",
        ],
        "sort_order": 1,
    },
    {
        "metric_code": "ocf_to_net_income",
        "display_name": "영업CF/순이익",
        "display_name_en": "OCF to Net Income",
        "category": "cash_flow_quality",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "operating_cashflow / net_income",
        "source_apis": ["cash-flow-statement", "income-statement"],
        "source_fields": ["operating_cashflow", "net_income"],
        "sort_order": 2,
    },
    {
        "metric_code": "capex_to_ocf",
        "display_name": "Capex/영업CF",
        "display_name_en": "Capex to OCF",
        "category": "cash_flow_quality",
        "unit": "ratio",
        "higher_is_better": False,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "abs(capital_expenditures) / operating_cashflow",
        "source_apis": ["cash-flow-statement"],
        "source_fields": ["capital_expenditures", "operating_cashflow"],
        "sort_order": 3,
    },
    {
        "metric_code": "accruals_ratio",
        "display_name": "발생액 비율",
        "display_name_en": "Accruals Ratio",
        "category": "cash_flow_quality",
        "unit": "ratio",
        "higher_is_better": False,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "(net_income - operating_cashflow) / total_assets",
        "source_apis": ["income-statement", "cash-flow-statement", "balance-sheet"],
        "source_fields": ["net_income", "operating_cashflow", "total_assets"],
        "sort_order": 4,
    },
    {
        "metric_code": "fcf_conversion",
        "display_name": "FCF 전환율",
        "display_name_en": "FCF Conversion",
        "category": "cash_flow_quality",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "FCF / net_income",
        "source_apis": ["cash-flow-statement", "income-statement"],
        "source_fields": ["operating_cashflow", "capital_expenditures", "net_income"],
        "sort_order": 5,
    },
    {
        "metric_code": "cash_from_ops_trend",
        "display_name": "영업CF 추세 (3년)",
        "display_name_en": "OCF 3Y Trend",
        "category": "cash_flow_quality",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "3Y CAGR of operating_cashflow",
        "source_apis": ["cash-flow-statement"],
        "source_fields": ["operating_cashflow"],
        "sort_order": 6,
        "notes": "requires_multi_year",
    },
    # ── operational_efficiency (6개) ──
    {
        "metric_code": "dso",
        "display_name": "매출채권 회전일수",
        "display_name_en": "Days Sales Outstanding",
        "category": "operational_efficiency",
        "unit": "days",
        "higher_is_better": False,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "(current_net_receivables / total_revenue) * 365",
        "source_apis": ["balance-sheet", "income-statement"],
        "source_fields": ["current_net_receivables", "total_revenue"],
        "sort_order": 1,
    },
    {
        "metric_code": "ar_to_revenue",
        "display_name": "AR/매출 비율",
        "display_name_en": "AR to Revenue",
        "category": "operational_efficiency",
        "unit": "ratio",
        "higher_is_better": False,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "current_net_receivables / total_revenue",
        "source_apis": ["balance-sheet", "income-statement"],
        "source_fields": ["current_net_receivables", "total_revenue"],
        "sort_order": 2,
    },
    {
        "metric_code": "inventory_turnover_days",
        "display_name": "재고자산 회전일수",
        "display_name_en": "Inventory Turnover Days",
        "category": "operational_efficiency",
        "unit": "days",
        "higher_is_better": False,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "(inventory / cost_of_revenue) * 365",
        "source_apis": ["balance-sheet", "income-statement"],
        "source_fields": ["inventory", "cost_of_revenue"],
        "sort_order": 3,
    },
    {
        "metric_code": "inventory_vs_sales_growth",
        "display_name": "재고증가 vs 매출증가",
        "display_name_en": "Inventory vs Sales Growth",
        "category": "operational_efficiency",
        "unit": "ratio",
        "higher_is_better": False,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "inventory_growth_rate - revenue_growth_rate",
        "source_apis": ["balance-sheet", "income-statement"],
        "source_fields": ["inventory", "total_revenue"],
        "sort_order": 4,
        "notes": "requires_prior_year",
    },
    {
        "metric_code": "sga_to_revenue",
        "display_name": "판관비/매출",
        "display_name_en": "SGA to Revenue",
        "category": "operational_efficiency",
        "unit": "ratio",
        "higher_is_better": False,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "SGA / total_revenue",
        "source_apis": ["income-statement"],
        "source_fields": ["selling_general_and_administrative", "total_revenue"],
        "sort_order": 5,
    },
    {
        "metric_code": "asset_turnover",
        "display_name": "총자산회전율",
        "display_name_en": "Asset Turnover",
        "category": "operational_efficiency",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "total_revenue / total_assets",
        "source_apis": ["income-statement", "balance-sheet"],
        "source_fields": ["total_revenue", "total_assets"],
        "sort_order": 6,
    },
    # ── dilution_shareholder (4개) ──
    {
        "metric_code": "dilution_3y_cum",
        "display_name": "3년 누적 희석률",
        "display_name_en": "3Y Cumulative Dilution",
        "category": "dilution_shareholder",
        "unit": "pct",
        "higher_is_better": False,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "(shares_now - shares_3y_ago) / shares_3y_ago",
        "source_apis": ["balance-sheet"],
        "source_fields": ["common_stock_shares_outstanding"],
        "sort_order": 1,
        "notes": "requires_multi_year",
    },
    {
        "metric_code": "sbc_to_revenue",
        "display_name": "주식보상비/매출",
        "display_name_en": "SBC to Revenue",
        "category": "dilution_shareholder",
        "unit": "ratio",
        "higher_is_better": False,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "stock_based_compensation / total_revenue",
        "source_apis": ["cash-flow-statement", "income-statement"],
        "source_fields": ["stock_based_compensation", "total_revenue"],
        "sort_order": 2,
        "notes": "nullable_until_fmp: CashFlowStatement에 SBC 전용 필드 없음. FMP key-metrics 전환 시 추가 가능.",
    },
    {
        "metric_code": "buyback_offsets_sbc",
        "display_name": "자사주매입 vs SBC",
        "display_name_en": "Buyback Offsets SBC",
        "category": "dilution_shareholder",
        "unit": "flag",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": False,
        "formula_description": "abs(buyback) >= SBC → true/false. SBC 없으면 null.",
        "source_apis": ["cash-flow-statement"],
        "source_fields": ["payments_for_repurchase_of_common_stock"],
        "sort_order": 3,
        "notes": "sbc_to_revenue와 동일 제약.",
    },
    {
        "metric_code": "net_shareholder_yield",
        "display_name": "순주주수익률",
        "display_name_en": "Net Shareholder Yield",
        "category": "dilution_shareholder",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": True,
        "is_benchmarkable": True,
        "formula_description": "(dividend + buyback - issuance) / market_cap",
        "source_apis": ["cash-flow-statement", "stocks.Stock"],
        "source_fields": [
            "dividend_payout",
            "payments_for_repurchase_of_common_stock",
            "proceeds_from_issuance_of_common_stock",
            "market_capitalization",
        ],
        "sort_order": 4,
    },
    # ── valuation (3개, 보조) ──
    {
        "metric_code": "pe_ratio",
        "display_name": "PER",
        "display_name_en": "Price to Earnings",
        "category": "valuation",
        "unit": "ratio",
        "higher_is_better": False,
        "is_core_mvp": False,
        "is_benchmarkable": True,
        "formula_description": "Stock.pe_ratio (이미 계산된 값 사용)",
        "source_apis": ["stocks.Stock"],
        "source_fields": ["pe_ratio"],
        "sort_order": 1,
        "notes": "직접 계산하지 않고 Stock 또는 FMP key-metrics에서 가져옴.",
    },
    {
        "metric_code": "ev_to_ebitda",
        "display_name": "EV/EBITDA",
        "display_name_en": "EV to EBITDA",
        "category": "valuation",
        "unit": "ratio",
        "higher_is_better": False,
        "is_core_mvp": False,
        "is_benchmarkable": True,
        "formula_description": "Stock.ev_to_ebitda (이미 계산된 값 사용)",
        "source_apis": ["stocks.Stock"],
        "source_fields": ["ev_to_ebitda"],
        "sort_order": 2,
    },
    {
        "metric_code": "fcf_yield",
        "display_name": "FCF 수익률",
        "display_name_en": "FCF Yield",
        "category": "valuation",
        "unit": "ratio",
        "higher_is_better": True,
        "is_core_mvp": False,
        "is_benchmarkable": True,
        "formula_description": "FCF / market_cap",
        "source_apis": ["cash-flow-statement", "stocks.Stock"],
        "source_fields": [
            "operating_cashflow",
            "capital_expenditures",
            "market_capitalization",
        ],
        "sort_order": 3,
    },
]


class Command(BaseCommand):
    help = "34개 MetricDefinition 시드 데이터 생성 (멱등)"

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        for seed in METRIC_SEEDS:
            metric_code = seed.pop("metric_code")
            obj, created = MetricDefinition.objects.update_or_create(
                metric_code=metric_code,
                defaults=seed,
            )
            # metric_code를 다시 넣어 다음 실행에 영향 없도록
            seed["metric_code"] = metric_code

            if created:
                created_count += 1
            else:
                updated_count += 1

        total = created_count + updated_count
        self.stdout.write(
            self.style.SUCCESS(
                f"MetricDefinition 시드 완료: {total}개 ({created_count} 생성, {updated_count} 갱신)"
            )
        )
