# Generated by Django 5.1.7 on 2025-12-08 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('code', models.CharField(help_text='FRED 시리즈 ID 또는 커스텀 코드 (예: GDP, UNRATE, FEDFUNDS)', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='지표 이름', max_length=200)),
                ('name_ko', models.CharField(blank=True, help_text='한국어 지표 이름', max_length=200)),
                ('description', models.TextField(blank=True, help_text='지표 설명')),
                ('category', models.CharField(choices=[('growth', 'Growth'), ('inflation', 'Inflation'), ('employment', 'Employment'), ('interest_rate', 'Interest Rate'), ('volatility', 'Volatility'), ('sentiment', 'Sentiment'), ('housing', 'Housing'), ('trade', 'Trade')], default='growth', max_length=20)),
                ('data_source', models.CharField(choices=[('fred', 'FRED API'), ('fmp', 'FMP API'), ('calculated', 'Calculated')], default='fred', max_length=20)),
                ('update_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, help_text='단위 (%, $, index 등)', max_length=50)),
                ('decimal_places', models.IntegerField(default=2, help_text='소수점 자릿수')),
                ('display_order', models.IntegerField(default=0, help_text='대시보드 표시 순서')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('cache_ttl', models.IntegerField(default=3600, help_text='캐시 유효 시간 (초). 실시간=60, 일간=3600, 월간=86400')),
            ],
            options={
                'verbose_name': 'Economic Indicator',
                'verbose_name_plural': 'Economic Indicators',
                'db_table': 'macro_economic_indicator',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('symbol', models.CharField(help_text='지수 심볼 (예: SPX, NDX, VIX, DXY)', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='지수 이름', max_length=200)),
                ('name_ko', models.CharField(blank=True, help_text='한국어 지수 이름', max_length=200)),
                ('category', models.CharField(choices=[('us_equity', 'US Equity'), ('global_equity', 'Global Equity'), ('volatility', 'Volatility'), ('currency', 'Currency'), ('commodity', 'Commodity'), ('bond', 'Bond'), ('sector', 'Sector')], default='us_equity', max_length=20)),
                ('fmp_symbol', models.CharField(blank=True, max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Market Index',
                'verbose_name_plural': 'Market Indices',
                'db_table': 'macro_market_index',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='이벤트 고유 ID', max_length=100, unique=True)),
                ('title', models.CharField(help_text='이벤트 제목', max_length=300)),
                ('title_ko', models.CharField(blank=True, help_text='한국어 제목', max_length=300)),
                ('event_date', models.DateField(help_text='이벤트 날짜')),
                ('event_time', models.TimeField(blank=True, help_text='발표 시간 (ET)', null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('importance', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('country', models.CharField(default='US', help_text='국가 코드', max_length=10)),
                ('previous_value', models.CharField(blank=True, help_text='이전 발표치', max_length=50)),
                ('forecast_value', models.CharField(blank=True, help_text='예측치', max_length=50)),
                ('actual_value', models.CharField(blank=True, help_text='실제 발표치', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_indicator', models.ForeignKey(blank=True, help_text='관련 경제 지표', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='macro.economicindicator')),
            ],
            options={
                'verbose_name': 'Economic Event',
                'verbose_name_plural': 'Economic Events',
                'db_table': 'macro_economic_event',
                'ordering': ['event_date', 'event_time'],
                'indexes': [models.Index(fields=['event_date', 'importance'], name='macro_econo_event_d_daf200_idx'), models.Index(fields=['country', 'event_date'], name='macro_econo_country_69b08d_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndicatorCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_type', models.CharField(choices=[('positive', 'Positive Correlation'), ('negative', 'Negative Correlation'), ('leading', 'Leading Indicator'), ('lagging', 'Lagging Indicator')], max_length=20)),
                ('correlation_coefficient', models.DecimalField(blank=True, decimal_places=4, help_text='최근 상관계수 (-1 ~ +1)', max_digits=5, null=True)),
                ('lead_lag_days', models.IntegerField(default=0, help_text='A가 B를 선행하는 일수 (음수면 후행)')),
                ('description', models.TextField(blank=True)),
                ('description_ko', models.TextField(blank=True)),
                ('calculation_period_days', models.IntegerField(default=252, help_text='상관계수 계산 기간 (거래일)')),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('indicator_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_a', to='macro.economicindicator')),
                ('indicator_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_b', to='macro.economicindicator')),
            ],
            options={
                'verbose_name': 'Indicator Correlation',
                'verbose_name_plural': 'Indicator Correlations',
                'db_table': 'macro_indicator_correlation',
                'unique_together': {('indicator_a', 'indicator_b')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='데이터 기준일')),
                ('value', models.DecimalField(decimal_places=6, help_text='지표 값', max_digits=20)),
                ('period', models.CharField(blank=True, help_text='기간 정보 (예: 2024Q1, 2024-01)', max_length=20)),
                ('is_preliminary', models.BooleanField(default=False, help_text='속보치/잠정치 여부')),
                ('revision_date', models.DateField(blank=True, help_text='수정 발표일 (있는 경우)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='macro.economicindicator')),
            ],
            options={
                'verbose_name': 'Indicator Value',
                'verbose_name_plural': 'Indicator Values',
                'db_table': 'macro_indicator_value',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['indicator', '-date'], name='macro_indic_indicat_9d6375_idx'), models.Index(fields=['-date'], name='macro_indic_date_2ac92b_idx')],
                'unique_together': {('indicator', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MarketIndexPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('close', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=4, help_text='전일 대비 변동', max_digits=15, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=4, help_text='전일 대비 변동률 (%)', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='macro.marketindex')),
            ],
            options={
                'verbose_name': 'Market Index Price',
                'verbose_name_plural': 'Market Index Prices',
                'db_table': 'macro_market_index_price',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['index', '-date'], name='macro_marke_index_i_58254f_idx')],
                'unique_together': {('index', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SectorIndicatorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(help_text='섹터 코드 (technology, financials, healthcare 등)', max_length=50)),
                ('sector_name', models.CharField(help_text='섹터 이름', max_length=100)),
                ('sector_name_ko', models.CharField(blank=True, help_text='한국어 섹터 이름', max_length=100)),
                ('impact_direction', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], default='neutral', max_length=20)),
                ('impact_strength', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('condition_type', models.CharField(choices=[('rising', 'Rising'), ('falling', 'Falling'), ('high', 'High Level'), ('low', 'Low Level'), ('any', 'Any Change')], default='any', max_length=20)),
                ('condition_threshold', models.DecimalField(blank=True, decimal_places=4, help_text='조건 임계값 (예: 금리 +0.5%p)', max_digits=10, null=True)),
                ('rationale', models.TextField(blank=True, help_text='영향 관계의 근거 설명')),
                ('rationale_ko', models.TextField(blank=True, help_text='한국어 설명')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_impacts', to='macro.economicindicator')),
            ],
            options={
                'verbose_name': 'Sector-Indicator Relation',
                'verbose_name_plural': 'Sector-Indicator Relations',
                'db_table': 'macro_sector_indicator_relation',
                'indexes': [models.Index(fields=['indicator', 'impact_direction'], name='macro_secto_indicat_ecddc0_idx'), models.Index(fields=['sector_code'], name='macro_secto_sector__745b4b_idx')],
                'unique_together': {('indicator', 'sector_code', 'condition_type')},
            },
        ),
    ]
