# Generated by Django 5.1.7 on 2026-03-06 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0005_multi_provider_news_collection'),
        ('users', '0007_add_user_interest_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorDNA',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='investor_dna', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_theses', models.IntegerField(default=0)),
                ('closed_theses', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('premise_category_counts', models.JSONField(default=dict)),
                ('indicator_type_counts', models.JSONField(default=dict)),
                ('ai_suggestions_shown', models.IntegerField(default=0)),
                ('ai_suggestions_accepted', models.IntegerField(default=0)),
                ('personalization_weight', models.FloatField(default=0.5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('bearish', 'Bearish'), ('bullish', 'Bullish'), ('neutral', 'Neutral')], max_length=10)),
                ('target', models.CharField(max_length=100)),
                ('target_type', models.CharField(choices=[('index', 'Index'), ('stock', 'Stock'), ('sector', 'Sector'), ('macro', 'Macro')], max_length=20)),
                ('expected_timeframe', models.CharField(blank=True, max_length=50)),
                ('expected_magnitude', models.CharField(blank=True, max_length=50)),
                ('target_date_start', models.DateField(blank=True, null=True)),
                ('target_date_end', models.DateField(blank=True, null=True)),
                ('thesis_type', models.CharField(choices=[('event', 'Event-driven'), ('trend', 'Trend'), ('comparison', 'Comparison'), ('divergence', 'Divergence'), ('custom', 'Custom')], max_length=20)),
                ('entry_source', models.CharField(choices=[('news', 'Today Issue'), ('free_input', 'Free Input'), ('popular', 'Popular Thesis'), ('template', 'Template'), ('chainsight', 'Chain Sight')], max_length=20)),
                ('status', models.CharField(choices=[('setting_up', 'Setting Up'), ('active', 'Active'), ('closed', 'Closed'), ('paused', 'Paused')], default='setting_up', max_length=20)),
                ('current_state', models.CharField(choices=[('warming_up', 'Warming Up'), ('active', 'Active'), ('strengthening', 'Strengthening'), ('weakening', 'Weakening'), ('critical', 'Critical'), ('expired', 'Expired'), ('needs_review', 'Needs Review'), ('paused', 'Paused')], default='warming_up', max_length=20)),
                ('current_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('neutral', 'Neutral')], max_length=10, null=True)),
                ('outcome_note', models.TextField(blank=True)),
                ('premise_universe_ids', models.JSONField(default=list)),
                ('indicator_universe_ids', models.JSONField(default=list)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='thesis.thesis')),
                ('source_news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_sources', to='news.newsarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PopularThesisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('support_ratio', models.FloatField(default=0.5)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('thesis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='thesis.thesis')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='HypothesisEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('thesis_created', '가설 생성'), ('thesis_closed', '가설 마감'), ('premise_added', '전제 추가'), ('premise_modified', '전제 수정'), ('premise_removed', '전제 제거'), ('indicator_added', '지표 추가'), ('indicator_removed', '지표 제거'), ('ai_suggestion_shown', 'AI 제안 표시'), ('ai_suggestion_accepted', 'AI 제안 수락'), ('ai_suggestion_rejected', 'AI 제안 거절'), ('outcome_correct', '적중 판정'), ('outcome_incorrect', '미적중 판정'), ('outcome_neutral', '중립 판정')], max_length=30)),
                ('event_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypothesis_events', to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='thesis.thesis')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='thesis.thesis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_follows', to=settings.AUTH_USER_MODEL)),
                ('user_thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_from', to='thesis.thesis')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('indicator_type', models.CharField(choices=[('market_data', 'Market Data'), ('macro', 'Macro Economic'), ('sentiment', 'News Sentiment'), ('technical', 'Technical'), ('fundamental', 'Fundamental'), ('custom', 'Custom')], max_length=30)),
                ('data_source', models.CharField(choices=[('fmp', 'FMP'), ('fred', 'FRED'), ('news_sentiment', 'News Sentiment'), ('manual', 'Manual'), ('custom', 'Custom')], max_length=50)),
                ('data_params', models.JSONField(default=dict)),
                ('support_direction', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10)),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('current_score', models.FloatField(blank=True, null=True)),
                ('current_degree', models.FloatField(blank=True, null=True)),
                ('current_color', models.CharField(blank=True, max_length=10)),
                ('current_label', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('epsilon', models.FloatField(default=0.0001)),
                ('window', models.IntegerField(default=60)),
                ('decay', models.FloatField(default=0.95)),
                ('min_valid_value', models.FloatField(blank=True, null=True)),
                ('max_valid_value', models.FloatField(blank=True, null=True)),
                ('max_change_pct', models.FloatField(blank=True, null=True)),
                ('allow_extreme_jump', models.BooleanField(default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('override_score', models.FloatField(blank=True, null=True)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='thesis.thesis')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThesisAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('direction_flip', 'Direction Flip'), ('sharp_move', 'Sharp Move'), ('extreme_volatility', 'Extreme Volatility'), ('weakest_link', 'Weakest Link'), ('premise_divergence', 'Premise Divergence'), ('stale_data', 'Stale Data'), ('indicator_overlap', 'Indicator Overlap'), ('indicator_bias', 'Indicator Bias'), ('state_change', 'State Change'), ('milestone', 'Milestone'), ('needs_review', 'Needs Review')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('target_id', models.CharField(blank=True, max_length=36)),
                ('cooldown_hours', models.IntegerField(default=24)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_pushed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='thesis.thesis')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='thesis.thesisindicator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('raw_value', models.FloatField()),
                ('asof', models.DateTimeField()),
                ('validation_status', models.CharField(choices=[('ok', 'OK'), ('null_value', 'Null Value'), ('non_finite', 'Non-Finite'), ('below_minimum', 'Below Minimum'), ('above_maximum', 'Above Maximum'), ('stale_data', 'Stale Data'), ('extreme_jump', 'Extreme Jump'), ('extreme_jump_allowed', 'Extreme Jump Allowed')], default='ok', max_length=25)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='thesis.thesisindicator')),
            ],
            options={
                'ordering': ['-asof'],
            },
        ),
        migrations.CreateModel(
            name='ThesisPremise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('macro', 'Macro'), ('sector', 'Sector'), ('company', 'Company'), ('technical', 'Technical'), ('sentiment', 'Sentiment'), ('custom', 'Custom')], max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premises', to='thesis.thesis')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='thesisindicator',
            name='premise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='thesis.thesispremise'),
        ),
        migrations.CreateModel(
            name='ThesisSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asof_date', models.DateField()),
                ('data_coverage', models.FloatField(default=1.0)),
                ('universe_snapshot', models.JSONField(default=dict)),
                ('ordered_indicator_ids', models.JSONField(default=list)),
                ('date', models.DateField()),
                ('overall_score', models.FloatField()),
                ('state', models.CharField(max_length=20)),
                ('premise_scores', models.JSONField(default=dict)),
                ('indicator_degrees', models.JSONField(default=dict)),
                ('notable_changes', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='thesis.thesis')),
            ],
            options={
                'ordering': ['-asof_date'],
            },
        ),
        migrations.CreateModel(
            name='ValidityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thesis_type', models.CharField(max_length=30)),
                ('indicator_data_key', models.CharField(max_length=50)),
                ('market_regime', models.CharField(max_length=20)),
                ('indicator_aligned', models.BooleanField()),
                ('thesis_correct', models.BooleanField()),
                ('score', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validity_records', to='thesis.thesisindicator')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validity_records', to='thesis.thesis')),
            ],
        ),
        migrations.AddIndex(
            model_name='thesis',
            index=models.Index(fields=['user', '-created_at'], name='thesis_thes_user_id_32036a_idx'),
        ),
        migrations.AddIndex(
            model_name='thesis',
            index=models.Index(fields=['user', 'status'], name='thesis_thes_user_id_2829b2_idx'),
        ),
        migrations.AddIndex(
            model_name='thesis',
            index=models.Index(fields=['status', '-created_at'], name='thesis_thes_status_643c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='hypothesisevent',
            index=models.Index(fields=['user', '-created_at'], name='thesis_hypo_user_id_75e145_idx'),
        ),
        migrations.AddIndex(
            model_name='hypothesisevent',
            index=models.Index(fields=['thesis', 'event_type'], name='thesis_hypo_thesis__86d351_idx'),
        ),
        migrations.AddIndex(
            model_name='hypothesisevent',
            index=models.Index(fields=['event_type', '-created_at'], name='thesis_hypo_event_t_f9811f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thesisfollow',
            unique_together={('user', 'original_thesis')},
        ),
        migrations.AddIndex(
            model_name='thesisalert',
            index=models.Index(fields=['thesis', 'alert_type', 'target_id', '-created_at'], name='thesis_thes_thesis__be20b6_idx'),
        ),
        migrations.AddIndex(
            model_name='thesisalert',
            index=models.Index(fields=['thesis', 'is_read'], name='thesis_thes_thesis__e5a0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorreading',
            index=models.Index(fields=['indicator', '-asof'], name='thesis_indi_indicat_e08073_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorreading',
            index=models.Index(fields=['indicator', 'validation_status', '-asof'], name='thesis_indi_indicat_9ef849_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorreading',
            unique_together={('indicator', 'asof')},
        ),
        migrations.AddIndex(
            model_name='thesispremise',
            index=models.Index(fields=['thesis', 'is_active'], name='thesis_thes_thesis__33f916_idx'),
        ),
        migrations.AddIndex(
            model_name='thesisindicator',
            index=models.Index(fields=['thesis', 'is_active'], name='thesis_thes_thesis__ad710f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thesissnapshot',
            unique_together={('thesis', 'asof_date')},
        ),
        migrations.AddIndex(
            model_name='validityrecord',
            index=models.Index(fields=['thesis_type', 'indicator_data_key', 'market_regime'], name='thesis_vali_thesis__5262a8_idx'),
        ),
    ]
