# Generated by Django 5.1.7 on 2026-03-07 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesissnapshot',
            name='date',
        ),
        migrations.AlterField(
            model_name='hypothesisevent',
            name='thesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='thesis.thesis'),
        ),
        migrations.AlterField(
            model_name='indicatorreading',
            name='raw_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorreading',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thesisindicator',
            name='indicator_type',
            field=models.CharField(choices=[('market_data', 'Market Data'), ('macro', 'Macro Economic'), ('sentiment', 'News Sentiment'), ('technical', 'Technical'), ('custom', 'Custom')], max_length=30),
        ),
    ]
