# Generated by Django 5.1.7 on 2026-03-08 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_remove_thesissnapshot_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisalert',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='thesis.thesisindicator'),
        ),
        migrations.AlterField(
            model_name='thesisindicator',
            name='premise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='thesis.thesispremise'),
        ),
    ]
