# Generated by Django 5.1.7 on 2026-03-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0003_fix_fk_on_delete_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisindicator',
            name='display_unit',
            field=models.CharField(default='', help_text="UI 표시 단위: '$', '원', '%', 'pt', '' 등", max_length=10),
        ),
    ]
