# Generated by Django 5.1.7 on 2026-03-20 04:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_populate_display_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(choices=[('chain', 'Chain Sight'), ('eod', 'EOD Signals'), ('news', 'News')], max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('support', 'Support'), ('risk', 'Risk'), ('signal', 'Signal'), ('theme', 'Theme')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['target', 'source'], name='thesis_keyw_target_42e96e_idx')],
                'unique_together': {('target', 'source', 'text')},
            },
        ),
    ]
