# Generated by Django 5.1.7 on 2026-03-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0006_add_keyword_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordcache',
            name='strength',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='키워드 강도: high=중요 단서, medium=일반, low=약한 힌트', max_length=10),
        ),
    ]
