# Generated by Django 5.1.7 on 2026-04-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0007_keyword_cache_add_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisindicator',
            name='data_source',
            field=models.CharField(choices=[('fmp', 'FMP'), ('fred', 'FRED'), ('news_sentiment', 'News Sentiment'), ('metrics', 'Metrics'), ('manual', 'Manual'), ('custom', 'Custom')], max_length=50),
        ),
    ]
