# Generated by Django 5.1.7 on 2026-04-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0008_add_metrics_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisindicator',
            name='recommendation_reason',
            field=models.TextField(blank=True, default='', help_text='이 지표가 가설에 추천된 이유'),
        ),
    ]
