# Generated by Django 5.2.14 on 2026-06-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketpulse', '0005_pr_a2_rebuild_news_ttl_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('model_version', models.CharField(default='gemini-2.5-flash', max_length=50)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('REFUSED', 'LLM Refused')], default='OK', max_length=20)),
                ('senses', models.JSONField(blank=True, default=dict)),
                ('prompt_inputs', models.JSONField(blank=True, default=dict)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, help_text='LLM 호출 비용 USD', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Translation Log',
                'verbose_name_plural': 'Translation Logs',
                'db_table': 'mp_translation_log',
                'ordering': ['-date'],
                'unique_together': {('date', 'model_version')},
            },
        ),
    ]
