# Generated by Django 5.2.14 on 2026-07-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketpulse', '0006_translationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogDayContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='모집단일(이웃일 lookup 키)', unique=True)),
                ('why_text', models.TextField(help_text='L3 맥락 1문장(한국어, 톤가드 통과분)')),
                ('provenance', models.JSONField(default=list, help_text='근거 헤드라인 목록 [{id, url, title}]')),
                ('prompt_version', models.CharField(help_text='생성 프롬프트 버전(동결 태깅)', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mp_analog_day_context',
                'ordering': ['-date'],
            },
        ),
    ]
