"""
Stock-Vis Metric Definitions (코드 상수)
=========================================

Metric Dictionary v1.2 기반 (2026-04-18 동기화 완료).
이 파일이 지표 정의의 Single Source of Truth.
DB에는 저장하지 않으며, MetricResult.metric_id의 유효성 검증에 사용.

구조: METRICS[metric_id] = { ... }

Type별 구성:
  - stock_level (Type 1): 39개 — 개별 종목 지표
  - portfolio_level (Type 2): 13개 — 포트폴리오 전체 지표
  - composite (Type 3): 5개 — Multi-Factor 합성 팩터

총 57개.
"""

METRICS = {
    # ----------------------------------------------------------------
    # 수익성 (4개)
    # ----------------------------------------------------------------
    "roic": {
        "display_name": "ROIC",
        "description": "투하자본수익률. 기업이 투자한 자본 대비 얼마나 효율적으로 수익을 창출하는지 측정.",
        "formula": "EBIT × (1 - 0.21) / Invested Capital",
        "formula_detail": (
            "EBIT: operatingIncome, "
            "Invested Capital: totalStockholdersEquity + totalDebt - cashAndCashEquivalents. "
            "세율 21%(미국 법정세율) MVP 고정."
        ),
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/income-statement?period=annual, /balance-sheet-statement?period=annual",
        "fmp_fields": [
            "operatingIncome",
            "totalStockholdersEquity",
            "totalDebt",
            "cashAndCashEquivalents",
        ],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "quarterly",
        "ttm_method": "latest_annual",
        "excluded_sectors": ["Financial Services"],
        "display_condition": None,
    },
    "roe": {
        "display_name": "ROE",
        "description": "자기자본이익률. 주주 자본 대비 순이익 비율.",
        "formula": "netIncome / totalStockholdersEquity",
        "formula_detail": "TTM 순이익 / 최근 분기 자기자본",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "direct",
        "fmp_endpoint": "/key-metrics-ttm",
        "fmp_fields": ["roeTTM"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "quarterly",
        "ttm_method": "fmp_ttm_field",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "gross_margin": {
        "display_name": "매출총이익률",
        "description": "매출 대비 매출총이익 비율. 가격 결정력과 원가 구조를 반영.",
        "formula": "grossProfit / revenue",
        "formula_detail": "FMP TTM 필드 직접 사용",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "direct",
        "fmp_endpoint": "/key-metrics-ttm",
        "fmp_fields": ["grossProfitMarginTTM"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "quarterly",
        "ttm_method": "fmp_ttm_field",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "fcf_margin": {
        "display_name": "FCF 마진",
        "description": "매출 대비 잉여현금흐름 비율. 실제 현금 창출 능력.",
        "formula": "freeCashFlow / revenue",
        "formula_detail": "freeCashFlow = operatingCashFlow - capitalExpenditure",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/cash-flow-statement?period=annual",
        "fmp_fields": ["operatingCashFlow", "capitalExpenditure", "revenue"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "quarterly",
        "ttm_method": "sum_recent_4q",
        "excluded_sectors": [],
        "display_condition": None,
    },
    # ----------------------------------------------------------------
    # 성장 (2개)
    # ----------------------------------------------------------------
    "eps_growth_yoy": {
        "display_name": "EPS 성장률 (YoY)",
        "description": "전년 동기 대비 주당순이익 성장률.",
        "formula": "(당기 EPS - 전기 EPS) / |전기 EPS|",
        "formula_detail": "전기 EPS가 0이면 Missing 처리",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/income-statement?period=annual",
        "fmp_fields": ["eps", "epsdiluted"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "quarterly",
        "ttm_method": "yoy_comparison",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "revenue_growth_yoy": {
        "display_name": "매출 성장률 (YoY)",
        "description": "전년 동기 대비 매출 성장률.",
        "formula": "(당기 revenue - 전기 revenue) / 전기 revenue",
        "formula_detail": "전기 revenue가 0이면 Missing 처리",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/income-statement?period=annual",
        "fmp_fields": ["revenue"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "quarterly",
        "ttm_method": "yoy_comparison",
        "excluded_sectors": [],
        "display_condition": None,
    },
    # ----------------------------------------------------------------
    # 밸류에이션 (4개)
    # ----------------------------------------------------------------
    "pe_ratio": {
        "display_name": "PER",
        "description": "주가수익비율. 주가가 이익의 몇 배인지.",
        "formula": "price / EPS",
        "formula_detail": "FMP TTM 필드 직접 사용. 음수(적자)면 Not Applicable",
        "direction": "lower_is_better",
        "metric_type": "stock_level",
        "source_type": "direct",
        "fmp_endpoint": "/key-metrics-ttm",
        "fmp_fields": ["peRatioTTM"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": "fmp_ttm_field",
        "excluded_sectors": [],
        "display_condition": "eps > 0",
    },
    "pb_ratio": {
        "display_name": "PBR",
        "description": "주가순자산비율. 주가가 장부가치의 몇 배인지.",
        "formula": "price / BVPS",
        "formula_detail": "FMP TTM 필드 직접 사용",
        "direction": "lower_is_better",
        "metric_type": "stock_level",
        "source_type": "direct",
        "fmp_endpoint": "/key-metrics-ttm",
        "fmp_fields": ["pbRatioTTM"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": "fmp_ttm_field",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "peg_ratio": {
        "display_name": "PEG",
        "description": "PER을 이익 성장률로 나눈 값. 성장 대비 밸류에이션 평가.",
        "formula": "PE / EPS Growth Rate",
        "formula_detail": "EPS Growth가 0 이하이면 Not Applicable",
        "direction": "lower_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/key-metrics-ttm",
        "fmp_fields": ["pegRatioTTM"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "quarterly",
        "ttm_method": "fmp_ttm_field",
        "excluded_sectors": [],
        "display_condition": "eps_growth > 0",
    },
    "ev_to_ebitda": {
        "display_name": "EV/EBITDA",
        "description": "기업가치 대비 EBITDA. 부채 포함한 전체 기업 가치 평가.",
        "formula": "enterpriseValue / EBITDA",
        "formula_detail": "EBITDA가 0 이하이면 Not Applicable",
        "direction": "lower_is_better",
        "metric_type": "stock_level",
        "source_type": "direct",
        "fmp_endpoint": "/key-metrics-ttm",
        "fmp_fields": ["enterpriseValueOverEBITDATTM"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": "fmp_ttm_field",
        "excluded_sectors": [],
        "display_condition": "ebitda > 0",
    },
    # ----------------------------------------------------------------
    # 재무 건전성 (2개)
    # ----------------------------------------------------------------
    "debt_to_equity": {
        "display_name": "부채비율",
        "description": "총부채 대 자기자본 비율. 재무 레버리지 수준.",
        "formula": "totalDebt / totalStockholdersEquity",
        "formula_detail": "자기자본이 0 이하이면 Not Applicable",
        "direction": "lower_is_better",
        "metric_type": "stock_level",
        "source_type": "direct",
        "fmp_endpoint": "/key-metrics-ttm",
        "fmp_fields": ["debtToEquityTTM"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "quarterly",
        "ttm_method": "fmp_ttm_field",
        "excluded_sectors": ["Financial Services"],
        "display_condition": "equity > 0",
    },
    "payout_ratio": {
        "display_name": "배당성향",
        "description": "순이익 중 배당금 비율. 배당 지속 가능성 판단.",
        "formula": "dividendsPaid / netIncome",
        "formula_detail": "무배당 기업은 Not Applicable",
        "direction": "neutral",
        "metric_type": "stock_level",
        "source_type": "direct",
        "fmp_endpoint": "/key-metrics-ttm",
        "fmp_fields": ["payoutRatioTTM"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "quarterly",
        "ttm_method": "fmp_ttm_field",
        "excluded_sectors": [],
        "display_condition": "pays_dividend",
    },
    # ----------------------------------------------------------------
    # 배당·주주환원 (4개)
    # ----------------------------------------------------------------
    "dividend_yield": {
        "display_name": "배당수익률",
        "description": "주가 대비 연간 배당금 비율.",
        "formula": "annualDividend / price",
        "formula_detail": "무배당 기업은 Not Applicable",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "direct",
        "fmp_endpoint": "/key-metrics-ttm",
        "fmp_fields": ["dividendYieldTTM"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": "fmp_ttm_field",
        "excluded_sectors": [],
        "display_condition": "pays_dividend",
    },
    "shareholder_yield": {
        "display_name": "주주수익률",
        "description": "배당 + 자사주 매입 + 순부채 감소를 합산한 총 주주환원.",
        "formula": "dividend_yield + net_buyback_yield + net_debt_reduction_rate",
        "formula_detail": "3개 구성요소 중 하나라도 Missing이면 해당 항목은 0으로 처리 (전체 null 아님)",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "composite",
        "fmp_endpoint": None,
        "fmp_fields": [],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "quarterly",
        "ttm_method": "composite",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "net_buyback_yield": {
        "display_name": "순자사주매입률",
        "description": "시가총액 대비 순자사주매입 비율.",
        "formula": "(전기 shares - 당기 shares) × 평균주가 / 시가총액",
        "formula_detail": "주식 분할 시 FMP 조정값 사용. 신주 발행이면 음수.",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/income-statement?period=annual, /historical-market-capitalization",
        "fmp_fields": ["weightedAverageShsOut", "marketCap"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "annual",
        "ttm_method": "yoy_comparison",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "net_debt_reduction_rate": {
        "display_name": "순부채감소율",
        "description": "전년 대비 순부채 감소분을 시가총액으로 정규화.",
        "formula": "(전기 netDebt - 당기 netDebt) / 전기 marketCap",
        "formula_detail": "netDebt = totalDebt - cashAndCashEquivalents",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/balance-sheet-statement?period=annual, /historical-market-capitalization",
        "fmp_fields": ["totalDebt", "cashAndCashEquivalents", "marketCap"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "annual",
        "ttm_method": "yoy_comparison",
        "excluded_sectors": ["Financial Services"],
        "display_condition": None,
    },
    # ----------------------------------------------------------------
    # 지속성·멀티이어 (7개) — count_based / numeric_aggregation
    # ----------------------------------------------------------------
    "roic_consistency_5y": {
        "display_name": "ROIC 일관성 (5년)",
        "description": "최근 5년 중 ROIC가 10% 이상인 연도 수.",
        "formula": "count(ROIC >= 10% over 5 years)",
        "formula_detail": "Count형. 공통 결정 #2에 따라 4년 데이터에서도 계산 가능 (Lenient).",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/income-statement?period=annual, /balance-sheet-statement?period=annual",
        "fmp_fields": [
            "operatingIncome",
            "totalStockholdersEquity",
            "totalDebt",
            "cashAndCashEquivalents",
        ],
        "aggregation_type": "count_based",
        "min_years": 4,
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "annual",
        "ttm_method": None,
        "excluded_sectors": ["Financial Services"],
        "display_condition": None,
    },
    "earnings_consistency_5y": {
        "display_name": "이익 일관성 (5년)",
        "description": "최근 5년 중 순이익이 양수인 연도 수.",
        "formula": "count(netIncome > 0 over 5 years)",
        "formula_detail": "Count형. min_years=4.",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/income-statement?period=annual",
        "fmp_fields": ["netIncome"],
        "aggregation_type": "count_based",
        "min_years": 4,
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "annual",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "revenue_growth_consistency_3y": {
        "display_name": "매출 성장 일관성 (3년)",
        "description": "최근 3년 중 매출이 전년 대비 증가한 연도 수.",
        "formula": "count(revenue YoY > 0 over 3 years)",
        "formula_detail": "Count형. min_years=2 (3년 지표는 최소 2년).",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/income-statement?period=annual",
        "fmp_fields": ["revenue"],
        "aggregation_type": "count_based",
        "min_years": 2,
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "annual",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "roe_stability_5y": {
        "display_name": "ROE 안정성 (5년)",
        "description": "최근 5년 ROE의 표준편차. 낮을수록 안정적.",
        "formula": "std(ROE over 5 years)",
        "formula_detail": "수치 집계형. Strict — 5년 풀 데이터 필수.",
        "direction": "lower_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/key-metrics?period=annual",
        "fmp_fields": ["roe"],
        "aggregation_type": "numeric_aggregation",
        "min_years": 5,
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "annual",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "earnings_volatility_5y": {
        "display_name": "이익 변동성 (5년)",
        "description": "최근 5년 EPS의 표준편차. 낮을수록 예측 가능.",
        "formula": "std(EPS over 5 years)",
        "formula_detail": "수치 집계형. Strict — 5년 풀 데이터 필수.",
        "direction": "lower_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/income-statement?period=annual",
        "fmp_fields": ["epsdiluted"],
        "aggregation_type": "numeric_aggregation",
        "min_years": 5,
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "annual",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "dividend_growth_consistency_5y": {
        "display_name": "배당 성장 일관성 (5년)",
        "description": "최근 5년 중 배당금이 전년 대비 증가한 연도 수.",
        "formula": "count(DPS YoY > 0 over 5 years)",
        "formula_detail": "Count형. min_years=4. 무배당 기업은 Not Applicable.",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/key-metrics?period=annual",
        "fmp_fields": ["dividendPerShare"],
        "aggregation_type": "count_based",
        "min_years": 4,
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "annual",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": "pays_dividend",
    },
    "dividend_growth_rate_5y": {
        "display_name": "배당 성장률 (5년 CAGR)",
        "description": "최근 5년 배당금의 연평균 성장률.",
        "formula": "(DPS_latest / DPS_5y_ago)^(1/5) - 1",
        "formula_detail": "수치 집계형. Strict — 5년 풀 데이터 필수. 무배당 기업은 Not Applicable.",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/key-metrics?period=annual",
        "fmp_fields": ["dividendPerShare"],
        "aggregation_type": "numeric_aggregation",
        "min_years": 5,
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "annual",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": "pays_dividend",
    },
    # ----------------------------------------------------------------
    # Piotroski (1개 — 서브 9개는 세션 C에서 별도 정의)
    # ----------------------------------------------------------------
    "f_score_total": {
        "display_name": "Piotroski F-Score",
        "description": "Piotroski 9개 재무 건전성 항목의 합산 점수 (0~9). 수익성 4 + 레버리지/유동성/자본조달 3 + 운영 효율성 2.",
        "formula": "sum of 9 binary sub-scores",
        "formula_detail": (
            "서브 9개: roa_positive, cfo_positive, roa_change_positive, accrual_quality, "
            "leverage_decrease, liquidity_increase, no_share_issuance, margin_increase, "
            "asset_turnover_increase. 각 bool 판정=1, 미달=0. "
            "상세 판정 조건은 Metric Dictionary v1.2 §5 #37 참조. "
            "StockMetricValue.extra_data JSON에 서브별 결과 보존."
        ),
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "composite",
        "fmp_endpoint": "/income-statement, /balance-sheet-statement, /cash-flow-statement (각 2년치, annual)",
        "fmp_fields": [
            "netIncome",
            "operatingCashFlow",
            "totalAssets",
            "longTermDebt",
            "totalCurrentAssets",
            "totalCurrentLiabilities",
            "weightedAverageShsOutDil",
            "grossProfit",
            "revenue",
        ],
        "aggregation_type": "composite_checklist",
        "comparison_group": "universe",
        "fallback_rule": "universe only",
        "refresh_frequency": "annual",
        "ttm_method": "latest_annual",
        "excluded_sectors": ["Financial Services", "Real Estate"],
        "display_condition": None,
    },
    # ================================================================
    # 가격·시장 지표 (Type 1: stock_level) — Metric Dictionary §5 #24~39
    # ================================================================
    "beta": {
        "display_name": "베타",
        "description": "시장 대비 종목 수익률의 민감도. 1 초과 = 시장보다 변동성 큼.",
        "formula": "Cov(r_stock, r_market) / Var(r_market)",
        "formula_detail": "최근 252 거래일 일간 수익률 기준. 벤치마크 = S&P 500.",
        "direction": "neutral",
        "metric_type": "stock_level",
        "source_type": "direct",
        "fmp_endpoint": "/profile",
        "fmp_fields": ["beta"],
        "window_trading_days": 252,
        "price_source": "adjusted",
        "benchmark": "^GSPC",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "market_cap": {
        "display_name": "시가총액",
        "description": "발행주식수 × 현재 주가. 기업 크기 측정.",
        "formula": "sharesOutstanding × price",
        "formula_detail": "FMP /profile 엔드포인트의 mktCap 필드 직접 사용 (일간 갱신).",
        "direction": "neutral",
        "metric_type": "stock_level",
        "source_type": "direct",
        "fmp_endpoint": "/profile",
        "fmp_fields": ["mktCap"],
        "price_source": "raw",
        "comparison_group": "universe",
        "fallback_rule": "universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "return_12m": {
        "display_name": "12개월 수익률",
        "description": "최근 12개월(252 거래일) 총 수익률. 배당 재투자 포함.",
        "formula": "(adjClose_t / adjClose_{t-252}) - 1",
        "formula_detail": "Adjusted close 기준 (배당·분할 조정). MVP는 단순 12m, Phase 2에 '12-1 모멘텀' 교체 예정.",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/historical-price-full/{symbol}",
        "fmp_fields": ["adjClose"],
        "window_trading_days": 252,
        "price_source": "adjusted",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "return_6m": {
        "display_name": "6개월 수익률",
        "description": "최근 6개월(126 거래일) 총 수익률.",
        "formula": "(adjClose_t / adjClose_{t-126}) - 1",
        "formula_detail": "Adjusted close 기준.",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/historical-price-full/{symbol}",
        "fmp_fields": ["adjClose"],
        "window_trading_days": 126,
        "price_source": "adjusted",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "return_3m": {
        "display_name": "3개월 수익률",
        "description": "최근 3개월(63 거래일) 총 수익률.",
        "formula": "(adjClose_t / adjClose_{t-63}) - 1",
        "formula_detail": "Adjusted close 기준.",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/historical-price-full/{symbol}",
        "fmp_fields": ["adjClose"],
        "window_trading_days": 63,
        "price_source": "adjusted",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "relative_strength": {
        "display_name": "상대 강도",
        "description": "동일 기간 벤치마크 대비 초과 수익률. 1.0 초과 = 벤치마크 대비 강세.",
        "formula": "(1 + return_12m_stock) / (1 + return_12m_benchmark)",
        "formula_detail": "벤치마크 = S&P 500. 12개월 기준.",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/historical-price-full/{symbol}, /historical-price-full/^GSPC",
        "fmp_fields": ["adjClose"],
        "window_trading_days": 252,
        "price_source": "adjusted",
        "benchmark": "^GSPC",
        "comparison_group": "universe",
        "fallback_rule": "universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "pct_from_52w_high": {
        "display_name": "52주 고점 대비",
        "description": "현재가와 52주 최고가의 차이(%). 0%는 신고가, -30%는 고점 대비 30% 하락.",
        "formula": "(price - max(price[-252:])) / max(price[-252:])",
        "formula_detail": "Raw price 사용 (사용자 체감 일치). 계산 시점 기준 52주(252 거래일) 최고치.",
        "direction": "neutral",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/historical-price-full/{symbol}",
        "fmp_fields": ["close"],
        "window_trading_days": 252,
        "price_source": "raw",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "pct_from_52w_low": {
        "display_name": "52주 저점 대비",
        "description": "현재가와 52주 최저가의 차이(%). 0%는 52주 신저가, +50%는 저점 대비 50% 반등.",
        "formula": "(price - min(price[-252:])) / min(price[-252:])",
        "formula_detail": "Raw price 사용.",
        "direction": "neutral",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/historical-price-full/{symbol}",
        "fmp_fields": ["close"],
        "window_trading_days": 252,
        "price_source": "raw",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "volatility_1y": {
        "display_name": "1년 변동성",
        "description": "최근 252 거래일 일간 수익률의 연환산 표준편차. 연간 가격 변동 폭.",
        "formula": "stddev(log_return_i for i in last 252 days) × sqrt(252)",
        "formula_detail": "Adjusted close 기준 로그 수익률. sqrt(252)로 연환산.",
        "direction": "lower_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/historical-price-full/{symbol}",
        "fmp_fields": ["adjClose"],
        "window_trading_days": 252,
        "price_source": "adjusted",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "downside_deviation": {
        "display_name": "하방 편차",
        "description": "음수 수익률만 고려한 표준편차. 변동성 중 하락 리스크만 분리.",
        "formula": "stddev(log_return_i for i in last 252 days if log_return_i < 0) × sqrt(252)",
        "formula_detail": "목표 수익률 0% 기준. Sortino ratio의 분모로도 사용됨.",
        "direction": "lower_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/historical-price-full/{symbol}",
        "fmp_fields": ["adjClose"],
        "window_trading_days": 252,
        "price_source": "adjusted",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "max_drawdown_1y": {
        "display_name": "최대 낙폭 (1년)",
        "description": "최근 252 거래일 중 최고점에서 최저점까지의 최대 하락률.",
        "formula": "min((price_i - max(price[:i])) / max(price[:i]) for i in last 252 days)",
        "formula_detail": "Adjusted close 기준. 음수값 (예: -0.35 = -35%).",
        "direction": "lower_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/historical-price-full/{symbol}",
        "fmp_fields": ["adjClose"],
        "window_trading_days": 252,
        "price_source": "adjusted",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "volume_change_ratio": {
        "display_name": "거래량 변화율",
        "description": "최근 20 거래일 평균 거래량 / 60 거래일 평균 거래량. 단기 관심 급증 감지.",
        "formula": "mean(volume[-20:]) / mean(volume[-60:])",
        "formula_detail": "1.5 이상이면 단기 관심 급증. Contrarian 진입 신호 또는 Momentum 확인용.",
        "direction": "neutral",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/historical-price-full/{symbol}",
        "fmp_fields": ["volume"],
        "window_trading_days": 60,
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "buyback_yield": {
        "display_name": "자사주매입 수익률 (gross)",
        "description": "전년 대비 발행주식 감소율. net_buyback_yield와 달리 신주 발행은 차감하지 않음.",
        "formula": "(sharesOutstanding_prev - sharesOutstanding_curr) / sharesOutstanding_prev",
        "formula_detail": "weightedAverageShsOutDil 사용 (diluted 기준). 음수는 희석 발생.",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/income-statement?period=annual",
        "fmp_fields": ["weightedAverageShsOutDil"],
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "annual",
        "ttm_method": "latest_annual",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "ulcer_index": {
        "display_name": "Ulcer Index",
        "description": "가격 하락의 깊이+지속시간 통합 지표. 변동성과 달리 하방 리스크만 벌칙화.",
        "formula": "sqrt(mean(drawdown_i^2))",
        "formula_detail": "drawdown_i = (price_i - max(price[:i])) / max(price[:i]) × 100. 252 거래일 기준.",
        "direction": "lower_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/historical-price-full/{symbol}",
        "fmp_fields": ["adjClose"],
        "window_trading_days": 252,
        "price_source": "adjusted",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "up_capture_ratio": {
        "display_name": "상승 포착 비율",
        "description": "벤치마크 상승 기간 동안 종목이 얼마나 잘 따라가는지 측정. 100%=동일, 120%=초과 수익.",
        "formula": "cumulative_return(stock, benchmark_up_days) / cumulative_return(benchmark, benchmark_up_days) × 100",
        "formula_detail": "벤치마크 일간 수익률 > 0인 거래일만 필터링. 252 거래일 기준. 벤치마크 = S&P 500.",
        "direction": "higher_is_better",
        "metric_type": "stock_level",
        "source_type": "calculated",
        "fmp_endpoint": "/historical-price-full/{symbol}, /historical-price-full/^GSPC",
        "fmp_fields": ["adjClose"],
        "window_trading_days": 252,
        "price_source": "adjusted",
        "benchmark": "^GSPC",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "ttm_method": None,
        "excluded_sectors": [],
        "display_condition": None,
    },
    # ================================================================
    # 포트폴리오 구조 지표 (Type 2: portfolio_level) — Metric Dictionary §6
    # ================================================================
    "portfolio_volatility": {
        "display_name": "포트폴리오 변동성",
        "description": "공분산을 반영한 포트폴리오 연간 변동성. 개별 종목 변동성의 단순 합과 다름.",
        "formula": "sqrt(w^T × Σ × w) × sqrt(252)",
        "formula_detail": "w = 비중 벡터, Σ = 252일 일간 수익률 공분산 행렬.",
        "direction": "lower_is_better",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "window_trading_days": 252,
        "price_source": "adjusted",
        "benchmark": "S&P 500 동일 기간 변동성",
        "min_holdings": 2,
        "comparison_group": "benchmark",
        "refresh_frequency": "daily",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "portfolio_beta": {
        "display_name": "포트폴리오 베타",
        "description": "비중 가중 평균 베타. 포트폴리오 전체의 시장 민감도.",
        "formula": "Σ(w_i × beta_i)",
        "formula_detail": "각 종목 beta를 비중으로 가중 평균.",
        "direction": "neutral",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "dependencies": ["beta"],
        "comparison_group": "benchmark",
        "benchmark": "1.0 (시장 중립)",
        "refresh_frequency": "daily",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "sharpe_ratio": {
        "display_name": "샤프 비율",
        "description": "위험 대비 초과 수익. (수익률 - 무위험이자율) / 변동성. 단위당 리스크 당 보상.",
        "formula": "(portfolio_return - risk_free_rate) / portfolio_volatility",
        "formula_detail": "연환산. 무위험이자율 = 미국 3개월 T-Bill 수익률. 252 거래일 기준.",
        "direction": "higher_is_better",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "dependencies": ["portfolio_volatility"],
        "window_trading_days": 252,
        "price_source": "adjusted",
        "comparison_group": "benchmark",
        "benchmark": "S&P 500 Sharpe",
        "refresh_frequency": "daily",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "sortino_ratio": {
        "display_name": "소르티노 비율",
        "description": "샤프의 변형 — 하방 편차만 리스크로 계산. 상승 변동성은 리스크가 아니라는 철학.",
        "formula": "(portfolio_return - risk_free_rate) / downside_deviation",
        "formula_detail": "연환산. 분모가 하방 편차라 Sharpe보다 관대한 경향.",
        "direction": "higher_is_better",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "window_trading_days": 252,
        "price_source": "adjusted",
        "comparison_group": "benchmark",
        "benchmark": "S&P 500 Sortino",
        "refresh_frequency": "daily",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "avg_correlation": {
        "display_name": "평균 상관계수",
        "description": "보유 종목 간 pairwise 상관계수의 평균. 분산 투자 효과 측정.",
        "formula": "mean(corr(r_i, r_j) for all i < j)",
        "formula_detail": "252일 일간 로그 수익률 기준. 1에 가까울수록 종목들이 함께 움직임 (분산 효과 낮음).",
        "direction": "lower_is_better",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "window_trading_days": 252,
        "price_source": "adjusted",
        "min_holdings": 2,
        "comparison_group": "benchmark",
        "benchmark": "0.3 (전통적 분산 포트폴리오 기준)",
        "refresh_frequency": "daily",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "max_risk_contribution": {
        "display_name": "최대 리스크 기여도",
        "description": "단일 종목이 포트폴리오 전체 변동성에 기여하는 비중의 최대값. 숨은 집중 위험 감지.",
        "formula": "max(MRC_i) where MRC_i = w_i × (Σw)_i / portfolio_volatility^2",
        "formula_detail": "명목 비중(w_i)이 낮아도 변동성이 크면 실제 리스크 기여는 높을 수 있음. 20% 초과면 경고.",
        "direction": "lower_is_better",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "dependencies": ["portfolio_volatility"],
        "window_trading_days": 252,
        "price_source": "adjusted",
        "min_holdings": 2,
        "comparison_group": "benchmark",
        "benchmark": "1/N (균등 분산 시 개별 종목 기여)",
        "refresh_frequency": "daily",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "hhi_concentration": {
        "display_name": "포트폴리오 HHI 집중도",
        "description": "허핀달-허쉬만 지수. 비중의 제곱합. 균등 분산(1/N) 대비 집중 정도.",
        "formula": "Σ(w_i^2)",
        "formula_detail": "1/N = 균등 분산, 1 = 단일 종목. 0.3 초과면 집중 포트폴리오로 간주.",
        "direction": "lower_is_better",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "comparison_group": "benchmark",
        "benchmark": "1/holding_count (균등 분산 기준)",
        "refresh_frequency": "on_change",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "top3_weight": {
        "display_name": "상위 3종목 비중",
        "description": "상위 3개 종목의 비중 합. 집중 투자 측정의 직관적 지표.",
        "formula": "sum(top 3 weights)",
        "formula_detail": "holding_count < 3이면 전체 비중(= 1.0).",
        "direction": "neutral",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "min_holdings": 1,
        "comparison_group": "benchmark",
        "benchmark": "3/holding_count (균등 분산 기준)",
        "refresh_frequency": "on_change",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "holding_count": {
        "display_name": "보유 종목 수",
        "description": "포트폴리오에 포함된 고유 종목 수 (비중과 무관).",
        "formula": "len(set(holdings))",
        "formula_detail": "단독으로는 좋고 나쁨이 없으나 프리셋별 적정 범위 있음. Concentrated 5~15, Multi-Factor·Low Volatility 30+.",
        "direction": "neutral",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "min_holdings": 0,
        "comparison_group": None,
        "refresh_frequency": "on_change",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "max_position_weight": {
        "display_name": "최대 단일 비중",
        "description": "단일 종목 최대 비중. 가장 큰 포지션의 노출도.",
        "formula": "max(w_i)",
        "formula_detail": "20% 초과면 단일 종목 집중, 40% 초과면 극단적 집중.",
        "direction": "lower_is_better",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "min_holdings": 1,
        "comparison_group": "benchmark",
        "benchmark": "1/holding_count (균등 분산 기준)",
        "refresh_frequency": "on_change",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "sector_hhi": {
        "display_name": "섹터 HHI 집중도",
        "description": "섹터별 비중 합의 제곱합. 업종 분산 측정.",
        "formula": "Σ((Σ w_i for i in sector_k)^2)",
        "formula_detail": "GICS Sector 기준. 11개 섹터 기준 균등 분산 시 1/11 ≈ 0.09.",
        "direction": "lower_is_better",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "dependencies": ["종목별 sector 분류"],
        "comparison_group": "benchmark",
        "benchmark": "S&P 500 sector HHI",
        "refresh_frequency": "on_change",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "avg_market_cap": {
        "display_name": "평균 시가총액",
        "description": "비중 가중 평균 시가총액. 포트폴리오의 size bias 측정.",
        "formula": "Σ(w_i × market_cap_i)",
        "formula_detail": "대형주 편중(> $50B) vs 소형주 편중(< $2B) 식별.",
        "direction": "neutral",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "dependencies": ["market_cap"],
        "comparison_group": "benchmark",
        "benchmark": "S&P 500 평균 시총",
        "refresh_frequency": "daily",
        "excluded_sectors": [],
        "display_condition": None,
    },
    "dividend_yield_portfolio": {
        "display_name": "포트폴리오 배당수익률",
        "description": "비중 가중 평균 배당수익률. 무배당 종목은 0으로 취급.",
        "formula": "Σ(w_i × dividend_yield_i)",
        "formula_detail": "Dividend Growth 프리셋에서는 핵심 Supporting, 일반 프리셋에서는 Context.",
        "direction": "neutral",
        "metric_type": "portfolio_level",
        "source_type": "calculated",
        "dependencies": ["dividend_yield"],
        "comparison_group": "benchmark",
        "benchmark": "S&P 500 배당수익률",
        "refresh_frequency": "daily",
        "excluded_sectors": [],
        "display_condition": None,
    },
    # ================================================================
    # Multi-Factor 합성 지표 (Type 3: composite) — Metric Dictionary §7
    # ================================================================
    "composite_value": {
        "display_name": "밸류 합성",
        "description": "PE + PB + EV/EBITDA의 정규화 합성. 낮은 밸류에이션일수록 양수.",
        "formula": "weighted_mean(winsorized_z(-pe_ratio), winsorized_z(-pb_ratio), winsorized_z(-ev_to_ebitda))",
        "formula_detail": "composition: [(pe_ratio, 0.34), (pb_ratio, 0.33), (ev_to_ebitda, 0.33)]. 모두 lower_is_better이므로 부호 flip. 업종 내 winsorized z-score (2.5% 양측 클리핑).",
        "direction": "higher_is_better",
        "metric_type": "composite",
        "source_type": "composite",
        "composition_metrics": [
            ("pe_ratio", 0.34),
            ("pb_ratio", 0.33),
            ("ev_to_ebitda", 0.33),
        ],
        "normalization_method": "winsorized_z_2.5_industry",
        "aggregation_method": "weighted_mean",
        "input_direction_handling": "flip_all",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "version_pinning": True,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "composite_quality": {
        "display_name": "퀄리티 합성",
        "description": "ROIC + 매출총이익률 + 부채비율 + ROE 안정성의 정규화 합성.",
        "formula": "weighted_mean(zs(roic), zs(gross_margin), -zs(debt_to_equity), zs(roe_stability_5y))",
        "formula_detail": "composition: [(roic, 0.35), (gross_margin, 0.25), (debt_to_equity, 0.20), (roe_stability_5y, 0.20)]. debt_to_equity는 flip.",
        "direction": "higher_is_better",
        "metric_type": "composite",
        "source_type": "composite",
        "composition_metrics": [
            ("roic", 0.35),
            ("gross_margin", 0.25),
            ("debt_to_equity", 0.20),
            ("roe_stability_5y", 0.20),
        ],
        "normalization_method": "winsorized_z_2.5_industry",
        "aggregation_method": "weighted_mean",
        "input_direction_handling": "flip_debt_to_equity",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "version_pinning": True,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "composite_growth": {
        "display_name": "성장 합성",
        "description": "EPS 성장률 + 매출 성장률 + 매출 성장 지속성의 정규화 합성.",
        "formula": "weighted_mean(zs(eps_growth_yoy), zs(revenue_growth_yoy), zs(revenue_growth_consistency_3y))",
        "formula_detail": "composition: [(eps_growth_yoy, 0.40), (revenue_growth_yoy, 0.35), (revenue_growth_consistency_3y, 0.25)]. 모두 higher_is_better. 상장 3년 미만은 consistency 결측 → 2개로 가중 재분배.",
        "direction": "higher_is_better",
        "metric_type": "composite",
        "source_type": "composite",
        "composition_metrics": [
            ("eps_growth_yoy", 0.40),
            ("revenue_growth_yoy", 0.35),
            ("revenue_growth_consistency_3y", 0.25),
        ],
        "normalization_method": "winsorized_z_2.5_industry",
        "aggregation_method": "weighted_mean",
        "input_direction_handling": "no_flip",
        "comparison_group": "industry",
        "fallback_rule": "industry → sector → universe",
        "refresh_frequency": "daily",
        "version_pinning": True,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "composite_momentum": {
        "display_name": "모멘텀 합성",
        "description": "12m 수익률 + 상대강도 + 6m 수익률의 정규화 합성. Universe 전체 기준.",
        "formula": "weighted_mean(zs(return_12m), zs(relative_strength), zs(return_6m))",
        "formula_detail": "composition: [(return_12m, 0.40), (relative_strength, 0.35), (return_6m, 0.25)]. universe 기준 (모멘텀은 업종 무관 특성).",
        "direction": "higher_is_better",
        "metric_type": "composite",
        "source_type": "composite",
        "composition_metrics": [
            ("return_12m", 0.40),
            ("relative_strength", 0.35),
            ("return_6m", 0.25),
        ],
        "normalization_method": "winsorized_z_2.5_universe",
        "aggregation_method": "weighted_mean",
        "input_direction_handling": "no_flip",
        "comparison_group": "universe",
        "fallback_rule": "universe",
        "refresh_frequency": "daily",
        "version_pinning": True,
        "excluded_sectors": [],
        "display_condition": None,
    },
    "composite_low_vol": {
        "display_name": "저변동성 합성",
        "description": "1년 변동성 + 하방 편차 + 최대 낙폭의 정규화 합성 (모두 flip). 낮은 변동성일수록 양수.",
        "formula": "weighted_mean(-zs(volatility_1y), -zs(downside_deviation), -zs(max_drawdown_1y))",
        "formula_detail": "composition: [(volatility_1y, 0.40), (downside_deviation, 0.35), (max_drawdown_1y, 0.25)]. universe 기준 (저변동성은 업종 무관 특성). 모두 flip.",
        "direction": "higher_is_better",
        "metric_type": "composite",
        "source_type": "composite",
        "composition_metrics": [
            ("volatility_1y", 0.40),
            ("downside_deviation", 0.35),
            ("max_drawdown_1y", 0.25),
        ],
        "normalization_method": "winsorized_z_2.5_universe",
        "aggregation_method": "weighted_mean",
        "input_direction_handling": "flip_all",
        "comparison_group": "universe",
        "fallback_rule": "universe",
        "refresh_frequency": "daily",
        "version_pinning": True,
        "excluded_sectors": [],
        "display_condition": None,
    },
}


# ---- Helper ----
def get_metric(metric_id: str) -> dict:
    """metric_id로 지표 정의 조회. 없으면 KeyError."""
    return METRICS[metric_id]


def get_all_metric_ids() -> list[str]:
    """전체 metric_id 목록."""
    return list(METRICS.keys())


def get_metrics_by_type(metric_type: str) -> dict:
    """metric_type별 필터. 예: get_metrics_by_type("stock_level")"""
    return {k: v for k, v in METRICS.items() if v.get("metric_type") == metric_type}
