# Generated by Django 5.2.14 on 2026-07-08 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('market', 'Market'), ('sector', 'Sector'), ('theme', 'Theme'), ('fund', 'Fund'), ('stock', 'Stock')], max_length=16)),
                ('target_ref', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('setting_up', 'Setting Up'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='setting_up', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assertion', models.TextField(help_text='주장')),
                ('deadline', models.DateField(blank=True, help_text='마감', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=16)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('invalidated', 'Invalidated'), ('inconclusive', 'Inconclusive')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='monitor.monitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monitor',
            index=models.Index(fields=['user', 'status'], name='monitor_mon_user_id_3327c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.UniqueConstraint(fields=('user', 'scope', 'target_ref'), name='uniq_monitor_user_scope_target'),
        ),
    ]
