# Generated by Django 5.2.14 on 2026-07-08 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='current_state',
            field=models.CharField(choices=[('warming_up', '데이터 수집 중'), ('active', '활성 관제 중'), ('strengthening', '강화 추세'), ('weakening', '약화 추세'), ('critical', '주의 필요'), ('needs_review', '점검 필요'), ('expired', '기간 만료'), ('paused', '일시정지')], default='warming_up', max_length=20),
        ),
        migrations.AddField(
            model_name='monitor',
            name='target_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MonitorIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('indicator_type', models.CharField(choices=[('market_data', '시장 데이터'), ('macro', '거시경제'), ('sentiment', '뉴스 심리'), ('technical', '기술적 분석'), ('custom', '사용자 정의')], max_length=16)),
                ('support_direction', models.CharField(choices=[('positive', '정방향(값↑ = 지지)'), ('negative', '역방향(값↓ = 지지)')], default='positive', max_length=8)),
                ('weight', models.FloatField(default=1.0)),
                ('epsilon', models.FloatField(blank=True, null=True)),
                ('window', models.IntegerField(blank=True, null=True)),
                ('decay', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('override_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='monitor.monitor')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, null=True)),
                ('asof', models.DateTimeField()),
                ('validation_status', models.CharField(choices=[('ok', '정상'), ('extreme_jump_allowed', '극단 점프 허용'), ('rejected', '기각'), ('pending', '대기')], default='ok', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitor.monitorindicator')),
            ],
            options={
                'ordering': ['asof'],
            },
        ),
        migrations.CreateModel(
            name='MonitorSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asof_date', models.DateField()),
                ('overall_score', models.FloatField()),
                ('state', models.CharField(choices=[('warming_up', '데이터 수집 중'), ('active', '활성 관제 중'), ('strengthening', '강화 추세'), ('weakening', '약화 추세'), ('critical', '주의 필요'), ('needs_review', '점검 필요'), ('expired', '기간 만료'), ('paused', '일시정지')], max_length=20)),
                ('data_coverage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitor.monitor')),
            ],
            options={
                'ordering': ['-asof_date'],
            },
        ),
        migrations.AddIndex(
            model_name='monitorindicator',
            index=models.Index(fields=['monitor', 'is_active'], name='monitor_mon_monitor_449f93_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorreading',
            index=models.Index(fields=['indicator', 'asof'], name='monitor_ind_indicat_065e63_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitorsnapshot',
            constraint=models.UniqueConstraint(fields=('monitor', 'asof_date'), name='uniq_snapshot_monitor_asof'),
        ),
    ]
