# Generated by Django 5.2.14 on 2026-07-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_monitor_current_state_monitor_target_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorindicator',
            name='source_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
