# Generated by Django 5.2.14 on 2026-07-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_monitorindicator_source_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='indicatorreading',
            constraint=models.UniqueConstraint(fields=('indicator', 'asof'), name='uniq_reading_indicator_asof'),
        ),
    ]
