# Generated by Django 5.2.14 on 2026-07-09 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_indicatorreading_uniq_reading_indicator_asof'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='close_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='danger_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(choices=[('warming_up', '데이터 수집 중'), ('active', '활성 관제 중'), ('strengthening', '강화 추세'), ('weakening', '약화 추세'), ('critical', '주의 필요'), ('needs_review', '점검 필요'), ('expired', '기간 만료'), ('paused', '일시정지')], max_length=20)),
                ('to_state', models.CharField(choices=[('warming_up', '데이터 수집 중'), ('active', '활성 관제 중'), ('strengthening', '강화 추세'), ('weakening', '약화 추세'), ('critical', '주의 필요'), ('needs_review', '점검 필요'), ('expired', '기간 만료'), ('paused', '일시정지')], max_length=20)),
                ('asof', models.DateField()),
                ('score', models.FloatField()),
                ('is_deterioration', models.BooleanField()),
                ('is_suppressed', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.monitor')),
            ],
            options={
                'ordering': ['-asof', '-created_at'],
                'indexes': [models.Index(fields=['monitor', '-asof'], name='monitor_ale_monitor_b6252f_idx'), models.Index(fields=['is_deterioration', 'read'], name='monitor_ale_is_dete_76f342_idx')],
                'constraints': [models.UniqueConstraint(fields=('monitor', 'from_state', 'to_state', 'asof'), name='uniq_alert_monitor_transition_asof')],
            },
        ),
    ]
