# Generated by Django 5.2.14 on 2026-07-13 07:06

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_monitor_close_suggested_monitor_danger_streak_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='factor_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('timing', '타이밍'), ('ext_shock', '외부 충격'), ('indicator_noise', '지표 노이즈'), ('luck', '운')], max_length=20), blank=True, default=list, help_text='회고 요인 태그(고정 enum)', size=None),
        ),
        migrations.AddField(
            model_name='claim',
            name='proposed_verdict',
            field=models.CharField(blank=True, choices=[('validated', 'Validated'), ('partial', 'Partial'), ('invalidated', 'Invalidated')], help_text='시스템 제안 판정 (마감 전 없음)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='마감 주체', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='retro_memo',
            field=models.TextField(blank=True, default='', help_text='회고 선택 한 줄'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('partial', 'Partial'), ('invalidated', 'Invalidated'), ('inconclusive', 'Inconclusive')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='ClosureSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.FloatField(help_text='마감 시점 [-1,1] 종합점수(동결)')),
                ('payload', models.JSONField(default=dict, help_text='지표별 최종값·달위상·스파크라인 시리즈 동결')),
                ('frozen_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure_snapshot', to='monitor.claim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimIndicatorResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('hit', 'Hit'), ('partial', 'Partial'), ('miss', 'Miss'), ('na', 'N/A')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_results', to='monitor.claim')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorindicator')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('claim', 'indicator'), name='uniq_claim_indicator_result')],
            },
        ),
    ]
