# Generated by Django 5.2.14 on 2026-07-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_claim_factor_tags_claim_proposed_verdict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='진입가', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='entry_reached_at',
            field=models.DateTimeField(blank=True, help_text='진입 구간 최초 도달 시각(1회 기록)', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='fair_value_high',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='적정가 상단', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='fair_value_low',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='적정가 하단', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='last_price_zone',
            field=models.CharField(blank=True, choices=[('exited', '이탈'), ('entry', '진입 구간'), ('approach', '접근'), ('waiting', '관망'), ('overheated', '과열')], help_text='직전 가격 구간(전이 감지용)', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='stop_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='손절가', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='목표가(익절)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('partial', 'Partial'), ('invalidated', 'Invalidated'), ('inconclusive', 'Inconclusive'), ('expired', '기한만료')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='claim',
            name='proposed_verdict',
            field=models.CharField(blank=True, choices=[('validated', 'Validated'), ('partial', 'Partial'), ('invalidated', 'Invalidated'), ('expired', '기한만료')], help_text='시스템 제안 판정 (마감 전 없음)', max_length=16, null=True),
        ),
    ]
