# Generated by Django 5.2.14 on 2026-07-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_claim_entry_price_claim_entry_reached_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='매입일(보유 기간 원천)', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='매입가(확정 사실)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='scenario_type',
            field=models.CharField(choices=[('new_entry', '신규 매수'), ('hold', '보유 관리'), ('add_on', '추가 매수')], default='new_entry', help_text='시나리오 모드(신규 매수/보유 관리/추가 매수)', max_length=16),
        ),
    ]
