# Generated by Django 5.2.14 on 2026-08-10 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_claim_purchase_date_claim_purchase_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asof', models.DateField()),
                ('surface', models.CharField(choices=[('L-A', '정기 브리핑'), ('L-B', '예약(L-B)'), ('L-C', '예약(L-C)')], default='L-A', max_length=8)),
                ('headline', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('coverage_n', models.SmallIntegerField()),
                ('coverage_total', models.SmallIntegerField()),
                ('model_id', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=16)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('market_score', models.FloatField(blank=True, null=True)),
                ('close_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_notes', to='monitor.monitor')),
            ],
            options={
                'ordering': ['-asof', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('monitor', 'asof', 'surface'), name='uniq_advisor_note_monitor_asof_surface')],
            },
        ),
    ]
