# Generated by Django 5.2.14 on 2026-08-20 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_advisornote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('auto', '자동(지표)'), ('manual', '수동(서술)')], max_length=8)),
                ('operator', models.CharField(blank=True, choices=[('gte', '>='), ('lte', '<='), ('gt', '>'), ('lt', '<')], help_text='자동형 비교 연산자(raw_z 대상)', max_length=4, null=True)),
                ('threshold', models.FloatField(blank=True, help_text='자동형 임계값(raw_z 대상)', null=True)),
                ('grace_days', models.PositiveIntegerField(default=5, help_text='자동형 유예 거래일 수(연속 위반 허용 한도)')),
                ('description', models.TextField(blank=True, default='', help_text='수동형 서술')),
                ('recheck_period_days', models.PositiveIntegerField(default=90, help_text='수동형 재확인 주기(일)')),
                ('last_confirmed_at', models.DateField(blank=True, help_text='수동형 마지막 확인일', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='monitor.claim')),
                ('indicator', models.ForeignKey(blank=True, help_text='자동형 대상 지표', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_evidences', to='monitor.monitorindicator')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
