# Generated by Django 5.2.14 on 2026-08-20 05:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_claimevidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('close', '마감'), ('recommit', '재커밋'), ('hold', '보류')], max_length=8)),
                ('sentence', models.TextField(help_text='결정 한 줄(검증 없음 — ADR §6)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='monitor.claim')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SwapHoldLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('held_at', models.DateTimeField(auto_now_add=True, help_text='보류 클릭 시각')),
                ('candidate_ref', models.CharField(blank=True, help_text='검토 대상 후보 종목 심볼(대문자)', max_length=20, null=True)),
                ('hold_price', models.DecimalField(blank=True, decimal_places=4, help_text='보류 시점 보유 종목 가격(성과 앵커)', max_digits=15, null=True)),
                ('candidate_price', models.DecimalField(blank=True, decimal_places=4, help_text='보류 시점 후보 종목 가격(성과 앵커)', max_digits=15, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_logs', to='monitor.claim')),
            ],
            options={
                'ordering': ['-held_at'],
            },
        ),
    ]
