# Generated by Django 5.2.14 on 2026-09-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_decisionjournalentry_swapholdlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='near_stop_notified_at',
            field=models.DateTimeField(blank=True, help_text='손절 접근 경고 발송 시각(밴드 이탈 시 해제)', null=True),
        ),
    ]
