# Generated by Django 5.2.14 on 2026-07-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(db_index=True, default='USDKRW', help_text='통화쌍 (예: USDKRW = 1 USD당 KRW).', max_length=7)),
                ('date', models.DateField(help_text='환율 일자 (영업일).')),
                ('close', models.DecimalField(decimal_places=4, help_text='종가 환율.', max_digits=12)),
                ('source', models.CharField(default='fmp', help_text='데이터 출처.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fx_exchange_rate',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['pair', '-date'], name='fx_exchange_pair_9a89f0_idx')],
                'unique_together': {('pair', 'date')},
            },
        ),
    ]
