# Generated by Django 5.2.14 on 2026-07-04 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(db_index=True, max_length=50)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('channel', models.CharField(default='email', max_length=20)),
                ('destination', models.CharField(help_text='채널별 목적지(이메일 주소 등)', max_length=254)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='user_id 스코프 이음새(방향 B). null이면 시스템/운영 구독.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerting_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedup_key', models.CharField(max_length=255, unique=True)),
                ('source_app', models.CharField(db_index=True, max_length=50)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='failed', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='alerting.alertsubscription')),
            ],
            options={
                'db_table': 'alerting_dispatch_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertsubscription',
            index=models.Index(fields=['source_app', 'event_type', 'enabled'], name='alerting_su_source__f94a50_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertsubscription',
            constraint=models.UniqueConstraint(fields=('source_app', 'event_type', 'channel', 'destination'), name='uq_alerting_subscription_target'),
        ),
        migrations.AddIndex(
            model_name='alertdispatchlog',
            index=models.Index(fields=['status', '-created_at'], name='alerting_di_status_7d2e06_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdispatchlog',
            index=models.Index(fields=['source_app', 'event_type', '-created_at'], name='alerting_di_source__c3fe71_idx'),
        ),
    ]
