# Generated by Django 5.1.7 on 2026-04-24 02:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stocks", "0008_industryclassification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preset_id",
                    models.CharField(
                        help_text="프리셋 식별자 (코드 상수 키, 예: buffett_quality_value)",
                        max_length=50,
                    ),
                ),
                ("preset_version", models.CharField(default="1.0", max_length=20)),
                ("metric_version", models.CharField(default="1.0", max_length=20)),
                ("scoring_version", models.CharField(default="1.0", max_length=20)),
                ("prompt_version", models.CharField(default="1.0", max_length=20)),
                ("universe_version", models.CharField(default="1.0", max_length=20)),
                (
                    "portfolio_hash",
                    models.CharField(
                        help_text="포트폴리오 구성 해시 (종목+비중 기반, 중복 분석 방지용)",
                        max_length=64,
                    ),
                ),
                (
                    "status_badge",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("moderate", "Moderate"),
                            ("weak", "Weak"),
                            ("critical", "Critical"),
                        ],
                        help_text="5단계 종합 상태 (LLM 또는 스코어링 엔진이 부여)",
                        max_length=10,
                    ),
                ),
                (
                    "one_line_summary",
                    models.TextField(
                        blank=True, help_text="한 줄 진단 요약 (LLM 생성)"
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(default=False, help_text="True 이후 수정 불가"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="분석 그룹 이름. null이면 임시 그룹 (일회성).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="이 분석 묶음의 목적/근거."),
                ),
                (
                    "wallet_holding_ids",
                    models.JSONField(
                        help_text="선택된 WalletHolding UUID 리스트. 매도된 종목은 effective_holdings()에서 자동 필터링 (H3 정책)."
                    ),
                ),
                (
                    "save_type",
                    models.CharField(
                        choices=[("named", "Named"), ("temporary", "Temporary")],
                        default="temporary",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session_summary",
                    models.TextField(
                        blank=True, help_text="Tier 2 요약. 세션 종료 시 생성."
                    ),
                ),
                (
                    "analysis_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to="portfolio.analysisrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("preset_adjustment", "Preset Adjustment (Level 1)"),
                            ("preset_switch", "Preset Switch"),
                            ("holding_change_intent", "Holding Change Intent"),
                            ("thesis_note", "Thesis Note (Wallet Holding)"),
                            (
                                "portfolio_creation",
                                "Portfolio (Analysis Group) Creation",
                            ),
                            ("preference_signal", "Preference Signal (Subjective)"),
                        ],
                        max_length=40,
                    ),
                ),
                ("decision_at", models.DateTimeField()),
                (
                    "rationale_text",
                    models.TextField(
                        help_text="사용자가 남긴 자연어 근거 또는 LLM이 대화에서 추출한 요약."
                    ),
                ),
                (
                    "structured_payload",
                    models.JSONField(
                        help_text="의사결정 유형별 구조화 데이터. 예: preset_adjustment 이면 {metric_id, old_threshold, new_threshold}"
                    ),
                ),
                (
                    "source_messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="추출 출처 Message UUID 리스트.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "context_analysis_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="portfolio.analysisrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-decision_at"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosticCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        help_text="카드 우선순위 (1=가장 중요, 최대 3)"
                    ),
                ),
                (
                    "target_metric_id",
                    models.CharField(
                        help_text="진단 대상 지표 (또는 복합 이슈의 경우 대표 지표)",
                        max_length=50,
                    ),
                ),
                (
                    "problem_statement",
                    models.TextField(help_text="무엇이 문제인가 (LLM 생성)"),
                ),
                (
                    "comparison_basis",
                    models.TextField(help_text="어떤 기준 대비인가 (LLM 생성)"),
                ),
                (
                    "preset_relevance",
                    models.TextField(help_text="이 프리셋에서 왜 중요한가 (LLM 생성)"),
                ),
                (
                    "exception_tradeoff",
                    models.TextField(
                        blank=True, help_text="예외/트레이드오프가 있는가 (LLM 생성)"
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(
                        help_text="생성에 사용된 prompt_version", max_length=20
                    ),
                ),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic_cards",
                        to="portfolio.analysisrun",
                    ),
                ),
                (
                    "target_stock",
                    models.ForeignKey(
                        blank=True,
                        help_text="진단 대상 종목 (포트폴리오 레벨 진단이면 null)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnostic_cards",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="LLMComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_id",
                    models.CharField(help_text="코멘트 대상 지표", max_length=50),
                ),
                ("comment_text", models.TextField(help_text="LLM 생성 코멘트")),
                (
                    "generated_by",
                    models.CharField(
                        help_text="생성에 사용된 prompt_version", max_length=20
                    ),
                ),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_comments",
                        to="portfolio.analysisrun",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="llm_comments",
                        to="stocks.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="예: 조정 요청 시 overrides_json, 진단 카드 생성 시 cards_json.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="portfolio.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetricResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_id",
                    models.CharField(
                        help_text="지표 식별자 (코드 상수 키, 예: roic, pe_ratio)",
                        max_length=50,
                    ),
                ),
                (
                    "raw_value",
                    models.FloatField(
                        blank=True, help_text="원시 값 (예: ROIC 28.3%)", null=True
                    ),
                ),
                (
                    "percentile",
                    models.FloatField(
                        blank=True, help_text="산업 대비 퍼센타일 (0~100)", null=True
                    ),
                ),
                (
                    "level_tag",
                    models.IntegerField(
                        blank=True, help_text="5단계 레벨 (1=최하 ~ 5=최상)", null=True
                    ),
                ),
                (
                    "comparison_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='퍼센타일 산출 맥락. 예: {"comparison_group": "industry", "group_code": "Technology Hardware", "sample_size": 47, "used_fallback": false, "fallback_from": null, "percentile_date": "2026-04-15"}',
                    ),
                ),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("ok", "정상"),
                            ("missing", "데이터 없음"),
                            ("not_applicable", "해당 없음"),
                            ("delayed", "갱신 대기"),
                            ("insufficient", "제한적 데이터"),
                            ("unstable", "일시적 왜곡 가능"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                (
                    "analysis_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_results",
                        to="portfolio.analysisrun",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="metric_results",
                        to="stocks.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PercentileCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_id", models.CharField(max_length=50)),
                (
                    "industry_code",
                    models.CharField(
                        help_text="산업 분류 코드 (FMP industry 기준)", max_length=100
                    ),
                ),
                ("date", models.DateField(help_text="배치 기준일")),
                (
                    "values",
                    models.JSONField(
                        help_text='업종 내 종목별 원시 값. 예: {"AAPL": 28.3, "MSFT": 24.1}'
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(help_text="표본 수 (= len(values), 검증용)"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["metric_id", "industry_code", "-date"],
                        name="portfolio_p_metric__608551_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("metric_id", "industry_code", "date"),
                        name="unique_percentile_cache",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_runs",
                to="portfolio.portfolio",
            ),
        ),
        migrations.CreateModel(
            name="StoredAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "save_type",
                    models.CharField(
                        choices=[("saved", "영구 저장"), ("temp", "임시 저장")],
                        default="temp",
                        max_length=5,
                    ),
                ),
                (
                    "user_memo",
                    models.TextField(
                        blank=True, help_text="사용자 메모 (saved 타입에서만 의미 있음)"
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        blank=True,
                        help_text="portfolio_hash:preset_id 복합 키 (temp 중복 방지)",
                        max_length=120,
                    ),
                ),
                (
                    "portfolio_return_breakdown",
                    models.JSONField(
                        blank=True,
                        help_text="저장 시점 Portfolio 수익률 breakdown. 불변.",
                        null=True,
                    ),
                ),
                (
                    "wallet_return_breakdown",
                    models.JSONField(
                        blank=True,
                        help_text="저장 시점 Wallet 수익률 breakdown. 불변.",
                        null=True,
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_analysis",
                        to="portfolio.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="My Wallet",
                        help_text="자산 지갑 이름. MVP는 사용자당 1개.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="portfolio",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to="portfolio.wallet",
            ),
        ),
        migrations.CreateModel(
            name="WalletHolding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shares",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="보유 수량 (소수점: 분할 매수)",
                        max_digits=14,
                    ),
                ),
                (
                    "avg_cost",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="평균 매수 단가 (USD). Phase 2 Trade 모델 도입 시 자동 계산.",
                        max_digits=12,
                    ),
                ),
                ("first_bought_at", models.DateField(help_text="최초 매수일")),
                (
                    "investment_thesis",
                    models.TextField(
                        blank=True,
                        help_text="매수 시 투자 근거. Coach가 대화 맥락으로 활용.",
                    ),
                ),
                (
                    "buy_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="매수 확정 시점의 Wallet 구성 스냅샷 (thesis 집중도, 섹터 비중 등).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_holdings",
                        to="stocks.stock",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="portfolio.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("initial_setup", "Initial Setup"),
                            ("saved_analysis", "Saved Analysis"),
                            ("periodic_batch", "Periodic Batch (Phase 2)"),
                            ("manual", "Manual"),
                        ],
                        help_text="스냅샷 생성 트리거.",
                        max_length=30,
                    ),
                ),
                (
                    "triggered_by_ref",
                    models.UUIDField(
                        blank=True,
                        help_text="트리거한 StoredAnalysis 등의 ID (선택).",
                        null=True,
                    ),
                ),
                (
                    "holdings_json",
                    models.JSONField(
                        help_text="스냅샷 시점의 WalletHolding 구조화 복사. [{stock_id, shares, avg_cost, sector, industry, market_value}, ...]"
                    ),
                ),
                (
                    "aggregate_metrics",
                    models.JSONField(
                        help_text="집계 지표. {total_value, sector_distribution, industry_distribution, holding_count}"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="portfolio.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="wallet_snapshot_at_execution",
            field=models.ForeignKey(
                blank=True,
                help_text="실행 시점 Wallet 스냅샷 (Saved로 승격 시 자동 생성).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyses_at_time",
                to="portfolio.walletsnapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-started_at"], name="portfolio_c_user_id_cb088a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["analysis_run"], name="portfolio_c_analysi_bcbaa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["user", "-decision_at"], name="portfolio_d_user_id_757ec1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["decision_type"], name="portfolio_d_decisio_8c9fcf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="diagnosticcard",
            constraint=models.UniqueConstraint(
                fields=("analysis_run", "priority"), name="unique_card_priority_per_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="llmcomment",
            constraint=models.UniqueConstraint(
                fields=("analysis_run", "stock", "metric_id"),
                name="unique_comment_per_run_stock_metric",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "created_at"], name="portfolio_m_session_43145b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metricresult",
            index=models.Index(
                fields=["analysis_run", "metric_id"],
                name="portfolio_m_analysi_a8e852_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metricresult",
            index=models.Index(
                fields=["stock", "metric_id"], name="portfolio_m_stock_i_93be29_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="metricresult",
            constraint=models.UniqueConstraint(
                fields=("analysis_run", "stock", "metric_id"),
                name="unique_metric_result_per_run_stock",
            ),
        ),
        migrations.AddIndex(
            model_name="storedanalysis",
            index=models.Index(
                fields=["save_type", "-saved_at"], name="portfolio_s_save_ty_ac376e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storedanalysis",
            index=models.Index(
                fields=["dedup_key"], name="portfolio_s_dedup_k_61fa4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["user"], name="portfolio_w_user_id_939ed8_idx"),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["wallet", "save_type"], name="portfolio_p_wallet__350a3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["wallet", "name"], name="portfolio_p_wallet__9a2ed7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletholding",
            index=models.Index(
                fields=["wallet"], name="portfolio_w_wallet__1e9a11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletholding",
            index=models.Index(
                fields=["wallet", "stock"], name="portfolio_w_wallet__b32657_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="walletholding",
            unique_together={("wallet", "stock")},
        ),
        migrations.AddIndex(
            model_name="walletsnapshot",
            index=models.Index(
                fields=["wallet", "-created_at"], name="portfolio_w_wallet__50bcc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletsnapshot",
            index=models.Index(
                fields=["triggered_by"], name="portfolio_w_trigger_429419_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["portfolio", "preset_id", "-created_at"],
                name="portfolio_a_portfol_845c84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["preset_id", "prompt_version"],
                name="portfolio_a_preset__3f6ede_idx",
            ),
        ),
    ]
