# Generated by Django 5.2.14 on 2026-07-13 04:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_return_pct', models.DecimalField(decimal_places=2, help_text='목표 수익률 (%). 예: 12.00 = 연 12%.', max_digits=6)),
                ('horizon_months', models.PositiveIntegerField(help_text='투자 기간 (개월).')),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20)),
                ('exclusions', models.JSONField(blank=True, default=dict, help_text='제외 대상. 예: {"sectors": ["Energy"], "tickers": ["XOM"]}. 19a 후보 필터용.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='현금 잔고 (USD).', max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_balance', to='portfolio.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet'], name='portfolio_c_wallet__b40a72_idx')],
            },
        ),
    ]
