# Generated by Django 5.2.14 on 2026-07-13 08:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_usergoal_cashbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbalance',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('KRW', 'KRW')], default='USD', help_text='통화 (USD/KRW). 지갑당 통화별 1행.', max_length=3),
        ),
        migrations.AlterField(
            model_name='cashbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='현금 잔고 (해당 통화 단위).', max_digits=16),
        ),
        migrations.AlterField(
            model_name='cashbalance',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_balances', to='portfolio.wallet'),
        ),
        migrations.AlterUniqueTogether(
            name='cashbalance',
            unique_together={('wallet', 'currency')},
        ),
    ]
