# Generated by Django 5.2.14 on 2026-07-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_cashbalance_currency_alter_cashbalance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletholding',
            name='acquisition_fx_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='매수 시점 USD/KRW 환율, 사용자 정정 가능 (SLICE19B). null이면 매수일(first_bought_at) 환율로 근사.', max_digits=12, null=True),
        ),
    ]
