# Generated by Django 5.2.14 on 2026-07-16 02:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_walletholding_acquisition_fx_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='aggressiveness_offset',
            field=models.PositiveSmallIntegerField(default=0, help_text='A: 상시 여력 오프셋 (%p, 0~7). 다이얼 a에 상시 가산.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='concentration_limit',
            field=models.PositiveSmallIntegerField(default=30, help_text='L: 집중도 한도 (%, 15~100). 자격+TRIM 기준. 100=무제한(TRIM 소멸).', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='diversification_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='w: 코어 랭킹 분산 성분 가중 (0~0.20). 신뢰도 지배 불변식 상한.', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('0.20'))]),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='exploration_ratio',
            field=models.PositiveSmallIntegerField(default=0, help_text='E: 여력 중 탐험 레인 배정 (%, 0~30). 젊은 후보 전용.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='growth_boost',
            field=models.PositiveSmallIntegerField(default=0, help_text='G: 성장 부스트 (%p, 0~7). **신고점 국면에서만** a에 가산.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='스냅샷 일자 (실행/배치 시점 date). unique(user, date).')),
                ('total_krw', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='총자산 KRW (보유 평가 + 현금, 전부 현재 환율 KRW 환산).', max_digits=20)),
                ('by_currency', models.JSONField(blank=True, default=dict, help_text='통화별 소계. {"USD": {"holdings_krw", "cash_krw"}, "KRW": {...}}.')),
                ('holdings_detail', models.JSONField(blank=True, default=list, help_text='종목별 상세(flow 분해 재료). [{symbol, currency, shares, price, fx_rate, value_krw}, ...].')),
                ('net_flow_krw', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='이 일자 순입금 KRW(입금−출금·수동수정 잔차). dd flow 조정용.', max_digits=20)),
                ('price_as_of', models.DateField(blank=True, help_text='보유 종목 가격 기준일(최신 DailyPrice.date). 신선도 판별용.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdvisoryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('output', models.JSONField(default=dict, help_text='산출 전문(계약 v3). recommendations는 lane(core/exploration) 라벨 포함.')),
                ('knobs_snapshot', models.JSONField(default=dict, help_text='실행 당시 손잡이 5종 값. {"A", "G", "w", "L", "E"} + 파생(dd, buffer, headroom).')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_runs', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(blank=True, help_text='이 실행이 근거한 자산 스냅샷.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_runs', to='portfolio.portfoliosnapshot')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['user', '-date'], name='portfolio_p_user_id_4dee7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliosnapshot',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='advisoryrun',
            index=models.Index(fields=['user', '-run_at'], name='portfolio_a_user_id_b90e9a_idx'),
        ),
    ]
