# Generated by Django 5.2.14 on 2026-07-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_usergoal_aggressiveness_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisoryrun',
            name='trigger',
            field=models.CharField(choices=[('auto', 'Auto (nightly)'), ('manual', 'Manual (화면 진단)')], db_index=True, default='manual', help_text='실행 트리거 (SLICE20A). auto=nightly 자동 기록(원장 시계열), manual=화면 수동 진단. **사후분석은 auto만 표본으로 사용**(수동 오염 배제).', max_length=10),
        ),
    ]
