# Generated by Django 5.2.14 on 2026-07-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_advisoryrun_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletholding',
            name='first_bought_at',
            field=models.DateField(blank=True, help_text="최초 매수일. 미입력 허용(SLICE20BF1) — null이면 취득 FX를 입력일 spot으로 캡처('입력일부터 KRW 추적', 과거 환율 복원 없음).", null=True),
        ),
    ]
