# Generated by Django 5.1.7 on 2026-04-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0003_companychainprofile_companyrevenuestructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companychainprofile',
            name='neo4j_synced',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='companychainprofile',
            name='neo4j_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CoMentionEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_a', models.CharField(db_index=True, max_length=10)),
                ('symbol_b', models.CharField(db_index=True, max_length=10)),
                ('co_mention_count', models.IntegerField(default=0)),
                ('last_co_mention_date', models.DateField(blank=True, null=True)),
                ('first_co_mention_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chainsight_co_mention_edge',
                'indexes': [models.Index(fields=['symbol_a'], name='chainsight__symbol__2e286b_idx'), models.Index(fields=['symbol_b'], name='chainsight__symbol__2f07cb_idx'), models.Index(fields=['-co_mention_count'], name='chainsight__co_ment_15580b_idx')],
                'unique_together': {('symbol_a', 'symbol_b')},
            },
        ),
        migrations.CreateModel(
            name='PriceCoMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_a', models.CharField(db_index=True, max_length=10)),
                ('symbol_b', models.CharField(db_index=True, max_length=10)),
                ('correlation', models.DecimalField(decimal_places=4, max_digits=5)),
                ('period', models.CharField(choices=[('30d', '30일'), ('90d', '90일'), ('180d', '180일')], default='90d', max_length=10)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chainsight_price_co_movement',
                'indexes': [models.Index(fields=['symbol_a'], name='chainsight__symbol__2b236d_idx'), models.Index(fields=['-correlation'], name='chainsight__correla_dead19_idx')],
                'unique_together': {('symbol_a', 'symbol_b', 'period')},
            },
        ),
        migrations.CreateModel(
            name='RelationConfidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_a', models.CharField(db_index=True, max_length=10)),
                ('symbol_b', models.CharField(db_index=True, max_length=10)),
                ('has_peer_relation', models.BooleanField(default=False)),
                ('has_same_industry', models.BooleanField(default=False)),
                ('has_co_mention', models.BooleanField(default=False)),
                ('has_price_correlation', models.BooleanField(default=False)),
                ('has_supply_chain', models.BooleanField(default=False)),
                ('has_etf_theme', models.BooleanField(default=False)),
                ('source_count', models.IntegerField(default=0, help_text='True인 소스 개수')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, help_text='0.0~1.0 종합 신뢰도', max_digits=3)),
                ('relation_status', models.CharField(choices=[('confirmed', '확인됨'), ('suggested', '제안됨'), ('weak', '약함'), ('rejected', '기각됨')], default='suggested', max_length=20)),
                ('synced_to_neo4j', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chainsight_relation_confidence',
                'indexes': [models.Index(fields=['symbol_a'], name='chainsight__symbol__5e8b93_idx'), models.Index(fields=['relation_status'], name='chainsight__relatio_c49cf3_idx'), models.Index(fields=['-confidence_score'], name='chainsight__confide_218eee_idx')],
                'unique_together': {('symbol_a', 'symbol_b')},
            },
        ),
    ]
