# Generated by Django 5.1.7 on 2026-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainsight', '0004_companychainprofile_neo4j_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationconfidence',
            name='neo4j_dirty',
            field=models.BooleanField(db_index=True, default=True, help_text='True이면 Neo4j 동기화 필요. save() 시 자동 True.'),
        ),
        migrations.AddField(
            model_name='relationconfidence',
            name='neo4j_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationconfidence',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('hidden', 'Hidden'), ('weak', 'Weak'), ('probable', 'Probable'), ('confirmed', 'Confirmed'), ('stale', 'Stale')], default='', help_text='직전 상태. 시드 선정 시 relation_upgrade/downgrade 판단용.', max_length=12),
        ),
        migrations.AddIndex(
            model_name='relationconfidence',
            index=models.Index(fields=['neo4j_dirty'], name='chainsight__neo4j_d_83a5af_idx'),
        ),
    ]
