# Generated by Django 5.1.7 on 2025-12-15 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '활성'), ('completed', '완료'), ('error', '오류')], default='active', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('exploration_path', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Session',
                'verbose_name_plural': 'Analysis Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', '어시스턴트'), ('system', '시스템')], max_length=20)),
                ('content', models.TextField()),
                ('suggestions', models.JSONField(default=list)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rag_analysis.analysissession')),
            ],
            options={
                'verbose_name': 'Analysis Message',
                'verbose_name_plural': 'Analysis Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Basket', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Basket',
                'verbose_name_plural': 'Data Baskets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='analysissession',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='rag_analysis.databasket'),
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('stock', '종목'), ('news', '뉴스'), ('financial', '재무제표'), ('macro', '거시경제')], max_length=20)),
                ('reference_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('data_snapshot', models.JSONField(default=dict)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rag_analysis.databasket')),
            ],
            options={
                'verbose_name': 'Basket Item',
                'verbose_name_plural': 'Basket Items',
                'ordering': ['created_at'],
                'unique_together': {('basket', 'item_type', 'reference_id')},
            },
        ),
    ]
