# Generated by Django 5.1.7 on 2025-12-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='data_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
