# Generated by Django 5.1.7 on 2025-12-16 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_analysis', '0004_add_item_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('claude-sonnet', 'Claude Sonnet'), ('claude-haiku', 'Claude Haiku'), ('claude-opus', 'Claude Opus'), ('gemini-flash', 'Gemini Flash'), ('gemini-pro', 'Gemini Pro'), ('other', 'Other')], default='gemini-flash', max_length=50)),
                ('model_version', models.CharField(blank=True, help_text='정확한 모델 버전 (예: gemini-2.5-flash-preview-05-20)', max_length=100)),
                ('request_type', models.CharField(choices=[('analysis', '분석'), ('entity_extraction', '엔티티 추출'), ('compression', '압축'), ('embedding', '임베딩'), ('other', '기타')], default='analysis', max_length=30)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='비용 (USD)', max_digits=10)),
                ('cached', models.BooleanField(default=False, help_text='캐시 히트 여부')),
                ('cache_id', models.CharField(blank=True, help_text='캐시 히트 시 캐시 ID', max_length=100)),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='응답 시간 (밀리초)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='추가 메타데이터 (엔티티, 압축률 등)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='rag_analysis.analysismessage')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='rag_analysis.analysissession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Log',
                'verbose_name_plural': 'Usage Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='rag_analysi_user_id_e8dc5d_idx'), models.Index(fields=['model', 'created_at'], name='rag_analysi_model_48f76a_idx'), models.Index(fields=['request_type', 'created_at'], name='rag_analysi_request_947c34_idx'), models.Index(fields=['cached', 'created_at'], name='rag_analysi_cached_e20628_idx')],
            },
        ),
    ]
