# Generated by Django 5.1.7 on 2026-01-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectorETFMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50, unique=True)),
                ('etf_symbol', models.CharField(max_length=10)),
                ('sector_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'serverless_sector_etf_mapping',
                'ordering': ['sector'],
            },
        ),
        migrations.CreateModel(
            name='StockSectorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('sector', models.CharField(db_index=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'serverless_stock_sector_info',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='MarketMover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('mover_type', models.CharField(choices=[('gainers', 'Gainers'), ('losers', 'Losers'), ('actives', 'Actives')], max_length=10)),
                ('rank', models.IntegerField()),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume', models.BigIntegerField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rvol', models.DecimalField(blank=True, decimal_places=2, help_text='Relative Volume: 당일 거래량 / 20일 평균', max_digits=8, null=True)),
                ('rvol_display', models.CharField(blank=True, max_length=20, null=True)),
                ('trend_strength', models.DecimalField(blank=True, decimal_places=2, help_text='장중 추세 강도: (종가-시가) / (고가-저가)', max_digits=5, null=True)),
                ('trend_display', models.CharField(blank=True, max_length=20, null=True)),
                ('sector_alpha', models.DecimalField(blank=True, decimal_places=2, help_text='섹터 대비 초과수익', max_digits=8, null=True)),
                ('etf_sync_rate', models.DecimalField(blank=True, decimal_places=2, help_text='ETF 동행률', max_digits=5, null=True)),
                ('volatility_pct', models.IntegerField(blank=True, help_text='변동성 백분위 (0-100)', null=True)),
                ('data_quality', models.JSONField(default=dict, help_text='데이터 품질 정보 (has_20d_volume, has_ohlc 등)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'serverless_market_mover',
                'ordering': ['date', 'mover_type', 'rank'],
                'indexes': [models.Index(fields=['date', 'mover_type'], name='serverless__date_72fd6b_idx'), models.Index(fields=['symbol', 'date'], name='serverless__symbol_def1a6_idx')],
                'unique_together': {('date', 'mover_type', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='VolatilityBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField()),
                ('volatility', models.DecimalField(decimal_places=4, max_digits=8)),
                ('percentile', models.IntegerField(help_text='0-100 백분위')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'serverless_volatility_baseline',
                'ordering': ['symbol', '-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
