# Generated by Django 5.1.7 on 2026-01-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverless', '0002_add_sector_industry_to_marketmover'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('keywords', models.JSONField(default=list, help_text='LLM 생성 키워드 리스트 (3-5개)')),
                ('llm_model', models.CharField(default='gemini-2.5-flash', help_text='사용된 LLM 모델', max_length=50)),
                ('generation_time_ms', models.IntegerField(blank=True, help_text='키워드 생성 소요 시간 (밀리초)', null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, help_text='입력 토큰 수', null=True)),
                ('completion_tokens', models.IntegerField(blank=True, help_text='출력 토큰 수', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='실패 시 에러 메시지', null=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='키워드 만료 시점 (생성일 + 7일)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'serverless_stock_keyword',
                'ordering': ['-date', 'symbol'],
                'indexes': [models.Index(fields=['date', 'status'], name='serverless__date_11554c_idx'), models.Index(fields=['symbol', '-date'], name='serverless__symbol_ae0611_idx'), models.Index(fields=['expires_at'], name='serverless__expires_344413_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
