# Generated by Django 5.1.7 on 2026-01-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverless', '0003_stockkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmover',
            name='corporate_action_display',
            field=models.CharField(blank=True, help_text="이벤트 표시 텍스트 (예: '1:28 역분할')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marketmover',
            name='corporate_action_type',
            field=models.CharField(blank=True, help_text='이벤트 타입 (split, reverse_split, dividend)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marketmover',
            name='has_corporate_action',
            field=models.BooleanField(default=False, help_text='기업 이벤트(분할/배당) 존재 여부'),
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('action_type', models.CharField(choices=[('reverse_split', '역주식분할'), ('split', '주식분할'), ('spinoff', '분사'), ('dividend', '특별배당')], max_length=20)),
                ('ratio', models.DecimalField(blank=True, decimal_places=4, help_text='분할/역분할 비율', max_digits=10, null=True)),
                ('dividend_amount', models.DecimalField(blank=True, decimal_places=4, help_text='배당금 (USD)', max_digits=10, null=True)),
                ('display_text', models.CharField(help_text="표시 텍스트 (예: '1:28 역분할')", max_length=50)),
                ('source', models.CharField(default='yfinance', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'serverless_corporate_action',
                'ordering': ['-date', 'symbol'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='serverless__symbol_eba372_idx')],
                'unique_together': {('symbol', 'date', 'action_type')},
            },
        ),
    ]
