# Generated by Django 5.1.7 on 2026-01-28 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverless', '0004_add_corporate_action_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBreadth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('advancing_count', models.IntegerField(default=0, help_text='상승 종목 수')),
                ('declining_count', models.IntegerField(default=0, help_text='하락 종목 수')),
                ('unchanged_count', models.IntegerField(default=0, help_text='보합 종목 수')),
                ('new_highs', models.IntegerField(default=0, help_text='52주 신고가 종목 수')),
                ('new_lows', models.IntegerField(default=0, help_text='52주 신저가 종목 수')),
                ('up_volume', models.BigIntegerField(default=0, help_text='상승 종목 총 거래량')),
                ('down_volume', models.BigIntegerField(default=0, help_text='하락 종목 총 거래량')),
                ('advance_decline_ratio', models.DecimalField(decimal_places=3, default=1.0, help_text='상승/하락 비율 (advancing / declining)', max_digits=6)),
                ('advance_decline_line', models.IntegerField(default=0, help_text='A/D Line (누적 상승-하락)')),
                ('breadth_signal', models.CharField(choices=[('strong_bullish', '강한 상승'), ('bullish', '상승'), ('neutral', '중립'), ('bearish', '하락'), ('strong_bearish', '강한 하락')], default='neutral', help_text='시장 건강도 신호', max_length=20)),
                ('new_high_low_ratio', models.DecimalField(blank=True, decimal_places=3, help_text='신고가/신저가 비율', max_digits=6, null=True)),
                ('volume_ratio', models.DecimalField(blank=True, decimal_places=3, help_text='상승종목 거래량 / 하락종목 거래량', max_digits=6, null=True)),
                ('data_source', models.CharField(default='fmp', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Breadth',
                'verbose_name_plural': 'Market Breadths',
                'db_table': 'serverless_market_breadth',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ScreenerFilter',
            fields=[
                ('filter_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('price', '가격'), ('volume', '거래량'), ('fundamental', '펀더멘탈'), ('technical', '기술적'), ('dividend', '배당'), ('other', '기타')], max_length=20)),
                ('label', models.CharField(help_text='영문 라벨', max_length=100)),
                ('label_ko', models.CharField(help_text='한국어 라벨', max_length=100)),
                ('description', models.TextField(blank=True, help_text='필터 설명')),
                ('description_ko', models.TextField(blank=True, help_text='한국어 설명')),
                ('data_field', models.CharField(help_text='API/DB 필드명', max_length=100)),
                ('api_param', models.CharField(blank=True, help_text='FMP API 파라미터명', max_length=100)),
                ('operator_type', models.CharField(choices=[('range', '범위 (min-max)'), ('gte', '이상'), ('lte', '이하'), ('eq', '동일'), ('select', '선택'), ('multi_select', '다중 선택'), ('boolean', '참/거짓')], default='range', max_length=20)),
                ('unit', models.CharField(blank=True, help_text='단위 (%, $, B 등)', max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('default_min', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('default_max', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('step', models.DecimalField(blank=True, decimal_places=4, help_text='증가 단위', max_digits=10, null=True)),
                ('options', models.JSONField(blank=True, default=list, help_text='선택 옵션 리스트')),
                ('tooltip_key', models.CharField(blank=True, help_text='KB 문서 키', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False, help_text='프리미엄 전용 필터')),
                ('is_popular', models.BooleanField(default=False, help_text='인기 필터')),
                ('fmp_supported', models.BooleanField(default=True, help_text='FMP API에서 직접 지원')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'serverless_screener_filter',
                'ordering': ['category', 'display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SectorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('sector', models.CharField(choices=[('Technology', '기술'), ('Healthcare', '헬스케어'), ('Financial Services', '금융'), ('Consumer Cyclical', '경기소비재'), ('Industrials', '산업재'), ('Energy', '에너지'), ('Communication Services', '통신'), ('Real Estate', '부동산'), ('Utilities', '유틸리티'), ('Basic Materials', '소재'), ('Consumer Defensive', '필수소비재')], max_length=50)),
                ('return_pct', models.DecimalField(decimal_places=3, help_text='일일 수익률 (%)', max_digits=8)),
                ('market_cap', models.BigIntegerField(help_text='섹터 총 시가총액')),
                ('stock_count', models.IntegerField(help_text='섹터 내 종목 수')),
                ('etf_symbol', models.CharField(help_text='대표 ETF', max_length=10)),
                ('etf_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etf_change_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('top_gainers', models.JSONField(default=list, help_text='상위 상승 종목 (symbol, name, change_pct)')),
                ('top_losers', models.JSONField(default=list, help_text='상위 하락 종목 (symbol, name, change_pct)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'serverless_sector_performance',
                'ordering': ['-date', 'sector'],
                'indexes': [models.Index(fields=['date', '-return_pct'], name='serverless__date_ef6dde_idx')],
                'unique_together': {('date', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='ScreenerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_ko', models.TextField(blank=True, help_text='한국어 설명')),
                ('category', models.CharField(choices=[('system', '시스템 프리셋'), ('beginner', '초보자용'), ('intermediate', '중급자용'), ('advanced', '고급자용'), ('custom', '사용자 정의')], default='custom', max_length=20)),
                ('icon', models.CharField(default='📊', help_text='이모지 아이콘', max_length=10)),
                ('filters_json', models.JSONField(default=dict, help_text="필터 조건 (예: {'pe_max': 20, 'roe_min': 15})")),
                ('sort_by', models.CharField(default='change_percent', help_text='정렬 기준', max_length=50)),
                ('sort_order', models.CharField(default='desc', help_text='정렬 방향', max_length=10)),
                ('is_public', models.BooleanField(default=False, help_text='공개 프리셋 여부')),
                ('share_code', models.CharField(blank=True, help_text='공유 코드 (URL 인코딩용)', max_length=20, null=True, unique=True)),
                ('use_count', models.IntegerField(default=0, help_text='사용 횟수')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screener_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'serverless_screener_preset',
                'ordering': ['-use_count', 'name'],
                'indexes': [models.Index(fields=['category', '-use_count'], name='serverless__categor_685ea1_idx'), models.Index(fields=['user', '-use_count'], name='serverless__user_id_3a9499_idx'), models.Index(fields=['share_code'], name='serverless__share_c_5ed48c_idx')],
            },
        ),
    ]
