# Generated by Django 5.1.7 on 2026-01-29 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverless', '0006_screener_alert_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alerthistory',
            new_name='serverless__alert_i_d17e53_idx',
            old_name='serverless__alert_i_5a8b1f_idx',
        ),
        migrations.RenameIndex(
            model_name='alerthistory',
            new_name='serverless__trigger_d9ea27_idx',
            old_name='serverless__trigger_d2e8a1_idx',
        ),
        migrations.RenameIndex(
            model_name='investmentthesis',
            new_name='serverless__user_id_b8bf35_idx',
            old_name='serverless__user_id_9f1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='investmentthesis',
            new_name='serverless__is_publ_3df697_idx',
            old_name='serverless__is_publ_3e4d5a_idx',
        ),
        migrations.RenameIndex(
            model_name='investmentthesis',
            new_name='serverless__share_c_664132_idx',
            old_name='serverless__share_c_7a8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='screeneralert',
            new_name='serverless__user_id_ebaf61_idx',
            old_name='serverless__user_id_5c8e1c_idx',
        ),
        migrations.RenameIndex(
            model_name='screeneralert',
            new_name='serverless__is_acti_adbcf9_idx',
            old_name='serverless__is_acti_a7b3e4_idx',
        ),
        migrations.AddField(
            model_name='screenerpreset',
            name='view_count',
            field=models.IntegerField(default=0, help_text='조회 횟수 (Phase 2.1)'),
        ),
        migrations.AddIndex(
            model_name='screenerpreset',
            index=models.Index(fields=['is_public', '-view_count'], name='serverless__is_publ_bd9224_idx'),
        ),
    ]
