# Generated by Django 5.1.7 on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    프리셋 타입 필드 추가 (instant vs enhanced)

    - instant: FMP 직접 지원 필터만 사용 → 즉시 실행
    - enhanced: 추가 API 호출 필요 (PE/ROE/EPS Growth 등)
    """

    dependencies = [
        ('serverless', '0007_add_view_count_to_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenerpreset',
            name='preset_type',
            field=models.CharField(
                choices=[('instant', 'Instant'), ('enhanced', 'Enhanced')],
                default='instant',
                help_text='instant: FMP 직접 지원, enhanced: 추가 API 필요 (PE/ROE/EPS 등)',
                max_length=20
            ),
        ),
    ]
