# Generated by Django 5.1.7 on 2026-02-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverless', '0008_add_preset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('categories', models.JSONField(default=list, help_text='카테고리 리스트 [{id, name, tier, count, description, icon}]')),
                ('llm_model', models.CharField(default='gemini-2.5-flash', max_length=50)),
                ('generation_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='캐시 만료 시점 (생성일 + 24시간)')),
            ],
            options={
                'db_table': 'serverless_category_cache',
                'indexes': [models.Index(fields=['symbol', 'date'], name='serverless__symbol_ccb3c6_idx'), models.Index(fields=['expires_at'], name='serverless__expires_e17cf3_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_symbol', models.CharField(db_index=True, max_length=10)),
                ('target_symbol', models.CharField(db_index=True, max_length=10)),
                ('relationship_type', models.CharField(choices=[('PEER_OF', '경쟁사'), ('SAME_INDUSTRY', '동일 산업'), ('CO_MENTIONED', '뉴스 동시언급'), ('HAS_THEME', '테마 공유'), ('SUPPLIED_BY', '공급사'), ('CUSTOMER_OF', '고객사')], max_length=20)),
                ('strength', models.DecimalField(decimal_places=3, default=1.0, help_text='관계 강도 (0.0 ~ 1.0)', max_digits=4)),
                ('source_provider', models.CharField(choices=[('finnhub', 'Finnhub Peers API'), ('fmp', 'FMP Company Profile'), ('news', 'NewsEntity Co-mention'), ('manual', 'Manual Entry'), ('ai', 'AI Generated')], default='manual', max_length=20)),
                ('context', models.JSONField(default=dict, help_text='관계 컨텍스트 (예: 뉴스 헤드라인, 산업 분류 등)')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'serverless_stock_relationship',
                'indexes': [models.Index(fields=['source_symbol', 'relationship_type'], name='serverless__source__5eed49_idx'), models.Index(fields=['target_symbol', 'relationship_type'], name='serverless__target__df767b_idx'), models.Index(fields=['source_symbol', '-strength'], name='serverless__source__5676c7_idx')],
                'unique_together': {('source_symbol', 'target_symbol', 'relationship_type')},
            },
        ),
    ]
