# Generated by Django 5.1.7 on 2026-02-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverless', '0009_chain_sight_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETFProfile',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tier', models.CharField(choices=[('sector', '섹터 ETF'), ('theme', '테마 ETF')], max_length=10)),
                ('theme_id', models.CharField(db_index=True, help_text='테마 식별자 (예: semiconductor, ai, ev)', max_length=50)),
                ('csv_url', models.URLField(blank=True, max_length=500)),
                ('parser_type', models.CharField(choices=[('spdr', 'State Street (SPDR)'), ('ishares', 'iShares (BlackRock)'), ('ark', 'ARK Invest'), ('invesco', 'Invesco'), ('vanguard', 'Vanguard'), ('generic', 'Generic CSV')], default='generic', max_length=20)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('last_row_count', models.IntegerField(default=0)),
                ('last_hash', models.CharField(blank=True, help_text='CSV 콘텐츠 해시 (변경 감지용)', max_length=64)),
                ('last_error', models.TextField(blank=True, help_text='마지막 수집 에러')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'serverless_etf_profile',
                'ordering': ['tier', 'symbol'],
                'indexes': [models.Index(fields=['tier', 'is_active'], name='serverless__tier_29776c_idx'), models.Index(fields=['theme_id'], name='serverless__theme_i_0d1c9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThemeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=10)),
                ('theme_id', models.CharField(db_index=True, max_length=50)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium-high', 'Medium-High'), ('medium', 'Medium')], default='medium', max_length=20)),
                ('source', models.CharField(choices=[('etf_holding', 'ETF Holdings'), ('keyword', 'Keyword Matching'), ('co_mentioned', 'Co-mentioned with Theme'), ('multi_etf', 'Multiple ETF Match')], default='keyword', max_length=20)),
                ('etf_symbol', models.CharField(blank=True, help_text='Tier A: Holdings 출처 ETF', max_length=10, null=True)),
                ('weight_in_etf', models.DecimalField(blank=True, decimal_places=3, help_text='Tier A: ETF 내 비중 (%)', max_digits=6, null=True)),
                ('evidence', models.JSONField(default=list, help_text='매칭 근거 리스트')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'serverless_theme_match',
                'ordering': ['stock_symbol', 'theme_id'],
                'indexes': [models.Index(fields=['theme_id', 'confidence'], name='serverless__theme_i_90dc2d_idx'), models.Index(fields=['stock_symbol', '-confidence'], name='serverless__stock_s_bd7091_idx')],
                'unique_together': {('stock_symbol', 'theme_id')},
            },
        ),
        migrations.CreateModel(
            name='ETFHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=10)),
                ('weight_percent', models.DecimalField(decimal_places=3, help_text='비중 (%)', max_digits=6)),
                ('shares', models.BigIntegerField(blank=True, help_text='보유 주식 수', null=True)),
                ('rank', models.IntegerField(help_text='비중 순위')),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, help_text='시장 가치 (USD)', max_digits=18, null=True)),
                ('snapshot_date', models.DateField()),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='serverless.etfprofile')),
            ],
            options={
                'db_table': 'serverless_etf_holding',
                'ordering': ['etf', 'rank'],
                'indexes': [models.Index(fields=['stock_symbol', 'snapshot_date'], name='serverless__stock_s_34d166_idx'), models.Index(fields=['etf', 'rank'], name='serverless__etf_id_6fe778_idx')],
                'unique_together': {('etf', 'stock_symbol', 'snapshot_date')},
            },
        ),
    ]
