# Generated by Django 5.1.7 on 2026-02-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverless', '0010_etf_holdings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('PEER_OF', '경쟁사'), ('SAME_INDUSTRY', '동일 산업'), ('CO_MENTIONED', '뉴스 동시언급'), ('HAS_THEME', '테마 공유'), ('SUPPLIED_BY', '공급사'), ('CUSTOMER_OF', '고객사'), ('ACQUIRED', '인수'), ('INVESTED_IN', '투자'), ('PARTNER_OF', '파트너'), ('SPIN_OFF', '분사'), ('SUED_BY', '소송')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockrelationship',
            name='source_provider',
            field=models.CharField(choices=[('finnhub', 'Finnhub Peers API'), ('fmp', 'FMP Company Profile'), ('news', 'NewsEntity Co-mention'), ('manual', 'Manual Entry'), ('ai', 'AI Generated'), ('llm_news', 'LLM News Extraction'), ('llm_sec', 'LLM SEC Filing Extraction')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='LLMExtractedRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_symbol', models.CharField(db_index=True, help_text="관계의 주체 (예: MSFT in 'MSFT acquired ATVI')", max_length=10)),
                ('target_symbol', models.CharField(db_index=True, help_text="관계의 대상 (예: ATVI in 'MSFT acquired ATVI')", max_length=10)),
                ('relation_type', models.CharField(choices=[('ACQUIRED', '인수'), ('INVESTED_IN', '투자'), ('PARTNER_OF', '파트너'), ('SPIN_OFF', '분사'), ('SUED_BY', '소송')], db_index=True, max_length=20)),
                ('source_type', models.CharField(choices=[('news', '뉴스'), ('sec_10k', 'SEC 10-K'), ('sec_8k', 'SEC 8-K'), ('sec_13f', 'SEC 13-F')], default='news', max_length=20)),
                ('source_id', models.CharField(blank=True, help_text='뉴스 UUID 또는 SEC 파일링 ID', max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, help_text='원본 소스 URL', null=True)),
                ('evidence', models.TextField(help_text='관계를 증명하는 원문 발췌 (최대 500자)')),
                ('context', models.JSONField(default=dict, help_text='추가 컨텍스트 (금액, 날짜, 조건 등)')),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('llm_confidence_score', models.DecimalField(blank=True, decimal_places=3, help_text='LLM이 반환한 신뢰도 점수 (0.0 ~ 1.0)', max_digits=4, null=True)),
                ('llm_model', models.CharField(default='gemini-2.5-flash', max_length=50)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('extraction_time_ms', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='수동 검증 완료 여부')),
                ('is_synced_to_graph', models.BooleanField(db_index=True, default=False, help_text='StockRelationship/Neo4j 동기화 여부')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='TTL 만료 시점 (기본 30일)')),
            ],
            options={
                'db_table': 'serverless_llm_extracted_relation',
                'ordering': ['-extracted_at'],
                'indexes': [models.Index(fields=['source_symbol', 'relation_type'], name='serverless__source__3f548b_idx'), models.Index(fields=['target_symbol', 'relation_type'], name='serverless__target__45b721_idx'), models.Index(fields=['extracted_at'], name='serverless__extract_4cb71f_idx'), models.Index(fields=['is_synced_to_graph', '-extracted_at'], name='serverless__is_sync_87d786_idx'), models.Index(fields=['confidence', '-llm_confidence_score'], name='serverless__confide_cf7a8a_idx')],
                'unique_together': {('source_symbol', 'target_symbol', 'relation_type', 'source_id')},
            },
        ),
    ]
