# Generated by Django 5.1.7 on 2026-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverless', '0011_llm_extracted_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('PEER_OF', '경쟁사'), ('SAME_INDUSTRY', '동일 산업'), ('CO_MENTIONED', '뉴스 동시언급'), ('HAS_THEME', '테마 공유'), ('SUPPLIED_BY', '공급사'), ('CUSTOMER_OF', '고객사'), ('ACQUIRED', '인수'), ('INVESTED_IN', '투자'), ('PARTNER_OF', '파트너'), ('SPIN_OFF', '분사'), ('SUED_BY', '소송'), ('HELD_BY_SAME_FUND', '동일 펀드 보유'), ('SAME_REGULATION', '규제 공유'), ('PATENT_CITED', '특허 인용'), ('PATENT_DISPUTE', '특허 분쟁')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockrelationship',
            name='source_provider',
            field=models.CharField(choices=[('finnhub', 'Finnhub Peers API'), ('fmp', 'FMP Company Profile'), ('news', 'NewsEntity Co-mention'), ('manual', 'Manual Entry'), ('ai', 'AI Generated'), ('llm_news', 'LLM News Extraction'), ('llm_sec', 'LLM SEC Filing Extraction'), ('sec_13f', 'SEC 13F Filing'), ('sec_8k', 'SEC 8-K Filing'), ('regulatory_llm', 'Regulatory LLM'), ('uspto', 'USPTO PatentsView')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='InstitutionalHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_cik', models.CharField(db_index=True, help_text='기관 CIK (SEC 식별번호)', max_length=20)),
                ('institution_name', models.CharField(help_text='기관명', max_length=300)),
                ('filing_date', models.DateField(db_index=True, help_text='공시일')),
                ('report_date', models.DateField(help_text='보고 기준일')),
                ('accession_number', models.CharField(help_text='SEC 접수번호', max_length=30)),
                ('stock_symbol', models.CharField(db_index=True, help_text='종목 심볼', max_length=10)),
                ('shares', models.BigIntegerField(help_text='보유 주식 수')),
                ('value_thousands', models.BigIntegerField(help_text='보유 가치 (천 달러)')),
                ('shares_change', models.BigIntegerField(blank=True, help_text='전 분기 대비 주식 수 변동', null=True)),
                ('position_change', models.CharField(blank=True, choices=[('new', '신규 매수'), ('increased', '증가'), ('decreased', '감소'), ('sold_all', '전량 매도'), ('unchanged', '변동 없음')], help_text='포지션 변화', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'serverless_institutional_holding',
                'ordering': ['-report_date', 'institution_name'],
                'indexes': [models.Index(fields=['institution_cik', '-report_date'], name='serverless__institu_7e8f9a_idx'), models.Index(fields=['stock_symbol', '-report_date'], name='serverless__stock_s_8c4b2d_idx'), models.Index(fields=['report_date', 'institution_cik'], name='serverless__report__5a9c3f_idx')],
                'unique_together': {('institution_cik', 'stock_symbol', 'report_date')},
            },
        ),
    ]
