# Generated by Django 5.1.7 on 2026-02-23 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverless', '0012_institutional_holdings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='dispatched', max_length=20)),
                ('result_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'serverless_admin_action_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='institutionalholding',
            new_name='serverless__institu_f1a7dc_idx',
            old_name='serverless__institu_7e8f9a_idx',
        ),
        migrations.RenameIndex(
            model_name='institutionalholding',
            new_name='serverless__stock_s_8596cf_idx',
            old_name='serverless__stock_s_8c4b2d_idx',
        ),
        migrations.RenameIndex(
            model_name='institutionalholding',
            new_name='serverless__report__a8e29b_idx',
            old_name='serverless__report__5a9c3f_idx',
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['-created_at', 'action'], name='serverless__created_18ec14_idx'),
        ),
    ]
