# Generated by Django 5.1.7 on 2025-11-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_api_call',
            field=models.DateTimeField(blank=True, help_text='Last time Alpha Vantage API was called for this stock', null=True),
        ),
    ]
