# Generated by Django 5.1.7 on 2025-04-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_currency_stock_sector_balancesheet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='stock_name',
        ),
    ]
