# Generated by Django 5.1.7 on 2026-02-26 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_sp500constituent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EODDashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('json_data', models.JSONField()),
                ('total_signals', models.IntegerField(default=0)),
                ('total_stocks', models.IntegerField(default=0)),
                ('signal_distribution', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField()),
                ('pipeline_duration_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stocks_eod_dashboard_snapshot',
            },
        ),
        migrations.CreateModel(
            name='PipelineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('run_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=10)),
                ('stages', models.JSONField(default=dict)),
                ('ingest_quality', models.JSONField(default=dict)),
                ('total_duration_seconds', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stocks_pipeline_log',
                'indexes': [models.Index(fields=['-date', 'status'], name='stocks_pipe_date_3c8702_idx')],
            },
        ),
        migrations.CreateModel(
            name='EODSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('signals', models.JSONField(default=list)),
                ('tag_details', models.JSONField(default=dict)),
                ('signal_count', models.IntegerField(default=0)),
                ('bullish_count', models.IntegerField(default=0)),
                ('bearish_count', models.IntegerField(default=0)),
                ('composite_score', models.FloatField(default=0.0)),
                ('news_context', models.JSONField(default=dict)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('change_percent', models.FloatField(default=0.0)),
                ('volume', models.BigIntegerField(default=0)),
                ('dollar_volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'db_table': 'stocks_eod_signal',
                'indexes': [models.Index(fields=['date', '-composite_score'], name='stocks_eod__date_620945_idx'), models.Index(fields=['date', '-signal_count'], name='stocks_eod__date_dda178_idx'), models.Index(fields=['stock', '-date'], name='stocks_eod__stock_i_477304_idx'), models.Index(fields=['date', 'sector'], name='stocks_eod__date_d4225b_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SignalAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_date', models.DateField()),
                ('signal_tag', models.CharField(max_length=10)),
                ('signal_value', models.FloatField()),
                ('close_at_signal', models.DecimalField(decimal_places=4, max_digits=15)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('vix_at_signal', models.FloatField(null=True)),
                ('spy_change_at_signal', models.FloatField(null=True)),
                ('return_1d', models.FloatField(blank=True, null=True)),
                ('return_5d', models.FloatField(blank=True, null=True)),
                ('return_20d', models.FloatField(blank=True, null=True)),
                ('excess_1d', models.FloatField(blank=True, null=True)),
                ('excess_5d', models.FloatField(blank=True, null=True)),
                ('excess_20d', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'db_table': 'stocks_signal_accuracy',
                'indexes': [models.Index(fields=['signal_date', 'signal_tag'], name='stocks_sign_signal__284e24_idx')],
                'unique_together': {('stock', 'signal_date', 'signal_tag')},
            },
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('headline', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('sentiment', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'db_table': 'stocks_stock_news',
                'indexes': [models.Index(fields=['symbol', '-published_at'], name='stocks_stoc_symbol_ea398f_idx'), models.Index(fields=['sector', '-published_at'], name='stocks_stoc_sector_54dd87_idx'), models.Index(fields=['industry', '-published_at'], name='stocks_stoc_industr_e03659_idx'), models.Index(fields=['-published_at'], name='stocks_stoc_publish_c66d9f_idx')],
            },
        ),
    ]
