# Generated by Django 5.1.7 on 2026-02-26 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_eoddashboardsnapshot_pipelinelog_eodsignal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOverviewKo',
            fields=[
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='overview_ko', serialize=False, to='stocks.stock')),
                ('summary', models.TextField(help_text='한글 기업 개요 요약 (2-3문단)')),
                ('business_model', models.TextField(blank=True, default='', help_text='사업 모델 설명')),
                ('competitive_edge', models.TextField(blank=True, default='', help_text='경쟁 우위 및 해자')),
                ('risk_factors', models.TextField(blank=True, default='', help_text='주요 리스크 요인')),
                ('llm_model', models.CharField(default='gemini-2.5-flash', max_length=50)),
                ('generated_at', models.DateTimeField()),
                ('generation_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stocks_overview_ko',
            },
        ),
    ]
