# Generated by Django 5.1.7 on 2026-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stockoverviewko'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp500constituent',
            name='industry',
            field=models.CharField(blank=True, default='', help_text='세부 산업 (FMP Profile industry)', max_length=100),
        ),
        migrations.AddField(
            model_name='sp500constituent',
            name='is_core_universe',
            field=models.BooleanField(db_index=True, default=True, help_text='핵심 커버리지 여부'),
        ),
        migrations.AddField(
            model_name='sp500constituent',
            name='universe_source',
            field=models.CharField(choices=[('sp500', 'S&P 500 Index'), ('manual', 'Manual Addition'), ('screener', 'Screener Result')], default='sp500', max_length=50),
        ),
    ]
